# setup

In [1]:
# Tìm thư mục gốc của dự án để notebook biết nơi chứa mã nguồn và dữ liệu.
from pathlib import Path
import sys
import cv2
import torch
import pandas as pd
from tqdm import tqdm
from ultralytics import YOLO

def find_project_root(max_up=6):
    p = Path.cwd()
    for _ in range(max_up + 1):
        if (p / "src").exists() and (p / "configs").exists():
            return p
        if p.parent == p:
            break
        p = p.parent
    return Path.cwd()

PROJECT_ROOT = find_project_root()

sys.path.append(str(PROJECT_ROOT))

from src.config import load_yaml
from src.io_utils import save_csv

print("PROJECT_ROOT:", PROJECT_ROOT)
print("CUDA:", torch.cuda.is_available())

PROJECT_ROOT: D:\hoiancomputervision\ticket_suspicion_project
CUDA: False

# Load config và frame index

In [2]:
# Đọc các file cấu hình từ thư mục configs để biết tham số chạy và các vùng ROI.
pipeline_cfg = load_yaml(PROJECT_ROOT / "configs" / "pipeline_config.yaml")

mot_root = PROJECT_ROOT / "data" / "raw" / "MOT17" / "train"

def parse_seqinfo(seq_dir):
    fps = 30.0
    width = 0
    height = 0
    ini_path = seq_dir / "seqinfo.ini"
    if ini_path.exists():
        import configparser
        config = configparser.ConfigParser()
        config.read(ini_path)
        if "Sequence" in config:
            seq_info = config["Sequence"]
            fps = float(seq_info.get("frameRate", seq_info.get("frame_rate", fps)))
            width = int(seq_info.get("imWidth", seq_info.get("imgWidth", width)))
            height = int(seq_info.get("imHeight", seq_info.get("imgHeight", height)))
    return fps, width, height


def build_frame_index(root_dir):
    rows = []
    if not root_dir.exists():
        return pd.DataFrame(rows)

    for seq_dir in sorted(root_dir.iterdir()):
        img_dir = seq_dir / "img1"
        if not img_dir.exists() or not img_dir.is_dir():
            continue

        sequence_name = seq_dir.name
        camera_id = sequence_name
        fps, width, height = parse_seqinfo(seq_dir)
        image_paths = sorted(img_dir.glob("*.jpg"))

        for frame_id, image_path in enumerate(image_paths, start=1):
            timestamp_sec = (frame_id - 1) / fps if fps > 0 else 0.0
            rows.append({
                "camera_id": camera_id,
                "sequence_name": sequence_name,
                "frame_id": frame_id,
                "timestamp_sec": timestamp_sec,
                "image_path": str(image_path),
                "width": width,
                "height": height,
                "fps": fps,
            })

    return pd.DataFrame(rows)

frame_index_df = build_frame_index(mot_root)
frame_index_path = PROJECT_ROOT / "outputs" / "frames" / "frame_index.csv"
frame_index_path.parent.mkdir(parents=True, exist_ok=True)
frame_index_df.to_csv(frame_index_path, index=False)
print("Loaded frame_index from:", mot_root)
print("Sequences found:", frame_index_df["sequence_name"].nunique())
print("Total frames:", len(frame_index_df))
frame_index_df.head()

Loaded frame_index from: D:\hoiancomputervision\ticket_suspicion_project\data\raw\MOT17\train
Sequences found: 7
Total frames: 5316

,camera_id,sequence_name,frame_id,timestamp_sec,image_path,width,height,fps
0,MOT17-02-FRCNN,MOT17-02-FRCNN,1,0.000000,D:\hoiancomputervision\ticket_suspicion_projec...,1920,1080,30.0
1,MOT17-02-FRCNN,MOT17-02-FRCNN,2,0.033333,D:\hoiancomputervision\ticket_suspicion_projec...,1920,1080,30.0
2,MOT17-02-FRCNN,MOT17-02-FRCNN,3,0.066667,D:\hoiancomputervision\ticket_suspicion_projec...,1920,1080,30.0
3,MOT17-02-FRCNN,MOT17-02-FRCNN,4,0.100000,D:\hoiancomputervision\ticket_suspicion_projec...,1920,1080,30.0
4,MOT17-02-FRCNN,MOT17-02-FRCNN,5,0.133333,D:\hoiancomputervision\ticket_suspicion_projec...,1920,1080,30.0

# Load YOLO

In [3]:
# Cell này thực hiện một bước cụ thể trong luồng pipeline, có thể là nạp dữ liệu, xử lý, hoặc lưu kết quả.
det_cfg = pipeline_cfg["detector"]

model = YOLO(det_cfg["model"])
device = 0 if torch.cuda.is_available() else "cpu"

print("Using device:", device)

Using device: cpu

# Chạy YOLO + ByteTrack

In [4]:
# Lưu dữ liệu trung gian dưới dạng CSV để các bước khác có thể đọc lại được.
conf_thres = det_cfg["confidence_threshold"]
iou_thres = det_cfg["iou_threshold"]
person_class_id = det_cfg["person_class_id"]
tracker_yaml = pipeline_cfg["tracker"]["tracker_yaml"]

output_rows = []

for camera_id, cam_df in frame_index_df.groupby("camera_id"):
    cam_df = cam_df.sort_values("frame_id").reset_index(drop=True)

    print(f"Processing camera: {camera_id}, frames: {len(cam_df)}")

    for _, frame_row in tqdm(cam_df.iterrows(), total=len(cam_df)):
        frame = cv2.imread(frame_row["image_path"])

        if frame is None:
            continue

        results = model.track(
            source=frame,
            persist=True,
            tracker=tracker_yaml,
            conf=conf_thres,
            iou=iou_thres,
            classes=[person_class_id],
            verbose=False,
            device=device
        )

        boxes = results[0].boxes

        if boxes is None or boxes.id is None:
            continue

        xyxy = boxes.xyxy.cpu().numpy()
        confs = boxes.conf.cpu().numpy()
        ids = boxes.id.cpu().numpy().astype(int)

        for bbox, conf, track_id in zip(xyxy, confs, ids):
            x1, y1, x2, y2 = bbox.tolist()

            output_rows.append({
                "camera_id": camera_id,
                "sequence_name": frame_row["sequence_name"],
                "frame_id": int(frame_row["frame_id"]),
                "timestamp_sec": float(frame_row["timestamp_sec"]),
                "image_path": frame_row["image_path"],
                "local_track_id": int(track_id),
                "confidence": float(conf),
                "x1": float(x1),
                "y1": float(y1),
                "x2": float(x2),
                "y2": float(y2)
            })

tracks_df = pd.DataFrame(output_rows)

out_path = PROJECT_ROOT / "outputs/tracks/tracks.csv"
save_csv(tracks_df, out_path)

print("Saved:", out_path)
print("Rows:", len(tracks_df))
tracks_df.head()

Processing camera: MOT17-02-FRCNN, frames: 600

  0%|          | 0/600 [00:00<?, ?it/s]

  0%|          | 1/600 [00:01<18:23,  1.84s/it]

  1%|          | 4/600 [00:01<03:49,  2.60it/s]

  1%|          | 7/600 [00:02<01:59,  4.96it/s]

  2%|▏         | 10/600 [00:02<01:18,  7.55it/s]

  2%|▏         | 13/600 [00:02<00:55, 10.49it/s]

  3%|▎         | 16/600 [00:02<00:43, 13.30it/s]

  3%|▎         | 19/600 [00:02<00:36, 15.83it/s]

  4%|▎         | 22/600 [00:02<00:31, 18.47it/s]

  4%|▍         | 25/600 [00:02<00:28, 20.22it/s]

  5%|▍         | 28/600 [00:02<00:26, 21.89it/s]

  5%|▌         | 31/600 [00:03<00:25, 22.55it/s]

  6%|▌         | 34/600 [00:03<00:25, 22.00it/s]

  6%|▌         | 37/600 [00:03<00:25, 22.47it/s]

  7%|▋         | 40/600 [00:03<00:24, 22.96it/s]

  7%|▋         | 43/600 [00:03<00:24, 23.10it/s]

  8%|▊         | 46/600 [00:03<00:24, 22.99it/s]

  8%|▊         | 49/600 [00:03<00:24, 22.65it/s]

  9%|▊         | 52/600 [00:03<00:24, 22.78it/s]

  9%|▉         | 55/600 [00:04<00:25, 21.12it/s]

 10%|▉         | 58/600 [00:04<00:25, 21.44it/s]

 10%|█         | 61/600 [00:04<00:24, 21.77it/s]

 11%|█         | 64/600 [00:04<00:24, 21.52it/s]

 11%|█         | 67/600 [00:04<00:24, 21.40it/s]

 12%|█▏        | 70/600 [00:04<00:24, 21.27it/s]

 12%|█▏        | 73/600 [00:04<00:24, 21.16it/s]

 13%|█▎        | 76/600 [00:05<00:24, 21.02it/s]

 13%|█▎        | 79/600 [00:05<00:24, 21.18it/s]

 14%|█▎        | 82/600 [00:05<00:24, 21.53it/s]

 14%|█▍        | 85/600 [00:05<00:23, 22.22it/s]

 15%|█▍        | 88/600 [00:05<00:22, 22.62it/s]

 15%|█▌        | 91/600 [00:05<00:22, 23.02it/s]

 16%|█▌        | 94/600 [00:05<00:22, 22.67it/s]

 16%|█▌        | 97/600 [00:06<00:22, 22.53it/s]

 17%|█▋        | 100/600 [00:06<00:22, 22.54it/s]

 17%|█▋        | 103/600 [00:06<00:22, 22.44it/s]

 18%|█▊        | 106/600 [00:06<00:21, 22.99it/s]

 18%|█▊        | 109/600 [00:06<00:21, 22.65it/s]

 19%|█▊        | 112/600 [00:06<00:21, 23.10it/s]

 19%|█▉        | 115/600 [00:06<00:21, 22.93it/s]

 20%|█▉        | 118/600 [00:06<00:21, 22.66it/s]

 20%|██        | 121/600 [00:07<00:21, 22.58it/s]

 21%|██        | 124/600 [00:07<00:20, 23.47it/s]

 21%|██        | 127/600 [00:07<00:20, 23.35it/s]

 22%|██▏       | 130/600 [00:07<00:20, 23.27it/s]

 22%|██▏       | 133/600 [00:07<00:20, 23.00it/s]

 23%|██▎       | 136/600 [00:07<00:20, 22.30it/s]

 23%|██▎       | 139/600 [00:07<00:21, 21.24it/s]

 24%|██▎       | 142/600 [00:08<00:20, 22.49it/s]

 24%|██▍       | 145/600 [00:08<00:20, 22.06it/s]

 25%|██▍       | 148/600 [00:08<00:20, 21.97it/s]

 25%|██▌       | 151/600 [00:08<00:22, 19.97it/s]

 26%|██▌       | 154/600 [00:08<00:22, 19.82it/s]

 26%|██▌       | 157/600 [00:08<00:21, 20.40it/s]

 27%|██▋       | 160/600 [00:08<00:21, 20.32it/s]

 27%|██▋       | 163/600 [00:09<00:21, 20.43it/s]

 28%|██▊       | 166/600 [00:09<00:20, 21.29it/s]

 28%|██▊       | 169/600 [00:09<00:20, 21.06it/s]

 29%|██▊       | 172/600 [00:09<00:20, 20.95it/s]

 29%|██▉       | 175/600 [00:09<00:20, 20.78it/s]

 30%|██▉       | 178/600 [00:09<00:20, 20.54it/s]

 30%|███       | 181/600 [00:09<00:20, 20.13it/s]

 31%|███       | 184/600 [00:10<00:20, 20.11it/s]

 31%|███       | 187/600 [00:10<00:20, 20.53it/s]

 32%|███▏      | 190/600 [00:10<00:18, 22.03it/s]

 32%|███▏      | 193/600 [00:10<00:18, 22.23it/s]

 33%|███▎      | 196/600 [00:10<00:18, 22.18it/s]

 33%|███▎      | 199/600 [00:10<00:18, 21.62it/s]

 34%|███▎      | 202/600 [00:10<00:18, 21.47it/s]

 34%|███▍      | 205/600 [00:11<00:18, 21.36it/s]

 35%|███▍      | 208/600 [00:11<00:17, 21.80it/s]

 35%|███▌      | 211/600 [00:11<00:16, 23.09it/s]

 36%|███▌      | 214/600 [00:11<00:16, 23.36it/s]

 36%|███▌      | 217/600 [00:11<00:16, 22.74it/s]

 37%|███▋      | 220/600 [00:11<00:16, 23.11it/s]

 37%|███▋      | 223/600 [00:11<00:16, 22.89it/s]

 38%|███▊      | 226/600 [00:11<00:16, 23.16it/s]

 38%|███▊      | 229/600 [00:12<00:16, 22.71it/s]

 39%|███▊      | 232/600 [00:12<00:16, 22.61it/s]

 39%|███▉      | 235/600 [00:12<00:16, 22.55it/s]

 40%|███▉      | 238/600 [00:12<00:16, 22.40it/s]

 40%|████      | 241/600 [00:12<00:16, 21.81it/s]

 41%|████      | 244/600 [00:12<00:16, 21.55it/s]

 41%|████      | 247/600 [00:12<00:17, 20.13it/s]

 42%|████▏     | 250/600 [00:13<00:17, 20.42it/s]

 42%|████▏     | 253/600 [00:13<00:16, 20.50it/s]

 43%|████▎     | 256/600 [00:13<00:16, 21.08it/s]

 43%|████▎     | 259/600 [00:13<00:16, 20.87it/s]

 44%|████▎     | 262/600 [00:13<00:15, 21.26it/s]

 44%|████▍     | 265/600 [00:13<00:15, 21.82it/s]

 45%|████▍     | 268/600 [00:13<00:15, 21.47it/s]

 45%|████▌     | 271/600 [00:14<00:15, 20.92it/s]

 46%|████▌     | 274/600 [00:14<00:15, 21.20it/s]

 46%|████▌     | 277/600 [00:14<00:15, 21.00it/s]

 47%|████▋     | 280/600 [00:14<00:15, 21.26it/s]

 47%|████▋     | 283/600 [00:14<00:15, 21.09it/s]

 48%|████▊     | 286/600 [00:14<00:14, 21.32it/s]

 48%|████▊     | 289/600 [00:14<00:14, 20.95it/s]

 49%|████▊     | 292/600 [00:15<00:14, 21.20it/s]

 49%|████▉     | 295/600 [00:15<00:14, 21.05it/s]

 50%|████▉     | 298/600 [00:15<00:14, 21.07it/s]

 50%|█████     | 301/600 [00:15<00:14, 21.22it/s]

 51%|█████     | 304/600 [00:15<00:13, 22.18it/s]

 51%|█████     | 307/600 [00:15<00:12, 23.06it/s]

 52%|█████▏    | 310/600 [00:15<00:12, 22.55it/s]

 52%|█████▏    | 313/600 [00:15<00:12, 22.10it/s]

 53%|█████▎    | 316/600 [00:16<00:13, 21.52it/s]

 53%|█████▎    | 319/600 [00:16<00:12, 23.19it/s]

 54%|█████▎    | 322/600 [00:16<00:11, 23.99it/s]

 54%|█████▍    | 325/600 [00:16<00:11, 23.93it/s]

 55%|█████▍    | 328/600 [00:16<00:11, 22.75it/s]

 55%|█████▌    | 331/600 [00:16<00:11, 22.69it/s]

 56%|█████▌    | 334/600 [00:16<00:11, 23.96it/s]

 56%|█████▌    | 337/600 [00:16<00:10, 24.99it/s]

 57%|█████▋    | 340/600 [00:17<00:10, 25.50it/s]

 57%|█████▋    | 343/600 [00:17<00:10, 24.91it/s]

 58%|█████▊    | 346/600 [00:17<00:10, 24.75it/s]

 58%|█████▊    | 349/600 [00:17<00:10, 23.54it/s]

 59%|█████▊    | 352/600 [00:17<00:10, 23.40it/s]

 59%|█████▉    | 355/600 [00:17<00:10, 23.97it/s]

 60%|█████▉    | 358/600 [00:17<00:09, 24.63it/s]

 60%|██████    | 361/600 [00:17<00:09, 25.24it/s]

 61%|██████    | 364/600 [00:18<00:09, 26.09it/s]

 61%|██████    | 367/600 [00:18<00:08, 26.02it/s]

 62%|██████▏   | 370/600 [00:18<00:09, 25.19it/s]

 62%|██████▏   | 373/600 [00:18<00:09, 23.81it/s]

 63%|██████▎   | 376/600 [00:18<00:09, 23.64it/s]

 63%|██████▎   | 379/600 [00:18<00:09, 24.51it/s]

 64%|██████▎   | 382/600 [00:18<00:08, 25.40it/s]

 64%|██████▍   | 385/600 [00:18<00:08, 25.74it/s]

 65%|██████▍   | 388/600 [00:19<00:08, 26.39it/s]

 65%|██████▌   | 391/600 [00:19<00:07, 26.58it/s]

 66%|██████▌   | 394/600 [00:19<00:07, 26.78it/s]

 66%|██████▌   | 397/600 [00:19<00:07, 27.15it/s]

 67%|██████▋   | 400/600 [00:19<00:07, 27.18it/s]

 67%|██████▋   | 403/600 [00:19<00:07, 26.55it/s]

 68%|██████▊   | 406/600 [00:19<00:07, 27.28it/s]

 68%|██████▊   | 409/600 [00:19<00:07, 26.62it/s]

 69%|██████▊   | 412/600 [00:19<00:07, 26.39it/s]

 69%|██████▉   | 415/600 [00:20<00:07, 26.15it/s]

 70%|██████▉   | 418/600 [00:20<00:06, 26.69it/s]

 70%|███████   | 421/600 [00:20<00:07, 25.10it/s]

 71%|███████   | 424/600 [00:20<00:06, 25.99it/s]

 71%|███████   | 427/600 [00:20<00:06, 26.02it/s]

 72%|███████▏  | 430/600 [00:20<00:06, 25.06it/s]

 72%|███████▏  | 433/600 [00:20<00:07, 23.46it/s]

 73%|███████▎  | 436/600 [00:20<00:07, 22.86it/s]

 73%|███████▎  | 439/600 [00:21<00:07, 22.26it/s]

 74%|███████▎  | 442/600 [00:21<00:06, 23.02it/s]

 74%|███████▍  | 445/600 [00:21<00:06, 24.20it/s]

 75%|███████▍  | 448/600 [00:21<00:05, 25.37it/s]

 75%|███████▌  | 451/600 [00:21<00:05, 25.13it/s]

 76%|███████▌  | 454/600 [00:21<00:06, 23.28it/s]

 76%|███████▌  | 457/600 [00:21<00:05, 23.89it/s]

 77%|███████▋  | 460/600 [00:21<00:05, 23.69it/s]

 77%|███████▋  | 463/600 [00:22<00:06, 22.50it/s]

 78%|███████▊  | 466/600 [00:22<00:05, 22.42it/s]

 78%|███████▊  | 469/600 [00:22<00:05, 22.21it/s]

 79%|███████▊  | 472/600 [00:22<00:05, 21.36it/s]

 79%|███████▉  | 475/600 [00:22<00:06, 19.70it/s]

 80%|███████▉  | 478/600 [00:22<00:06, 19.98it/s]

 80%|████████  | 481/600 [00:22<00:05, 20.27it/s]

 81%|████████  | 484/600 [00:23<00:05, 20.61it/s]

 81%|████████  | 487/600 [00:23<00:05, 20.73it/s]

 82%|████████▏ | 490/600 [00:23<00:05, 20.40it/s]

 82%|████████▏ | 493/600 [00:23<00:05, 20.87it/s]

 83%|████████▎ | 496/600 [00:23<00:04, 20.94it/s]

 83%|████████▎ | 499/600 [00:23<00:04, 21.45it/s]

 84%|████████▎ | 502/600 [00:23<00:04, 22.50it/s]

 84%|████████▍ | 505/600 [00:24<00:04, 22.07it/s]

 85%|████████▍ | 508/600 [00:24<00:04, 22.88it/s]

 85%|████████▌ | 511/600 [00:24<00:04, 22.12it/s]

 86%|████████▌ | 514/600 [00:24<00:03, 21.58it/s]

 86%|████████▌ | 517/600 [00:24<00:03, 21.96it/s]

 87%|████████▋ | 520/600 [00:24<00:03, 21.70it/s]

 87%|████████▋ | 523/600 [00:24<00:03, 22.50it/s]

 88%|████████▊ | 526/600 [00:24<00:03, 22.54it/s]

 88%|████████▊ | 529/600 [00:25<00:03, 23.33it/s]

 89%|████████▊ | 532/600 [00:25<00:02, 23.20it/s]

 89%|████████▉ | 535/600 [00:25<00:02, 24.29it/s]

 90%|████████▉ | 538/600 [00:25<00:02, 24.99it/s]

 90%|█████████ | 541/600 [00:25<00:02, 24.62it/s]

 91%|█████████ | 544/600 [00:25<00:02, 24.02it/s]

 91%|█████████ | 547/600 [00:25<00:02, 24.67it/s]

 92%|█████████▏| 550/600 [00:25<00:02, 24.64it/s]

 92%|█████████▏| 553/600 [00:26<00:01, 24.75it/s]

 93%|█████████▎| 556/600 [00:26<00:01, 24.95it/s]

 93%|█████████▎| 559/600 [00:26<00:01, 25.67it/s]

 94%|█████████▎| 562/600 [00:26<00:01, 26.06it/s]

 94%|█████████▍| 565/600 [00:26<00:01, 24.72it/s]

 95%|█████████▍| 568/600 [00:26<00:01, 25.56it/s]

 95%|█████████▌| 571/600 [00:26<00:01, 26.47it/s]

 96%|█████████▌| 574/600 [00:26<00:00, 26.92it/s]

 96%|█████████▌| 577/600 [00:26<00:00, 27.02it/s]

 97%|█████████▋| 580/600 [00:27<00:00, 26.88it/s]

 97%|█████████▋| 583/600 [00:27<00:00, 27.29it/s]

 98%|█████████▊| 586/600 [00:27<00:00, 27.29it/s]

 98%|█████████▊| 589/600 [00:27<00:00, 27.51it/s]

 99%|█████████▊| 592/600 [00:27<00:00, 27.74it/s]

 99%|█████████▉| 595/600 [00:27<00:00, 27.08it/s]

100%|█████████▉| 598/600 [00:27<00:00, 24.84it/s]

100%|██████████| 600/600 [00:27<00:00, 21.54it/s]

Processing camera: MOT17-04-FRCNN, frames: 1050

  0%|          | 0/1050 [00:00<?, ?it/s]

  0%|          | 3/1050 [00:00<00:39, 26.55it/s]

  1%|          | 6/1050 [00:00<00:39, 26.14it/s]

  1%|          | 9/1050 [00:00<00:40, 25.91it/s]

  1%|          | 12/1050 [00:00<00:40, 25.63it/s]

  1%|▏         | 15/1050 [00:00<00:39, 25.95it/s]

  2%|▏         | 18/1050 [00:00<00:41, 24.83it/s]

  2%|▏         | 21/1050 [00:00<00:42, 24.49it/s]

  2%|▏         | 24/1050 [00:00<00:42, 24.20it/s]

  3%|▎         | 27/1050 [00:01<00:41, 24.57it/s]

  3%|▎         | 30/1050 [00:01<00:42, 24.21it/s]

  3%|▎         | 33/1050 [00:01<00:42, 24.21it/s]

  3%|▎         | 36/1050 [00:01<00:42, 24.08it/s]

  4%|▎         | 39/1050 [00:01<00:40, 24.78it/s]

  4%|▍         | 42/1050 [00:01<00:40, 24.78it/s]

  4%|▍         | 45/1050 [00:01<00:43, 23.33it/s]

  5%|▍         | 48/1050 [00:01<00:45, 22.17it/s]

  5%|▍         | 51/1050 [00:02<00:42, 23.49it/s]

  5%|▌         | 54/1050 [00:02<00:41, 23.98it/s]

  5%|▌         | 57/1050 [00:02<00:40, 24.28it/s]

  6%|▌         | 60/1050 [00:02<00:40, 24.31it/s]

  6%|▌         | 63/1050 [00:02<00:40, 24.57it/s]

  6%|▋         | 66/1050 [00:02<00:39, 24.82it/s]

  7%|▋         | 69/1050 [00:02<00:40, 24.33it/s]

  7%|▋         | 72/1050 [00:02<00:39, 24.71it/s]

  7%|▋         | 75/1050 [00:03<00:39, 24.86it/s]

  7%|▋         | 78/1050 [00:03<00:39, 24.65it/s]

  8%|▊         | 81/1050 [00:03<00:39, 24.76it/s]

  8%|▊         | 84/1050 [00:03<00:38, 24.95it/s]

  8%|▊         | 87/1050 [00:03<00:38, 25.03it/s]

  9%|▊         | 90/1050 [00:03<00:38, 24.71it/s]

  9%|▉         | 93/1050 [00:03<00:38, 24.86it/s]

  9%|▉         | 96/1050 [00:03<00:41, 22.85it/s]

  9%|▉         | 99/1050 [00:04<00:40, 23.62it/s]

 10%|▉         | 102/1050 [00:04<00:44, 21.35it/s]

 10%|█         | 105/1050 [00:04<00:46, 20.25it/s]

 10%|█         | 108/1050 [00:04<00:44, 21.20it/s]

 11%|█         | 111/1050 [00:04<00:41, 22.46it/s]

 11%|█         | 114/1050 [00:04<00:40, 23.22it/s]

 11%|█         | 117/1050 [00:04<00:39, 23.84it/s]

 11%|█▏        | 120/1050 [00:04<00:37, 24.72it/s]

 12%|█▏        | 123/1050 [00:05<00:37, 24.44it/s]

 12%|█▏        | 126/1050 [00:05<00:37, 24.91it/s]

 12%|█▏        | 129/1050 [00:05<00:36, 25.12it/s]

 13%|█▎        | 132/1050 [00:05<00:36, 25.21it/s]

 13%|█▎        | 135/1050 [00:05<00:35, 25.93it/s]

 13%|█▎        | 138/1050 [00:05<00:34, 26.18it/s]

 13%|█▎        | 141/1050 [00:05<00:35, 25.49it/s]

 14%|█▎        | 144/1050 [00:05<00:36, 24.84it/s]

 14%|█▍        | 147/1050 [00:06<00:35, 25.45it/s]

 14%|█▍        | 150/1050 [00:06<00:35, 25.51it/s]

 15%|█▍        | 153/1050 [00:06<00:37, 24.02it/s]

 15%|█▍        | 156/1050 [00:06<00:36, 24.27it/s]

 15%|█▌        | 159/1050 [00:06<00:37, 24.07it/s]

 15%|█▌        | 162/1050 [00:06<00:39, 22.64it/s]

 16%|█▌        | 165/1050 [00:06<00:40, 21.97it/s]

 16%|█▌        | 168/1050 [00:06<00:40, 21.99it/s]

 16%|█▋        | 171/1050 [00:07<00:37, 23.16it/s]

 17%|█▋        | 174/1050 [00:07<00:38, 22.66it/s]

 17%|█▋        | 177/1050 [00:07<00:40, 21.75it/s]

 17%|█▋        | 180/1050 [00:07<00:40, 21.28it/s]

 17%|█▋        | 183/1050 [00:07<00:41, 21.01it/s]

 18%|█▊        | 186/1050 [00:07<00:42, 20.28it/s]

 18%|█▊        | 189/1050 [00:07<00:42, 20.23it/s]

 18%|█▊        | 192/1050 [00:08<00:43, 19.57it/s]

 18%|█▊        | 194/1050 [00:08<00:45, 18.92it/s]

 19%|█▉        | 197/1050 [00:08<00:44, 19.38it/s]

 19%|█▉        | 200/1050 [00:08<00:43, 19.73it/s]

 19%|█▉        | 202/1050 [00:08<00:43, 19.61it/s]

 20%|█▉        | 205/1050 [00:08<00:42, 20.05it/s]

 20%|█▉        | 207/1050 [00:08<00:42, 19.89it/s]

 20%|██        | 210/1050 [00:09<00:41, 20.25it/s]

 20%|██        | 213/1050 [00:09<00:42, 19.82it/s]

 21%|██        | 216/1050 [00:09<00:41, 20.26it/s]

 21%|██        | 219/1050 [00:09<00:39, 20.83it/s]

 21%|██        | 222/1050 [00:09<00:39, 21.20it/s]

 21%|██▏       | 225/1050 [00:09<00:37, 21.88it/s]

 22%|██▏       | 228/1050 [00:09<00:36, 22.23it/s]

 22%|██▏       | 231/1050 [00:10<00:37, 21.74it/s]

 22%|██▏       | 234/1050 [00:10<00:38, 21.14it/s]

 23%|██▎       | 237/1050 [00:10<00:37, 21.50it/s]

 23%|██▎       | 240/1050 [00:10<00:37, 21.71it/s]

 23%|██▎       | 243/1050 [00:10<00:36, 22.01it/s]

 23%|██▎       | 246/1050 [00:10<00:36, 21.78it/s]

 24%|██▎       | 249/1050 [00:10<00:38, 20.77it/s]

 24%|██▍       | 252/1050 [00:11<00:39, 20.37it/s]

 24%|██▍       | 255/1050 [00:11<00:40, 19.81it/s]

 24%|██▍       | 257/1050 [00:11<00:39, 19.86it/s]

 25%|██▍       | 260/1050 [00:11<00:40, 19.69it/s]

 25%|██▌       | 263/1050 [00:11<00:39, 19.83it/s]

 25%|██▌       | 266/1050 [00:11<00:39, 19.84it/s]

 26%|██▌       | 269/1050 [00:11<00:39, 19.93it/s]

 26%|██▌       | 271/1050 [00:12<00:39, 19.68it/s]

 26%|██▌       | 274/1050 [00:12<00:37, 20.70it/s]

 26%|██▋       | 277/1050 [00:12<00:37, 20.69it/s]

 27%|██▋       | 280/1050 [00:12<00:37, 20.69it/s]

 27%|██▋       | 283/1050 [00:12<00:37, 20.56it/s]

 27%|██▋       | 286/1050 [00:12<00:37, 20.60it/s]

 28%|██▊       | 289/1050 [00:12<00:36, 20.67it/s]

 28%|██▊       | 292/1050 [00:13<00:36, 20.72it/s]

 28%|██▊       | 295/1050 [00:13<00:35, 20.97it/s]

 28%|██▊       | 298/1050 [00:13<00:34, 21.61it/s]

 29%|██▊       | 301/1050 [00:13<00:34, 21.84it/s]

 29%|██▉       | 304/1050 [00:13<00:32, 23.07it/s]

 29%|██▉       | 307/1050 [00:13<00:32, 23.07it/s]

 30%|██▉       | 310/1050 [00:13<00:33, 22.15it/s]

 30%|██▉       | 313/1050 [00:13<00:33, 21.83it/s]

 30%|███       | 316/1050 [00:14<00:34, 20.98it/s]

 30%|███       | 319/1050 [00:14<00:35, 20.51it/s]

 31%|███       | 322/1050 [00:14<00:34, 21.22it/s]

 31%|███       | 325/1050 [00:14<00:32, 22.13it/s]

 31%|███       | 328/1050 [00:14<00:32, 22.35it/s]

 32%|███▏      | 331/1050 [00:14<00:32, 22.02it/s]

 32%|███▏      | 334/1050 [00:14<00:32, 21.74it/s]

 32%|███▏      | 337/1050 [00:15<00:33, 21.51it/s]

 32%|███▏      | 340/1050 [00:15<00:31, 22.50it/s]

 33%|███▎      | 343/1050 [00:15<00:30, 23.04it/s]

 33%|███▎      | 346/1050 [00:15<00:30, 23.32it/s]

 33%|███▎      | 349/1050 [00:15<00:30, 23.24it/s]

 34%|███▎      | 352/1050 [00:15<00:31, 22.26it/s]

 34%|███▍      | 355/1050 [00:15<00:33, 20.86it/s]

 34%|███▍      | 358/1050 [00:16<00:34, 20.10it/s]

 34%|███▍      | 361/1050 [00:16<00:33, 20.27it/s]

 35%|███▍      | 364/1050 [00:16<00:34, 19.91it/s]

 35%|███▍      | 367/1050 [00:16<00:34, 19.98it/s]

 35%|███▌      | 370/1050 [00:16<00:34, 19.48it/s]

 36%|███▌      | 373/1050 [00:16<00:34, 19.79it/s]

 36%|███▌      | 375/1050 [00:16<00:34, 19.49it/s]

 36%|███▌      | 378/1050 [00:17<00:33, 19.82it/s]

 36%|███▋      | 381/1050 [00:17<00:32, 20.54it/s]

 37%|███▋      | 384/1050 [00:17<00:32, 20.28it/s]

 37%|███▋      | 387/1050 [00:17<00:33, 20.03it/s]

 37%|███▋      | 390/1050 [00:17<00:32, 20.19it/s]

 37%|███▋      | 393/1050 [00:17<00:31, 20.55it/s]

 38%|███▊      | 396/1050 [00:17<00:31, 20.98it/s]

 38%|███▊      | 399/1050 [00:18<00:31, 20.68it/s]

 38%|███▊      | 402/1050 [00:18<00:30, 21.44it/s]

 39%|███▊      | 405/1050 [00:18<00:30, 20.81it/s]

 39%|███▉      | 408/1050 [00:18<00:28, 22.21it/s]

 39%|███▉      | 411/1050 [00:18<00:29, 21.87it/s]

 39%|███▉      | 414/1050 [00:18<00:28, 22.02it/s]

 40%|███▉      | 417/1050 [00:18<00:28, 22.28it/s]

 40%|████      | 420/1050 [00:18<00:27, 22.82it/s]

 40%|████      | 423/1050 [00:19<00:27, 22.74it/s]

 41%|████      | 426/1050 [00:19<00:28, 22.28it/s]

 41%|████      | 429/1050 [00:19<00:28, 21.45it/s]

 41%|████      | 432/1050 [00:19<00:29, 20.73it/s]

 41%|████▏     | 435/1050 [00:19<00:29, 20.51it/s]

 42%|████▏     | 438/1050 [00:19<00:29, 20.95it/s]

 42%|████▏     | 441/1050 [00:20<00:29, 20.87it/s]

 42%|████▏     | 444/1050 [00:20<00:29, 20.86it/s]

 43%|████▎     | 447/1050 [00:20<00:28, 20.98it/s]

 43%|████▎     | 450/1050 [00:20<00:29, 20.64it/s]

 43%|████▎     | 453/1050 [00:20<00:28, 20.78it/s]

 43%|████▎     | 456/1050 [00:20<00:27, 21.24it/s]

 44%|████▎     | 459/1050 [00:20<00:26, 22.24it/s]

 44%|████▍     | 462/1050 [00:20<00:25, 22.79it/s]

 44%|████▍     | 465/1050 [00:21<00:26, 22.32it/s]

 45%|████▍     | 468/1050 [00:21<00:26, 21.95it/s]

 45%|████▍     | 471/1050 [00:21<00:27, 21.14it/s]

 45%|████▌     | 474/1050 [00:21<00:26, 21.78it/s]

 45%|████▌     | 477/1050 [00:21<00:25, 22.56it/s]

 46%|████▌     | 480/1050 [00:21<00:24, 23.24it/s]

 46%|████▌     | 483/1050 [00:21<00:23, 23.85it/s]

 46%|████▋     | 486/1050 [00:22<00:24, 22.96it/s]

 47%|████▋     | 489/1050 [00:22<00:24, 23.24it/s]

 47%|████▋     | 492/1050 [00:22<00:23, 23.46it/s]

 47%|████▋     | 495/1050 [00:22<00:24, 22.81it/s]

 47%|████▋     | 498/1050 [00:22<00:24, 22.79it/s]

 48%|████▊     | 501/1050 [00:22<00:24, 22.31it/s]

 48%|████▊     | 504/1050 [00:22<00:23, 22.90it/s]

 48%|████▊     | 507/1050 [00:22<00:22, 23.66it/s]

 49%|████▊     | 510/1050 [00:23<00:22, 23.70it/s]

 49%|████▉     | 513/1050 [00:23<00:22, 24.19it/s]

 49%|████▉     | 516/1050 [00:23<00:21, 24.55it/s]

 49%|████▉     | 519/1050 [00:23<00:21, 24.50it/s]

 50%|████▉     | 522/1050 [00:23<00:21, 24.59it/s]

 50%|█████     | 525/1050 [00:23<00:21, 24.06it/s]

 50%|█████     | 528/1050 [00:23<00:21, 24.57it/s]

 51%|█████     | 531/1050 [00:23<00:20, 24.76it/s]

 51%|█████     | 534/1050 [00:24<00:20, 24.65it/s]

 51%|█████     | 537/1050 [00:24<00:20, 24.88it/s]

 51%|█████▏    | 540/1050 [00:24<00:20, 24.91it/s]

 52%|█████▏    | 543/1050 [00:24<00:20, 25.00it/s]

 52%|█████▏    | 546/1050 [00:24<00:20, 24.51it/s]

 52%|█████▏    | 549/1050 [00:24<00:21, 23.22it/s]

 53%|█████▎    | 552/1050 [00:24<00:20, 23.84it/s]

 53%|█████▎    | 555/1050 [00:24<00:20, 24.24it/s]

 53%|█████▎    | 558/1050 [00:25<00:20, 24.14it/s]

 53%|█████▎    | 561/1050 [00:25<00:20, 23.64it/s]

 54%|█████▎    | 564/1050 [00:25<00:22, 21.27it/s]

 54%|█████▍    | 567/1050 [00:25<00:24, 20.12it/s]

 54%|█████▍    | 570/1050 [00:25<00:24, 19.92it/s]

 55%|█████▍    | 573/1050 [00:25<00:23, 20.03it/s]

 55%|█████▍    | 576/1050 [00:25<00:24, 19.66it/s]

 55%|█████▌    | 579/1050 [00:26<00:23, 19.65it/s]

 55%|█████▌    | 581/1050 [00:26<00:24, 19.34it/s]

 56%|█████▌    | 583/1050 [00:26<00:24, 19.27it/s]

 56%|█████▌    | 585/1050 [00:26<00:24, 19.12it/s]

 56%|█████▌    | 587/1050 [00:26<00:24, 18.62it/s]

 56%|█████▌    | 589/1050 [00:26<00:24, 18.55it/s]

 56%|█████▋    | 591/1050 [00:26<00:24, 18.94it/s]

 56%|█████▋    | 593/1050 [00:26<00:23, 19.13it/s]

 57%|█████▋    | 596/1050 [00:26<00:22, 19.99it/s]

 57%|█████▋    | 599/1050 [00:27<00:22, 20.11it/s]

 57%|█████▋    | 602/1050 [00:27<00:22, 20.35it/s]

 58%|█████▊    | 605/1050 [00:27<00:21, 20.92it/s]

 58%|█████▊    | 608/1050 [00:27<00:21, 20.53it/s]

 58%|█████▊    | 611/1050 [00:27<00:21, 20.80it/s]

 58%|█████▊    | 614/1050 [00:27<00:20, 21.27it/s]

 59%|█████▉    | 617/1050 [00:27<00:20, 21.27it/s]

 59%|█████▉    | 620/1050 [00:28<00:19, 22.03it/s]

 59%|█████▉    | 623/1050 [00:28<00:18, 22.59it/s]

 60%|█████▉    | 626/1050 [00:28<00:18, 23.00it/s]

 60%|█████▉    | 629/1050 [00:28<00:17, 23.51it/s]

 60%|██████    | 632/1050 [00:28<00:17, 24.00it/s]

 60%|██████    | 635/1050 [00:28<00:17, 23.83it/s]

 61%|██████    | 638/1050 [00:28<00:17, 23.00it/s]

 61%|██████    | 641/1050 [00:29<00:17, 22.81it/s]

 61%|██████▏   | 644/1050 [00:29<00:18, 21.79it/s]

 62%|██████▏   | 647/1050 [00:29<00:18, 21.59it/s]

 62%|██████▏   | 650/1050 [00:29<00:18, 22.06it/s]

 62%|██████▏   | 653/1050 [00:29<00:18, 21.17it/s]

 62%|██████▏   | 656/1050 [00:29<00:19, 20.59it/s]

 63%|██████▎   | 659/1050 [00:29<00:19, 19.69it/s]

 63%|██████▎   | 661/1050 [00:30<00:20, 19.21it/s]

 63%|██████▎   | 663/1050 [00:30<00:20, 18.53it/s]

 63%|██████▎   | 665/1050 [00:30<00:23, 16.56it/s]

 64%|██████▎   | 667/1050 [00:30<00:22, 16.89it/s]

 64%|██████▎   | 669/1050 [00:30<00:22, 17.31it/s]

 64%|██████▍   | 671/1050 [00:30<00:21, 17.51it/s]

 64%|██████▍   | 673/1050 [00:30<00:21, 17.88it/s]

 64%|██████▍   | 675/1050 [00:30<00:20, 17.97it/s]

 64%|██████▍   | 677/1050 [00:30<00:20, 17.89it/s]

 65%|██████▍   | 679/1050 [00:31<00:20, 17.88it/s]

 65%|██████▍   | 681/1050 [00:31<00:20, 18.26it/s]

 65%|██████▌   | 684/1050 [00:31<00:18, 19.77it/s]

 65%|██████▌   | 687/1050 [00:31<00:17, 20.43it/s]

 66%|██████▌   | 690/1050 [00:31<00:17, 20.95it/s]

 66%|██████▌   | 693/1050 [00:31<00:17, 19.96it/s]

 66%|██████▋   | 696/1050 [00:31<00:17, 19.93it/s]

 66%|██████▋   | 698/1050 [00:32<00:17, 19.72it/s]

 67%|██████▋   | 700/1050 [00:32<00:17, 19.67it/s]

 67%|██████▋   | 702/1050 [00:32<00:17, 19.70it/s]

 67%|██████▋   | 705/1050 [00:32<00:15, 21.72it/s]

 67%|██████▋   | 708/1050 [00:32<00:15, 22.11it/s]

 68%|██████▊   | 711/1050 [00:32<00:15, 21.37it/s]

 68%|██████▊   | 714/1050 [00:32<00:16, 20.82it/s]

 68%|██████▊   | 717/1050 [00:32<00:16, 20.47it/s]

 69%|██████▊   | 720/1050 [00:33<00:16, 19.63it/s]

 69%|██████▉   | 722/1050 [00:33<00:17, 19.24it/s]

 69%|██████▉   | 724/1050 [00:33<00:17, 19.14it/s]

 69%|██████▉   | 726/1050 [00:33<00:16, 19.17it/s]

 69%|██████▉   | 728/1050 [00:33<00:16, 19.09it/s]

 70%|██████▉   | 730/1050 [00:33<00:16, 18.92it/s]

 70%|██████▉   | 732/1050 [00:33<00:17, 18.56it/s]

 70%|███████   | 735/1050 [00:33<00:16, 19.36it/s]

 70%|███████   | 737/1050 [00:34<00:17, 17.69it/s]

 70%|███████   | 739/1050 [00:34<00:17, 18.23it/s]

 71%|███████   | 741/1050 [00:34<00:16, 18.64it/s]

 71%|███████   | 743/1050 [00:34<00:16, 19.01it/s]

 71%|███████   | 745/1050 [00:34<00:16, 19.02it/s]

 71%|███████   | 747/1050 [00:34<00:16, 18.67it/s]

 71%|███████▏  | 749/1050 [00:34<00:16, 18.47it/s]

 72%|███████▏  | 751/1050 [00:34<00:16, 18.23it/s]

 72%|███████▏  | 753/1050 [00:34<00:16, 17.97it/s]

 72%|███████▏  | 755/1050 [00:34<00:16, 17.99it/s]

 72%|███████▏  | 757/1050 [00:35<00:15, 18.34it/s]

 72%|███████▏  | 760/1050 [00:35<00:15, 19.19it/s]

 73%|███████▎  | 762/1050 [00:35<00:14, 19.35it/s]

 73%|███████▎  | 765/1050 [00:35<00:14, 19.82it/s]

 73%|███████▎  | 768/1050 [00:35<00:14, 19.98it/s]

 73%|███████▎  | 770/1050 [00:35<00:14, 19.79it/s]

 74%|███████▎  | 772/1050 [00:35<00:14, 19.79it/s]

 74%|███████▎  | 774/1050 [00:35<00:14, 19.69it/s]

 74%|███████▍  | 777/1050 [00:36<00:12, 21.19it/s]

 74%|███████▍  | 780/1050 [00:36<00:12, 22.02it/s]

 75%|███████▍  | 783/1050 [00:36<00:12, 21.62it/s]

 75%|███████▍  | 786/1050 [00:36<00:12, 21.46it/s]

 75%|███████▌  | 789/1050 [00:36<00:12, 20.62it/s]

 75%|███████▌  | 792/1050 [00:36<00:12, 20.46it/s]

 76%|███████▌  | 795/1050 [00:36<00:12, 20.24it/s]

 76%|███████▌  | 798/1050 [00:37<00:12, 20.33it/s]

 76%|███████▋  | 801/1050 [00:37<00:12, 19.96it/s]

 77%|███████▋  | 804/1050 [00:37<00:12, 20.01it/s]

 77%|███████▋  | 807/1050 [00:37<00:11, 20.34it/s]

 77%|███████▋  | 810/1050 [00:37<00:12, 19.87it/s]

 77%|███████▋  | 813/1050 [00:37<00:11, 20.11it/s]

 78%|███████▊  | 816/1050 [00:37<00:11, 20.04it/s]

 78%|███████▊  | 819/1050 [00:38<00:11, 20.99it/s]

 78%|███████▊  | 822/1050 [00:38<00:10, 21.08it/s]

 79%|███████▊  | 825/1050 [00:38<00:10, 21.50it/s]

 79%|███████▉  | 828/1050 [00:38<00:09, 22.49it/s]

 79%|███████▉  | 831/1050 [00:38<00:09, 23.41it/s]

 79%|███████▉  | 834/1050 [00:38<00:09, 23.58it/s]

 80%|███████▉  | 837/1050 [00:38<00:09, 23.54it/s]

 80%|████████  | 840/1050 [00:38<00:08, 24.31it/s]

 80%|████████  | 843/1050 [00:39<00:08, 24.04it/s]

 81%|████████  | 846/1050 [00:39<00:08, 24.56it/s]

 81%|████████  | 849/1050 [00:39<00:08, 24.63it/s]

 81%|████████  | 852/1050 [00:39<00:08, 24.38it/s]

 81%|████████▏ | 855/1050 [00:39<00:07, 24.99it/s]

 82%|████████▏ | 858/1050 [00:39<00:07, 25.06it/s]

 82%|████████▏ | 861/1050 [00:39<00:07, 24.37it/s]

 82%|████████▏ | 864/1050 [00:39<00:08, 22.77it/s]

 83%|████████▎ | 867/1050 [00:40<00:08, 21.67it/s]

 83%|████████▎ | 870/1050 [00:40<00:08, 22.07it/s]

 83%|████████▎ | 873/1050 [00:40<00:07, 22.82it/s]

 83%|████████▎ | 876/1050 [00:40<00:07, 23.38it/s]

 84%|████████▎ | 879/1050 [00:40<00:07, 23.29it/s]

 84%|████████▍ | 882/1050 [00:40<00:07, 23.44it/s]

 84%|████████▍ | 885/1050 [00:40<00:06, 24.00it/s]

 85%|████████▍ | 888/1050 [00:40<00:06, 24.41it/s]

 85%|████████▍ | 891/1050 [00:41<00:06, 24.77it/s]

 85%|████████▌ | 894/1050 [00:41<00:06, 24.53it/s]

 85%|████████▌ | 897/1050 [00:41<00:06, 24.92it/s]

 86%|████████▌ | 900/1050 [00:41<00:05, 25.13it/s]

 86%|████████▌ | 903/1050 [00:41<00:06, 23.89it/s]

 86%|████████▋ | 906/1050 [00:41<00:05, 24.45it/s]

 87%|████████▋ | 909/1050 [00:41<00:05, 24.14it/s]

 87%|████████▋ | 912/1050 [00:41<00:05, 24.69it/s]

 87%|████████▋ | 915/1050 [00:42<00:05, 22.60it/s]

 87%|████████▋ | 918/1050 [00:42<00:05, 23.60it/s]

 88%|████████▊ | 921/1050 [00:42<00:05, 24.12it/s]

 88%|████████▊ | 924/1050 [00:42<00:05, 24.49it/s]

 88%|████████▊ | 927/1050 [00:42<00:04, 24.70it/s]

 89%|████████▊ | 930/1050 [00:42<00:04, 24.37it/s]

 89%|████████▉ | 933/1050 [00:42<00:04, 24.68it/s]

 89%|████████▉ | 936/1050 [00:42<00:04, 24.96it/s]

 89%|████████▉ | 939/1050 [00:43<00:04, 25.16it/s]

 90%|████████▉ | 942/1050 [00:43<00:04, 25.24it/s]

 90%|█████████ | 945/1050 [00:43<00:04, 25.10it/s]

 90%|█████████ | 948/1050 [00:43<00:04, 25.33it/s]

 91%|█████████ | 951/1050 [00:43<00:03, 25.48it/s]

 91%|█████████ | 954/1050 [00:43<00:03, 25.40it/s]

 91%|█████████ | 957/1050 [00:43<00:03, 25.47it/s]

 91%|█████████▏| 960/1050 [00:43<00:03, 25.46it/s]

 92%|█████████▏| 963/1050 [00:44<00:03, 25.26it/s]

 92%|█████████▏| 966/1050 [00:44<00:03, 24.68it/s]

 92%|█████████▏| 969/1050 [00:44<00:03, 23.12it/s]

 93%|█████████▎| 972/1050 [00:44<00:03, 23.10it/s]

 93%|█████████▎| 975/1050 [00:44<00:03, 22.42it/s]

 93%|█████████▎| 978/1050 [00:44<00:03, 22.41it/s]

 93%|█████████▎| 981/1050 [00:44<00:03, 21.58it/s]

 94%|█████████▎| 984/1050 [00:45<00:03, 20.78it/s]

 94%|█████████▍| 987/1050 [00:45<00:02, 21.01it/s]

 94%|█████████▍| 990/1050 [00:45<00:02, 21.59it/s]

 95%|█████████▍| 993/1050 [00:45<00:02, 21.97it/s]

 95%|█████████▍| 996/1050 [00:45<00:02, 23.06it/s]

 95%|█████████▌| 999/1050 [00:45<00:02, 23.33it/s]

 95%|█████████▌| 1002/1050 [00:45<00:02, 23.75it/s]

 96%|█████████▌| 1005/1050 [00:45<00:01, 23.33it/s]

 96%|█████████▌| 1008/1050 [00:46<00:01, 24.03it/s]

 96%|█████████▋| 1011/1050 [00:46<00:01, 23.52it/s]

 97%|█████████▋| 1014/1050 [00:46<00:01, 23.71it/s]

 97%|█████████▋| 1017/1050 [00:46<00:01, 24.44it/s]

 97%|█████████▋| 1020/1050 [00:46<00:01, 24.60it/s]

 97%|█████████▋| 1023/1050 [00:46<00:01, 24.54it/s]

 98%|█████████▊| 1026/1050 [00:46<00:00, 24.26it/s]

 98%|█████████▊| 1029/1050 [00:46<00:00, 23.83it/s]

 98%|█████████▊| 1032/1050 [00:47<00:00, 24.11it/s]

 99%|█████████▊| 1035/1050 [00:47<00:00, 23.93it/s]

 99%|█████████▉| 1038/1050 [00:47<00:00, 23.95it/s]

 99%|█████████▉| 1041/1050 [00:47<00:00, 24.50it/s]

 99%|█████████▉| 1044/1050 [00:47<00:00, 23.22it/s]

100%|█████████▉| 1047/1050 [00:47<00:00, 22.75it/s]

100%|██████████| 1050/1050 [00:47<00:00, 22.80it/s]

100%|██████████| 1050/1050 [00:47<00:00, 21.97it/s]

Processing camera: MOT17-05-FRCNN, frames: 837

  0%|          | 0/837 [00:00<?, ?it/s]

  0%|          | 3/837 [00:00<00:40, 20.83it/s]

  1%|          | 6/837 [00:00<00:42, 19.56it/s]

  1%|          | 8/837 [00:00<00:42, 19.51it/s]

  1%|          | 10/837 [00:00<00:44, 18.79it/s]

  2%|▏         | 13/837 [00:00<00:42, 19.33it/s]

  2%|▏         | 15/837 [00:00<00:42, 19.47it/s]

  2%|▏         | 18/837 [00:00<00:39, 20.70it/s]

  3%|▎         | 21/837 [00:01<00:37, 21.59it/s]

  3%|▎         | 24/837 [00:01<00:36, 22.17it/s]

  3%|▎         | 27/837 [00:01<00:37, 21.62it/s]

  4%|▎         | 30/837 [00:01<00:37, 21.51it/s]

  4%|▍         | 33/837 [00:01<00:36, 21.97it/s]

  4%|▍         | 36/837 [00:01<00:33, 23.60it/s]

  5%|▍         | 39/837 [00:01<00:32, 24.86it/s]

  5%|▌         | 42/837 [00:01<00:31, 25.22it/s]

  5%|▌         | 45/837 [00:02<00:30, 25.94it/s]

  6%|▌         | 48/837 [00:02<00:30, 25.65it/s]

  6%|▌         | 51/837 [00:02<00:30, 25.65it/s]

  6%|▋         | 54/837 [00:02<00:30, 25.91it/s]

  7%|▋         | 57/837 [00:02<00:31, 24.86it/s]

  7%|▋         | 60/837 [00:02<00:30, 25.09it/s]

  8%|▊         | 63/837 [00:02<00:31, 24.88it/s]

  8%|▊         | 66/837 [00:02<00:29, 26.08it/s]

  8%|▊         | 69/837 [00:02<00:28, 26.93it/s]

  9%|▊         | 72/837 [00:03<00:27, 27.40it/s]

  9%|▉         | 75/837 [00:03<00:28, 26.78it/s]

  9%|▉         | 78/837 [00:03<00:28, 26.50it/s]

 10%|▉         | 81/837 [00:03<00:28, 26.94it/s]

 10%|█         | 84/837 [00:03<00:28, 26.05it/s]

 10%|█         | 87/837 [00:03<00:29, 25.86it/s]

 11%|█         | 90/837 [00:03<00:28, 26.55it/s]

 11%|█         | 93/837 [00:03<00:27, 27.05it/s]

 11%|█▏        | 96/837 [00:03<00:27, 27.34it/s]

 12%|█▏        | 99/837 [00:04<00:27, 27.32it/s]

 12%|█▏        | 102/837 [00:04<00:26, 27.38it/s]

 13%|█▎        | 105/837 [00:04<00:27, 26.41it/s]

 13%|█▎        | 108/837 [00:04<00:27, 26.77it/s]

 13%|█▎        | 111/837 [00:04<00:27, 26.35it/s]

 14%|█▎        | 114/837 [00:04<00:29, 24.84it/s]

 14%|█▍        | 117/837 [00:04<00:28, 25.01it/s]

 14%|█▍        | 120/837 [00:04<00:29, 24.58it/s]

 15%|█▍        | 123/837 [00:05<00:29, 24.16it/s]

 15%|█▌        | 126/837 [00:05<00:29, 24.41it/s]

 15%|█▌        | 129/837 [00:05<00:29, 24.40it/s]

 16%|█▌        | 132/837 [00:05<00:29, 24.05it/s]

 16%|█▌        | 135/837 [00:05<00:28, 24.50it/s]

 16%|█▋        | 138/837 [00:05<00:28, 24.71it/s]

 17%|█▋        | 141/837 [00:05<00:27, 25.69it/s]

 17%|█▋        | 144/837 [00:05<00:27, 25.48it/s]

 18%|█▊        | 147/837 [00:05<00:26, 26.26it/s]

 18%|█▊        | 150/837 [00:06<00:25, 26.63it/s]

 18%|█▊        | 153/837 [00:06<00:25, 27.11it/s]

 19%|█▊        | 156/837 [00:06<00:25, 26.30it/s]

 19%|█▉        | 159/837 [00:06<00:25, 26.80it/s]

 19%|█▉        | 162/837 [00:06<00:24, 27.16it/s]

 20%|█▉        | 165/837 [00:06<00:24, 27.19it/s]

 20%|██        | 168/837 [00:06<00:25, 26.64it/s]

 20%|██        | 171/837 [00:06<00:24, 26.97it/s]

 21%|██        | 174/837 [00:06<00:24, 27.43it/s]

 21%|██        | 177/837 [00:07<00:25, 26.23it/s]

 22%|██▏       | 180/837 [00:07<00:24, 26.68it/s]

 22%|██▏       | 183/837 [00:07<00:24, 27.07it/s]

 22%|██▏       | 186/837 [00:07<00:24, 27.06it/s]

 23%|██▎       | 189/837 [00:07<00:24, 26.20it/s]

 23%|██▎       | 192/837 [00:07<00:24, 26.72it/s]

 23%|██▎       | 195/837 [00:07<00:24, 26.28it/s]

 24%|██▎       | 198/837 [00:07<00:24, 26.57it/s]

 24%|██▍       | 201/837 [00:07<00:23, 27.07it/s]

 24%|██▍       | 204/837 [00:08<00:23, 27.35it/s]

 25%|██▍       | 207/837 [00:08<00:23, 27.11it/s]

 25%|██▌       | 210/837 [00:08<00:23, 26.65it/s]

 25%|██▌       | 213/837 [00:08<00:24, 25.02it/s]

 26%|██▌       | 216/837 [00:08<00:24, 25.66it/s]

 26%|██▌       | 219/837 [00:08<00:23, 26.40it/s]

 27%|██▋       | 222/837 [00:08<00:23, 26.51it/s]

 27%|██▋       | 225/837 [00:08<00:23, 26.04it/s]

 27%|██▋       | 228/837 [00:09<00:23, 26.05it/s]

 28%|██▊       | 231/837 [00:09<00:23, 25.86it/s]

 28%|██▊       | 234/837 [00:09<00:23, 25.73it/s]

 28%|██▊       | 237/837 [00:09<00:22, 26.27it/s]

 29%|██▊       | 240/837 [00:09<00:22, 26.36it/s]

 29%|██▉       | 243/837 [00:09<00:22, 26.48it/s]

 29%|██▉       | 246/837 [00:09<00:22, 26.43it/s]

 30%|██▉       | 249/837 [00:09<00:21, 26.75it/s]

 30%|███       | 252/837 [00:09<00:21, 26.69it/s]

 30%|███       | 255/837 [00:10<00:21, 26.79it/s]

 31%|███       | 258/837 [00:10<00:21, 26.72it/s]

 31%|███       | 261/837 [00:10<00:21, 26.60it/s]

 32%|███▏      | 264/837 [00:10<00:21, 26.30it/s]

 32%|███▏      | 267/837 [00:10<00:21, 26.80it/s]

 32%|███▏      | 270/837 [00:10<00:21, 26.03it/s]

 33%|███▎      | 273/837 [00:10<00:21, 26.67it/s]

 33%|███▎      | 276/837 [00:10<00:21, 26.56it/s]

 33%|███▎      | 279/837 [00:10<00:20, 27.06it/s]

 34%|███▎      | 282/837 [00:11<00:20, 27.27it/s]

 34%|███▍      | 285/837 [00:11<00:20, 26.62it/s]

 34%|███▍      | 288/837 [00:11<00:20, 26.60it/s]

 35%|███▍      | 291/837 [00:11<00:20, 26.94it/s]

 35%|███▌      | 294/837 [00:11<00:20, 26.12it/s]

 35%|███▌      | 297/837 [00:11<00:21, 25.58it/s]

 36%|███▌      | 300/837 [00:11<00:20, 26.00it/s]

 36%|███▌      | 303/837 [00:11<00:20, 26.58it/s]

 37%|███▋      | 306/837 [00:11<00:20, 26.50it/s]

 37%|███▋      | 309/837 [00:12<00:19, 26.73it/s]

 37%|███▋      | 312/837 [00:12<00:21, 24.51it/s]

 38%|███▊      | 315/837 [00:12<00:20, 24.97it/s]

 38%|███▊      | 318/837 [00:12<00:20, 25.49it/s]

 38%|███▊      | 321/837 [00:12<00:19, 26.06it/s]

 39%|███▊      | 324/837 [00:12<00:20, 25.54it/s]

 39%|███▉      | 327/837 [00:12<00:19, 26.31it/s]

 39%|███▉      | 330/837 [00:12<00:20, 25.25it/s]

 40%|███▉      | 333/837 [00:13<00:21, 23.80it/s]

 40%|████      | 336/837 [00:13<00:20, 24.68it/s]

 41%|████      | 339/837 [00:13<00:19, 25.21it/s]

 41%|████      | 342/837 [00:13<00:19, 24.84it/s]

 41%|████      | 345/837 [00:13<00:19, 25.07it/s]

 42%|████▏     | 348/837 [00:13<00:18, 26.10it/s]

 42%|████▏     | 351/837 [00:13<00:18, 26.72it/s]

 42%|████▏     | 354/837 [00:13<00:17, 27.03it/s]

 43%|████▎     | 357/837 [00:13<00:19, 24.57it/s]

 43%|████▎     | 360/837 [00:14<00:18, 25.32it/s]

 43%|████▎     | 363/837 [00:14<00:19, 24.91it/s]

 44%|████▎     | 366/837 [00:14<00:18, 25.28it/s]

 44%|████▍     | 369/837 [00:14<00:18, 24.76it/s]

 44%|████▍     | 372/837 [00:14<00:19, 24.00it/s]

 45%|████▍     | 375/837 [00:14<00:18, 24.83it/s]

 45%|████▌     | 378/837 [00:14<00:17, 25.52it/s]

 46%|████▌     | 381/837 [00:14<00:17, 25.82it/s]

 46%|████▌     | 384/837 [00:15<00:17, 26.45it/s]

 46%|████▌     | 387/837 [00:15<00:17, 26.13it/s]

 47%|████▋     | 390/837 [00:15<00:16, 26.82it/s]

 47%|████▋     | 393/837 [00:15<00:17, 25.91it/s]

 47%|████▋     | 396/837 [00:15<00:18, 24.38it/s]

 48%|████▊     | 399/837 [00:15<00:17, 25.12it/s]

 48%|████▊     | 402/837 [00:15<00:17, 24.89it/s]

 48%|████▊     | 405/837 [00:15<00:16, 25.83it/s]

 49%|████▊     | 408/837 [00:15<00:16, 26.38it/s]

 49%|████▉     | 411/837 [00:16<00:16, 26.36it/s]

 49%|████▉     | 414/837 [00:16<00:17, 24.42it/s]

 50%|████▉     | 417/837 [00:16<00:16, 24.90it/s]

 50%|█████     | 420/837 [00:16<00:16, 25.50it/s]

 51%|█████     | 423/837 [00:16<00:15, 26.07it/s]

 51%|█████     | 426/837 [00:16<00:15, 26.35it/s]

 51%|█████▏    | 429/837 [00:16<00:15, 26.00it/s]

 52%|█████▏    | 432/837 [00:16<00:15, 25.50it/s]

 52%|█████▏    | 435/837 [00:17<00:15, 26.49it/s]

 52%|█████▏    | 438/837 [00:17<00:14, 26.65it/s]

 53%|█████▎    | 441/837 [00:17<00:16, 24.71it/s]

 53%|█████▎    | 444/837 [00:17<00:15, 25.30it/s]

 53%|█████▎    | 447/837 [00:17<00:15, 25.99it/s]

 54%|█████▍    | 450/837 [00:17<00:14, 26.30it/s]

 54%|█████▍    | 453/837 [00:17<00:14, 26.30it/s]

 54%|█████▍    | 456/837 [00:17<00:14, 26.24it/s]

 55%|█████▍    | 459/837 [00:17<00:14, 26.61it/s]

 55%|█████▌    | 462/837 [00:18<00:14, 25.51it/s]

 56%|█████▌    | 465/837 [00:18<00:14, 25.61it/s]

 56%|█████▌    | 468/837 [00:18<00:14, 25.95it/s]

 56%|█████▋    | 471/837 [00:18<00:13, 26.55it/s]

 57%|█████▋    | 474/837 [00:18<00:13, 26.27it/s]

 57%|█████▋    | 477/837 [00:18<00:13, 26.63it/s]

 57%|█████▋    | 480/837 [00:18<00:13, 27.11it/s]

 58%|█████▊    | 483/837 [00:18<00:13, 26.80it/s]

 58%|█████▊    | 486/837 [00:18<00:12, 27.30it/s]

 58%|█████▊    | 489/837 [00:19<00:12, 27.67it/s]

 59%|█████▉    | 492/837 [00:19<00:12, 27.55it/s]

 59%|█████▉    | 495/837 [00:19<00:12, 27.17it/s]

 59%|█████▉    | 498/837 [00:19<00:12, 27.23it/s]

 60%|█████▉    | 501/837 [00:19<00:12, 27.54it/s]

 60%|██████    | 504/837 [00:19<00:12, 27.54it/s]

 61%|██████    | 507/837 [00:19<00:12, 27.46it/s]

 61%|██████    | 510/837 [00:19<00:11, 27.40it/s]

 61%|██████▏   | 513/837 [00:19<00:11, 27.51it/s]

 62%|██████▏   | 516/837 [00:20<00:11, 27.75it/s]

 62%|██████▏   | 519/837 [00:20<00:11, 27.45it/s]

 62%|██████▏   | 522/837 [00:20<00:11, 27.85it/s]

 63%|██████▎   | 525/837 [00:20<00:11, 27.60it/s]

 63%|██████▎   | 528/837 [00:20<00:11, 27.65it/s]

 63%|██████▎   | 531/837 [00:20<00:11, 27.61it/s]

 64%|██████▍   | 534/837 [00:20<00:11, 26.99it/s]

 64%|██████▍   | 537/837 [00:20<00:11, 27.08it/s]

 65%|██████▍   | 540/837 [00:20<00:11, 26.99it/s]

 65%|██████▍   | 543/837 [00:21<00:10, 27.07it/s]

 65%|██████▌   | 546/837 [00:21<00:10, 27.21it/s]

 66%|██████▌   | 549/837 [00:21<00:10, 26.50it/s]

 66%|██████▌   | 552/837 [00:21<00:10, 26.45it/s]

 66%|██████▋   | 555/837 [00:21<00:10, 26.69it/s]

 67%|██████▋   | 558/837 [00:21<00:10, 27.08it/s]

 67%|██████▋   | 561/837 [00:21<00:10, 27.06it/s]

 67%|██████▋   | 564/837 [00:21<00:09, 27.58it/s]

 68%|██████▊   | 567/837 [00:21<00:09, 27.87it/s]

 68%|██████▊   | 570/837 [00:22<00:09, 27.46it/s]

 68%|██████▊   | 573/837 [00:22<00:09, 26.89it/s]

 69%|██████▉   | 576/837 [00:22<00:09, 26.50it/s]

 69%|██████▉   | 579/837 [00:22<00:09, 27.24it/s]

 70%|██████▉   | 582/837 [00:22<00:09, 26.81it/s]

 70%|██████▉   | 585/837 [00:22<00:09, 27.02it/s]

 70%|███████   | 588/837 [00:22<00:09, 27.47it/s]

 71%|███████   | 591/837 [00:22<00:09, 27.11it/s]

 71%|███████   | 594/837 [00:22<00:08, 27.46it/s]

 71%|███████▏  | 597/837 [00:23<00:08, 27.86it/s]

 72%|███████▏  | 600/837 [00:23<00:08, 27.45it/s]

 72%|███████▏  | 603/837 [00:23<00:08, 27.40it/s]

 72%|███████▏  | 606/837 [00:23<00:08, 27.29it/s]

 73%|███████▎  | 609/837 [00:23<00:08, 27.36it/s]

 73%|███████▎  | 612/837 [00:23<00:08, 27.63it/s]

 73%|███████▎  | 615/837 [00:23<00:07, 27.75it/s]

 74%|███████▍  | 618/837 [00:23<00:07, 27.84it/s]

 74%|███████▍  | 621/837 [00:23<00:07, 27.74it/s]

 75%|███████▍  | 624/837 [00:24<00:07, 27.08it/s]

 75%|███████▍  | 627/837 [00:24<00:07, 27.28it/s]

 75%|███████▌  | 630/837 [00:24<00:07, 27.21it/s]

 76%|███████▌  | 633/837 [00:24<00:07, 27.49it/s]

 76%|███████▌  | 636/837 [00:24<00:07, 27.35it/s]

 76%|███████▋  | 639/837 [00:24<00:07, 27.55it/s]

 77%|███████▋  | 642/837 [00:24<00:07, 27.62it/s]

 77%|███████▋  | 645/837 [00:24<00:06, 27.51it/s]

 77%|███████▋  | 648/837 [00:24<00:06, 27.75it/s]

 78%|███████▊  | 651/837 [00:24<00:06, 27.99it/s]

 78%|███████▊  | 654/837 [00:25<00:06, 28.08it/s]

 78%|███████▊  | 657/837 [00:25<00:06, 28.23it/s]

 79%|███████▉  | 660/837 [00:25<00:06, 27.93it/s]

 79%|███████▉  | 663/837 [00:25<00:06, 27.73it/s]

 80%|███████▉  | 666/837 [00:25<00:06, 27.75it/s]

 80%|███████▉  | 669/837 [00:25<00:06, 27.38it/s]

 80%|████████  | 672/837 [00:25<00:06, 27.27it/s]

 81%|████████  | 675/837 [00:25<00:05, 27.42it/s]

 81%|████████  | 678/837 [00:25<00:05, 27.45it/s]

 81%|████████▏ | 681/837 [00:26<00:05, 27.62it/s]

 82%|████████▏ | 684/837 [00:26<00:05, 26.85it/s]

 82%|████████▏ | 687/837 [00:26<00:05, 27.12it/s]

 82%|████████▏ | 690/837 [00:26<00:05, 25.31it/s]

 83%|████████▎ | 693/837 [00:26<00:05, 26.07it/s]

 83%|████████▎ | 696/837 [00:26<00:05, 25.74it/s]

 84%|████████▎ | 699/837 [00:26<00:05, 25.51it/s]

 84%|████████▍ | 702/837 [00:26<00:05, 25.82it/s]

 84%|████████▍ | 705/837 [00:27<00:05, 25.83it/s]

 85%|████████▍ | 708/837 [00:27<00:04, 26.25it/s]

 85%|████████▍ | 711/837 [00:27<00:04, 26.76it/s]

 85%|████████▌ | 714/837 [00:27<00:04, 26.41it/s]

 86%|████████▌ | 717/837 [00:27<00:04, 27.32it/s]

 86%|████████▌ | 720/837 [00:27<00:04, 27.61it/s]

 86%|████████▋ | 723/837 [00:27<00:04, 27.43it/s]

 87%|████████▋ | 726/837 [00:27<00:04, 27.53it/s]

 87%|████████▋ | 729/837 [00:27<00:03, 27.76it/s]

 87%|████████▋ | 732/837 [00:27<00:03, 26.94it/s]

 88%|████████▊ | 735/837 [00:28<00:03, 27.49it/s]

 88%|████████▊ | 738/837 [00:28<00:03, 27.20it/s]

 89%|████████▊ | 741/837 [00:28<00:03, 26.93it/s]

 89%|████████▉ | 744/837 [00:28<00:03, 27.33it/s]

 89%|████████▉ | 747/837 [00:28<00:03, 27.61it/s]

 90%|████████▉ | 750/837 [00:28<00:03, 27.51it/s]

 90%|████████▉ | 753/837 [00:28<00:03, 27.74it/s]

 90%|█████████ | 756/837 [00:28<00:02, 27.91it/s]

 91%|█████████ | 759/837 [00:28<00:02, 27.34it/s]

 91%|█████████ | 762/837 [00:29<00:02, 27.62it/s]

 91%|█████████▏| 765/837 [00:29<00:02, 27.07it/s]

 92%|█████████▏| 768/837 [00:29<00:02, 27.24it/s]

 92%|█████████▏| 771/837 [00:29<00:02, 27.32it/s]

 92%|█████████▏| 774/837 [00:29<00:02, 27.69it/s]

 93%|█████████▎| 777/837 [00:29<00:02, 27.79it/s]

 93%|█████████▎| 780/837 [00:29<00:02, 27.26it/s]

 94%|█████████▎| 783/837 [00:29<00:01, 27.56it/s]

 94%|█████████▍| 786/837 [00:29<00:01, 27.03it/s]

 94%|█████████▍| 789/837 [00:30<00:01, 27.40it/s]

 95%|█████████▍| 792/837 [00:30<00:01, 27.59it/s]

 95%|█████████▍| 795/837 [00:30<00:01, 27.49it/s]

 95%|█████████▌| 798/837 [00:30<00:01, 26.91it/s]

 96%|█████████▌| 801/837 [00:30<00:01, 26.38it/s]

 96%|█████████▌| 804/837 [00:30<00:01, 25.55it/s]

 96%|█████████▋| 807/837 [00:30<00:01, 25.91it/s]

 97%|█████████▋| 810/837 [00:30<00:01, 26.10it/s]

 97%|█████████▋| 813/837 [00:30<00:00, 26.09it/s]

 97%|█████████▋| 816/837 [00:31<00:00, 26.65it/s]

 98%|█████████▊| 819/837 [00:31<00:00, 25.86it/s]

 98%|█████████▊| 822/837 [00:31<00:00, 26.55it/s]

 99%|█████████▊| 825/837 [00:31<00:00, 26.48it/s]

 99%|█████████▉| 828/837 [00:31<00:00, 26.93it/s]

 99%|█████████▉| 831/837 [00:31<00:00, 26.88it/s]

100%|█████████▉| 834/837 [00:31<00:00, 27.00it/s]

100%|██████████| 837/837 [00:31<00:00, 26.86it/s]

100%|██████████| 837/837 [00:31<00:00, 26.26it/s]

Processing camera: MOT17-09-FRCNN, frames: 525

  0%|          | 0/525 [00:00<?, ?it/s]

  1%|          | 3/525 [00:00<00:20, 25.42it/s]

  1%|          | 6/525 [00:00<00:21, 24.45it/s]

  2%|▏         | 9/525 [00:00<00:21, 23.55it/s]

  2%|▏         | 12/525 [00:00<00:20, 24.73it/s]

  3%|▎         | 15/525 [00:00<00:20, 25.20it/s]

  3%|▎         | 18/525 [00:00<00:20, 24.92it/s]

  4%|▍         | 21/525 [00:00<00:20, 25.08it/s]

  5%|▍         | 24/525 [00:00<00:19, 25.33it/s]

  5%|▌         | 27/525 [00:01<00:19, 25.63it/s]

  6%|▌         | 30/525 [00:01<00:19, 25.84it/s]

  6%|▋         | 33/525 [00:01<00:18, 25.98it/s]

  7%|▋         | 36/525 [00:01<00:19, 25.61it/s]

  7%|▋         | 39/525 [00:01<00:18, 25.82it/s]

  8%|▊         | 42/525 [00:01<00:19, 24.99it/s]

  9%|▊         | 45/525 [00:01<00:20, 23.85it/s]

  9%|▉         | 48/525 [00:01<00:19, 24.42it/s]

 10%|▉         | 51/525 [00:02<00:19, 24.90it/s]

 10%|█         | 54/525 [00:02<00:18, 25.31it/s]

 11%|█         | 57/525 [00:02<00:18, 25.54it/s]

 11%|█▏        | 60/525 [00:02<00:18, 24.81it/s]

 12%|█▏        | 63/525 [00:02<00:18, 25.15it/s]

 13%|█▎        | 66/525 [00:02<00:18, 25.42it/s]

 13%|█▎        | 69/525 [00:02<00:17, 25.49it/s]

 14%|█▎        | 72/525 [00:02<00:18, 24.23it/s]

 14%|█▍        | 75/525 [00:02<00:18, 24.70it/s]

 15%|█▍        | 78/525 [00:03<00:18, 24.79it/s]

 15%|█▌        | 81/525 [00:03<00:17, 25.29it/s]

 16%|█▌        | 84/525 [00:03<00:17, 25.66it/s]

 17%|█▋        | 87/525 [00:03<00:16, 25.85it/s]

 17%|█▋        | 90/525 [00:03<00:17, 25.27it/s]

 18%|█▊        | 93/525 [00:03<00:17, 25.25it/s]

 18%|█▊        | 96/525 [00:03<00:16, 25.49it/s]

 19%|█▉        | 99/525 [00:03<00:17, 24.54it/s]

 19%|█▉        | 102/525 [00:04<00:16, 24.92it/s]

 20%|██        | 105/525 [00:04<00:16, 25.39it/s]

 21%|██        | 108/525 [00:04<00:16, 25.08it/s]

 21%|██        | 111/525 [00:04<00:16, 25.37it/s]

 22%|██▏       | 114/525 [00:04<00:16, 25.58it/s]

 22%|██▏       | 117/525 [00:04<00:15, 25.80it/s]

 23%|██▎       | 120/525 [00:04<00:15, 25.95it/s]

 23%|██▎       | 123/525 [00:04<00:15, 25.79it/s]

 24%|██▍       | 126/525 [00:04<00:15, 25.88it/s]

 25%|██▍       | 129/525 [00:05<00:15, 26.08it/s]

 25%|██▌       | 132/525 [00:05<00:15, 25.88it/s]

 26%|██▌       | 135/525 [00:05<00:15, 25.94it/s]

 26%|██▋       | 138/525 [00:05<00:14, 26.05it/s]

 27%|██▋       | 141/525 [00:05<00:14, 26.06it/s]

 27%|██▋       | 144/525 [00:05<00:14, 26.07it/s]

 28%|██▊       | 147/525 [00:05<00:14, 26.07it/s]

 29%|██▊       | 150/525 [00:05<00:14, 25.68it/s]

 29%|██▉       | 153/525 [00:06<00:14, 25.80it/s]

 30%|██▉       | 156/525 [00:06<00:14, 25.42it/s]

 30%|███       | 159/525 [00:06<00:14, 25.68it/s]

 31%|███       | 162/525 [00:06<00:14, 24.97it/s]

 31%|███▏      | 165/525 [00:06<00:15, 23.96it/s]

 32%|███▏      | 168/525 [00:06<00:14, 24.50it/s]

 33%|███▎      | 171/525 [00:06<00:14, 24.89it/s]

 33%|███▎      | 174/525 [00:06<00:14, 23.52it/s]

 34%|███▎      | 177/525 [00:07<00:15, 23.17it/s]

 34%|███▍      | 180/525 [00:07<00:14, 23.80it/s]

 35%|███▍      | 183/525 [00:07<00:14, 24.09it/s]

 35%|███▌      | 186/525 [00:07<00:13, 24.36it/s]

 36%|███▌      | 189/525 [00:07<00:13, 24.39it/s]

 37%|███▋      | 192/525 [00:07<00:13, 24.82it/s]

 37%|███▋      | 195/525 [00:07<00:13, 24.51it/s]

 38%|███▊      | 198/525 [00:07<00:13, 24.96it/s]

 38%|███▊      | 201/525 [00:08<00:13, 24.66it/s]

 39%|███▉      | 204/525 [00:08<00:12, 25.07it/s]

 39%|███▉      | 207/525 [00:08<00:12, 25.43it/s]

 40%|████      | 210/525 [00:08<00:12, 25.05it/s]

 41%|████      | 213/525 [00:08<00:12, 25.16it/s]

 41%|████      | 216/525 [00:08<00:12, 25.24it/s]

 42%|████▏     | 219/525 [00:08<00:12, 25.29it/s]

 42%|████▏     | 222/525 [00:08<00:12, 24.71it/s]

 43%|████▎     | 225/525 [00:08<00:12, 24.67it/s]

 43%|████▎     | 228/525 [00:09<00:11, 24.83it/s]

 44%|████▍     | 231/525 [00:09<00:12, 23.05it/s]

 45%|████▍     | 234/525 [00:09<00:12, 23.32it/s]

 45%|████▌     | 237/525 [00:09<00:12, 23.97it/s]

 46%|████▌     | 240/525 [00:09<00:11, 23.87it/s]

 46%|████▋     | 243/525 [00:09<00:11, 24.61it/s]

 47%|████▋     | 246/525 [00:09<00:11, 24.67it/s]

 47%|████▋     | 249/525 [00:09<00:11, 23.88it/s]

 48%|████▊     | 252/525 [00:10<00:11, 24.56it/s]

 49%|████▊     | 255/525 [00:10<00:10, 24.57it/s]

 49%|████▉     | 258/525 [00:10<00:10, 24.88it/s]

 50%|████▉     | 261/525 [00:10<00:10, 25.23it/s]

 50%|█████     | 264/525 [00:10<00:10, 25.35it/s]

 51%|█████     | 267/525 [00:10<00:10, 25.50it/s]

 51%|█████▏    | 270/525 [00:10<00:09, 25.68it/s]

 52%|█████▏    | 273/525 [00:10<00:09, 25.34it/s]

 53%|█████▎    | 276/525 [00:11<00:09, 25.37it/s]

 53%|█████▎    | 279/525 [00:11<00:10, 24.16it/s]

 54%|█████▎    | 282/525 [00:11<00:10, 24.23it/s]

 54%|█████▍    | 285/525 [00:11<00:09, 24.57it/s]

 55%|█████▍    | 288/525 [00:11<00:09, 24.95it/s]

 55%|█████▌    | 291/525 [00:11<00:09, 25.21it/s]

 56%|█████▌    | 294/525 [00:11<00:09, 23.95it/s]

 57%|█████▋    | 297/525 [00:11<00:09, 23.90it/s]

 57%|█████▋    | 300/525 [00:12<00:09, 23.54it/s]

 58%|█████▊    | 303/525 [00:12<00:09, 23.34it/s]

 58%|█████▊    | 306/525 [00:12<00:10, 21.89it/s]

 59%|█████▉    | 309/525 [00:12<00:09, 22.01it/s]

 59%|█████▉    | 312/525 [00:12<00:09, 22.83it/s]

 60%|██████    | 315/525 [00:12<00:09, 22.59it/s]

 61%|██████    | 318/525 [00:12<00:09, 21.06it/s]

 61%|██████    | 321/525 [00:13<00:09, 21.44it/s]

 62%|██████▏   | 324/525 [00:13<00:09, 21.30it/s]

 62%|██████▏   | 327/525 [00:13<00:09, 21.11it/s]

 63%|██████▎   | 330/525 [00:13<00:09, 21.25it/s]

 63%|██████▎   | 333/525 [00:13<00:08, 21.91it/s]

 64%|██████▍   | 336/525 [00:13<00:08, 22.40it/s]

 65%|██████▍   | 339/525 [00:13<00:08, 21.90it/s]

 65%|██████▌   | 342/525 [00:13<00:08, 21.95it/s]

 66%|██████▌   | 345/525 [00:14<00:07, 23.10it/s]

 66%|██████▋   | 348/525 [00:14<00:07, 23.86it/s]

 67%|██████▋   | 351/525 [00:14<00:07, 22.16it/s]

 67%|██████▋   | 354/525 [00:14<00:07, 21.93it/s]

 68%|██████▊   | 357/525 [00:14<00:07, 21.18it/s]

 69%|██████▊   | 360/525 [00:14<00:07, 22.00it/s]

 69%|██████▉   | 363/525 [00:14<00:07, 22.21it/s]

 70%|██████▉   | 366/525 [00:15<00:06, 22.88it/s]

 70%|███████   | 369/525 [00:15<00:06, 23.31it/s]

 71%|███████   | 372/525 [00:15<00:06, 21.92it/s]

 71%|███████▏  | 375/525 [00:15<00:06, 22.81it/s]

 72%|███████▏  | 378/525 [00:15<00:06, 23.21it/s]

 73%|███████▎  | 381/525 [00:15<00:06, 23.66it/s]

 73%|███████▎  | 384/525 [00:15<00:05, 24.05it/s]

 74%|███████▎  | 387/525 [00:15<00:05, 24.50it/s]

 74%|███████▍  | 390/525 [00:16<00:05, 24.12it/s]

 75%|███████▍  | 393/525 [00:16<00:05, 24.37it/s]

 75%|███████▌  | 396/525 [00:16<00:05, 23.14it/s]

 76%|███████▌  | 399/525 [00:16<00:05, 23.89it/s]

 77%|███████▋  | 402/525 [00:16<00:05, 23.15it/s]

 77%|███████▋  | 405/525 [00:16<00:05, 23.73it/s]

 78%|███████▊  | 408/525 [00:16<00:04, 24.04it/s]

 78%|███████▊  | 411/525 [00:16<00:04, 24.09it/s]

 79%|███████▉  | 414/525 [00:17<00:04, 24.53it/s]

 79%|███████▉  | 417/525 [00:17<00:04, 24.61it/s]

 80%|████████  | 420/525 [00:17<00:04, 23.90it/s]

 81%|████████  | 423/525 [00:17<00:04, 22.76it/s]

 81%|████████  | 426/525 [00:17<00:04, 22.05it/s]

 82%|████████▏ | 429/525 [00:17<00:04, 21.12it/s]

 82%|████████▏ | 432/525 [00:17<00:04, 20.68it/s]

 83%|████████▎ | 435/525 [00:18<00:04, 21.08it/s]

 83%|████████▎ | 438/525 [00:18<00:03, 22.42it/s]

 84%|████████▍ | 441/525 [00:18<00:03, 22.46it/s]

 85%|████████▍ | 444/525 [00:18<00:03, 21.94it/s]

 85%|████████▌ | 447/525 [00:18<00:03, 21.32it/s]

 86%|████████▌ | 450/525 [00:18<00:03, 20.56it/s]

 86%|████████▋ | 453/525 [00:18<00:03, 20.19it/s]

 87%|████████▋ | 456/525 [00:19<00:03, 21.11it/s]

 87%|████████▋ | 459/525 [00:19<00:03, 21.57it/s]

 88%|████████▊ | 462/525 [00:19<00:02, 21.43it/s]

 89%|████████▊ | 465/525 [00:19<00:02, 21.67it/s]

 89%|████████▉ | 468/525 [00:19<00:02, 21.73it/s]

 90%|████████▉ | 471/525 [00:19<00:02, 21.64it/s]

 90%|█████████ | 474/525 [00:19<00:02, 21.12it/s]

 91%|█████████ | 477/525 [00:20<00:02, 20.60it/s]

 91%|█████████▏| 480/525 [00:20<00:02, 20.21it/s]

 92%|█████████▏| 483/525 [00:20<00:02, 20.01it/s]

 93%|█████████▎| 486/525 [00:20<00:02, 19.27it/s]

 93%|█████████▎| 488/525 [00:20<00:01, 18.94it/s]

 94%|█████████▎| 491/525 [00:20<00:01, 19.51it/s]

 94%|█████████▍| 494/525 [00:20<00:01, 19.50it/s]

 94%|█████████▍| 496/525 [00:20<00:01, 19.48it/s]

 95%|█████████▍| 498/525 [00:21<00:01, 19.19it/s]

 95%|█████████▌| 500/525 [00:21<00:01, 18.82it/s]

 96%|█████████▌| 502/525 [00:21<00:01, 18.98it/s]

 96%|█████████▌| 504/525 [00:21<00:01, 18.65it/s]

 96%|█████████▋| 506/525 [00:21<00:01, 18.76it/s]

 97%|█████████▋| 508/525 [00:21<00:00, 18.79it/s]

 97%|█████████▋| 511/525 [00:21<00:00, 19.58it/s]

 98%|█████████▊| 513/525 [00:21<00:00, 19.43it/s]

 98%|█████████▊| 515/525 [00:22<00:00, 19.22it/s]

 98%|█████████▊| 517/525 [00:22<00:00, 18.76it/s]

 99%|█████████▉| 519/525 [00:22<00:00, 18.85it/s]

 99%|█████████▉| 521/525 [00:22<00:00, 18.85it/s]

100%|█████████▉| 523/525 [00:22<00:00, 18.99it/s]

100%|██████████| 525/525 [00:22<00:00, 19.06it/s]

100%|██████████| 525/525 [00:22<00:00, 23.30it/s]

Processing camera: MOT17-10-FRCNN, frames: 654

  0%|          | 0/654 [00:00<?, ?it/s]

  0%|          | 2/654 [00:00<00:32, 19.80it/s]

  1%|          | 4/654 [00:00<00:33, 19.69it/s]

  1%|          | 6/654 [00:00<00:33, 19.56it/s]

  1%|          | 8/654 [00:00<00:32, 19.66it/s]

  2%|▏         | 11/654 [00:00<00:31, 20.49it/s]

  2%|▏         | 14/654 [00:00<00:31, 20.13it/s]

  3%|▎         | 17/654 [00:00<00:32, 19.66it/s]

  3%|▎         | 19/654 [00:00<00:32, 19.40it/s]

  3%|▎         | 22/654 [00:01<00:31, 20.22it/s]

  4%|▍         | 25/654 [00:01<00:30, 20.80it/s]

  4%|▍         | 28/654 [00:01<00:29, 21.34it/s]

  5%|▍         | 31/654 [00:01<00:28, 21.66it/s]

  5%|▌         | 34/654 [00:01<00:28, 21.40it/s]

  6%|▌         | 37/654 [00:01<00:29, 20.68it/s]

  6%|▌         | 40/654 [00:01<00:30, 20.21it/s]

  7%|▋         | 43/654 [00:02<00:30, 20.23it/s]

  7%|▋         | 46/654 [00:02<00:29, 20.45it/s]

  7%|▋         | 49/654 [00:02<00:29, 20.61it/s]

  8%|▊         | 52/654 [00:02<00:28, 20.81it/s]

  8%|▊         | 55/654 [00:02<00:28, 20.90it/s]

  9%|▉         | 58/654 [00:02<00:28, 21.06it/s]

  9%|▉         | 61/654 [00:02<00:28, 21.03it/s]

 10%|▉         | 64/654 [00:03<00:27, 21.47it/s]

 10%|█         | 67/654 [00:03<00:26, 22.02it/s]

 11%|█         | 70/654 [00:03<00:27, 21.28it/s]

 11%|█         | 73/654 [00:03<00:27, 21.01it/s]

 12%|█▏        | 76/654 [00:03<00:27, 21.09it/s]

 12%|█▏        | 79/654 [00:03<00:26, 21.89it/s]

 13%|█▎        | 82/654 [00:03<00:26, 21.65it/s]

 13%|█▎        | 85/654 [00:04<00:26, 21.22it/s]

 13%|█▎        | 88/654 [00:04<00:26, 20.99it/s]

 14%|█▍        | 91/654 [00:04<00:27, 20.26it/s]

 14%|█▍        | 94/654 [00:04<00:27, 20.22it/s]

 15%|█▍        | 97/654 [00:04<00:27, 20.04it/s]

 15%|█▌        | 100/654 [00:04<00:27, 19.79it/s]

 16%|█▌        | 102/654 [00:04<00:28, 19.26it/s]

 16%|█▌        | 104/654 [00:05<00:29, 18.95it/s]

 16%|█▌        | 106/654 [00:05<00:29, 18.88it/s]

 17%|█▋        | 108/654 [00:05<00:29, 18.28it/s]

 17%|█▋        | 110/654 [00:05<00:29, 18.16it/s]

 17%|█▋        | 112/654 [00:05<00:30, 17.98it/s]

 17%|█▋        | 114/654 [00:05<00:30, 17.99it/s]

 18%|█▊        | 116/654 [00:05<00:30, 17.90it/s]

 18%|█▊        | 118/654 [00:05<00:29, 18.18it/s]

 18%|█▊        | 120/654 [00:05<00:29, 17.94it/s]

 19%|█▊        | 122/654 [00:06<00:30, 17.45it/s]

 19%|█▉        | 124/654 [00:06<00:31, 16.69it/s]

 19%|█▉        | 126/654 [00:06<00:31, 16.81it/s]

 20%|█▉        | 128/654 [00:06<00:30, 17.29it/s]

 20%|█▉        | 130/654 [00:06<00:30, 17.36it/s]

 20%|██        | 132/654 [00:06<00:29, 17.69it/s]

 20%|██        | 134/654 [00:06<00:28, 18.08it/s]

 21%|██        | 136/654 [00:06<00:28, 18.16it/s]

 21%|██        | 138/654 [00:07<00:29, 17.54it/s]

 21%|██▏       | 140/654 [00:07<00:29, 17.54it/s]

 22%|██▏       | 142/654 [00:07<00:28, 17.83it/s]

 22%|██▏       | 144/654 [00:07<00:28, 17.88it/s]

 22%|██▏       | 146/654 [00:07<00:27, 18.17it/s]

 23%|██▎       | 148/654 [00:07<00:27, 18.47it/s]

 23%|██▎       | 150/654 [00:07<00:27, 18.54it/s]

 23%|██▎       | 152/654 [00:07<00:28, 17.46it/s]

 24%|██▎       | 154/654 [00:07<00:29, 17.00it/s]

 24%|██▍       | 156/654 [00:08<00:28, 17.34it/s]

 24%|██▍       | 158/654 [00:08<00:28, 17.44it/s]

 24%|██▍       | 160/654 [00:08<00:28, 17.16it/s]

 25%|██▍       | 162/654 [00:08<00:29, 16.75it/s]

 25%|██▌       | 164/654 [00:08<00:29, 16.56it/s]

 25%|██▌       | 166/654 [00:08<00:29, 16.55it/s]

 26%|██▌       | 168/654 [00:08<00:28, 17.32it/s]

 26%|██▌       | 170/654 [00:08<00:29, 16.52it/s]

 26%|██▋       | 172/654 [00:09<00:33, 14.51it/s]

 27%|██▋       | 174/654 [00:09<00:32, 14.70it/s]

 27%|██▋       | 176/654 [00:09<00:31, 15.38it/s]

 27%|██▋       | 178/654 [00:09<00:30, 15.71it/s]

 28%|██▊       | 180/654 [00:09<00:30, 15.50it/s]

 28%|██▊       | 182/654 [00:09<00:36, 13.02it/s]

 28%|██▊       | 184/654 [00:09<00:33, 13.98it/s]

 28%|██▊       | 186/654 [00:09<00:32, 14.50it/s]

 29%|██▊       | 188/654 [00:10<00:31, 14.78it/s]

 29%|██▉       | 190/654 [00:10<00:30, 15.06it/s]

 29%|██▉       | 192/654 [00:10<00:29, 15.40it/s]

 30%|██▉       | 194/654 [00:10<00:29, 15.80it/s]

 30%|██▉       | 196/654 [00:10<00:27, 16.36it/s]

 30%|███       | 198/654 [00:10<00:27, 16.83it/s]

 31%|███       | 200/654 [00:10<00:26, 16.95it/s]

 31%|███       | 202/654 [00:10<00:26, 17.21it/s]

 31%|███       | 204/654 [00:11<00:26, 17.09it/s]

 31%|███▏      | 206/654 [00:11<00:26, 17.05it/s]

 32%|███▏      | 208/654 [00:11<00:26, 16.93it/s]

 32%|███▏      | 210/654 [00:11<00:26, 17.02it/s]

 32%|███▏      | 212/654 [00:11<00:25, 17.18it/s]

 33%|███▎      | 214/654 [00:11<00:24, 17.60it/s]

 33%|███▎      | 216/654 [00:11<00:24, 18.16it/s]

 33%|███▎      | 218/654 [00:11<00:24, 17.92it/s]

 34%|███▎      | 220/654 [00:11<00:23, 18.30it/s]

 34%|███▍      | 222/654 [00:12<00:25, 17.18it/s]

 34%|███▍      | 224/654 [00:12<00:25, 17.11it/s]

 35%|███▍      | 226/654 [00:12<00:25, 16.97it/s]

 35%|███▍      | 228/654 [00:12<00:24, 17.27it/s]

 35%|███▌      | 230/654 [00:12<00:24, 17.22it/s]

 35%|███▌      | 232/654 [00:12<00:24, 17.32it/s]

 36%|███▌      | 234/654 [00:12<00:23, 17.90it/s]

 36%|███▌      | 236/654 [00:12<00:23, 18.03it/s]

 36%|███▋      | 238/654 [00:12<00:23, 17.79it/s]

 37%|███▋      | 240/654 [00:13<00:23, 17.81it/s]

 37%|███▋      | 242/654 [00:13<00:22, 18.02it/s]

 37%|███▋      | 244/654 [00:13<00:22, 18.29it/s]

 38%|███▊      | 246/654 [00:13<00:22, 18.01it/s]

 38%|███▊      | 248/654 [00:13<00:22, 18.31it/s]

 38%|███▊      | 250/654 [00:13<00:22, 17.83it/s]

 39%|███▊      | 252/654 [00:13<00:22, 18.23it/s]

 39%|███▉      | 254/654 [00:13<00:21, 18.47it/s]

 39%|███▉      | 256/654 [00:13<00:21, 18.64it/s]

 39%|███▉      | 258/654 [00:14<00:21, 18.81it/s]

 40%|███▉      | 260/654 [00:14<00:20, 18.83it/s]

 40%|████      | 262/654 [00:14<00:21, 18.22it/s]

 40%|████      | 264/654 [00:14<00:22, 17.73it/s]

 41%|████      | 266/654 [00:14<00:22, 17.44it/s]

 41%|████      | 269/654 [00:14<00:20, 18.76it/s]

 41%|████▏     | 271/654 [00:14<00:20, 18.65it/s]

 42%|████▏     | 273/654 [00:14<00:20, 18.73it/s]

 42%|████▏     | 275/654 [00:15<00:20, 18.82it/s]

 42%|████▏     | 277/654 [00:15<00:20, 18.53it/s]

 43%|████▎     | 279/654 [00:15<00:20, 18.33it/s]

 43%|████▎     | 281/654 [00:15<00:21, 17.62it/s]

 43%|████▎     | 283/654 [00:15<00:21, 17.19it/s]

 44%|████▎     | 285/654 [00:15<00:20, 17.75it/s]

 44%|████▍     | 287/654 [00:15<00:21, 17.37it/s]

 44%|████▍     | 289/654 [00:15<00:20, 17.65it/s]

 44%|████▍     | 291/654 [00:15<00:20, 17.57it/s]

 45%|████▍     | 293/654 [00:16<00:20, 17.66it/s]

 45%|████▌     | 295/654 [00:16<00:20, 17.81it/s]

 45%|████▌     | 297/654 [00:16<00:20, 17.64it/s]

 46%|████▌     | 299/654 [00:16<00:20, 17.56it/s]

 46%|████▌     | 301/654 [00:16<00:20, 17.42it/s]

 46%|████▋     | 303/654 [00:16<00:19, 17.64it/s]

 47%|████▋     | 305/654 [00:16<00:19, 18.14it/s]

 47%|████▋     | 307/654 [00:16<00:19, 17.91it/s]

 47%|████▋     | 309/654 [00:16<00:19, 17.52it/s]

 48%|████▊     | 311/654 [00:17<00:19, 17.30it/s]

 48%|████▊     | 313/654 [00:17<00:19, 17.79it/s]

 48%|████▊     | 315/654 [00:17<00:18, 18.20it/s]

 48%|████▊     | 317/654 [00:17<00:18, 18.44it/s]

 49%|████▉     | 319/654 [00:17<00:17, 18.62it/s]

 49%|████▉     | 322/654 [00:17<00:16, 19.83it/s]

 50%|████▉     | 325/654 [00:17<00:15, 20.83it/s]

 50%|█████     | 328/654 [00:17<00:15, 21.44it/s]

 51%|█████     | 331/654 [00:18<00:14, 22.05it/s]

 51%|█████     | 334/654 [00:18<00:14, 22.47it/s]

 52%|█████▏    | 337/654 [00:18<00:14, 22.19it/s]

 52%|█████▏    | 340/654 [00:18<00:14, 21.85it/s]

 52%|█████▏    | 343/654 [00:18<00:14, 21.77it/s]

 53%|█████▎    | 346/654 [00:18<00:14, 21.62it/s]

 53%|█████▎    | 349/654 [00:18<00:13, 21.99it/s]

 54%|█████▍    | 352/654 [00:18<00:13, 22.21it/s]

 54%|█████▍    | 355/654 [00:19<00:13, 22.26it/s]

 55%|█████▍    | 358/654 [00:19<00:13, 21.39it/s]

 55%|█████▌    | 361/654 [00:19<00:13, 22.11it/s]

 56%|█████▌    | 364/654 [00:19<00:13, 21.07it/s]

 56%|█████▌    | 367/654 [00:19<00:13, 21.59it/s]

 57%|█████▋    | 370/654 [00:19<00:13, 21.63it/s]

 57%|█████▋    | 373/654 [00:19<00:12, 21.74it/s]

 57%|█████▋    | 376/654 [00:20<00:12, 21.69it/s]

 58%|█████▊    | 379/654 [00:20<00:12, 21.52it/s]

 58%|█████▊    | 382/654 [00:20<00:12, 22.21it/s]

 59%|█████▉    | 385/654 [00:20<00:12, 21.22it/s]

 59%|█████▉    | 388/654 [00:20<00:12, 21.51it/s]

 60%|█████▉    | 391/654 [00:20<00:11, 21.96it/s]

 60%|██████    | 394/654 [00:20<00:11, 22.38it/s]

 61%|██████    | 397/654 [00:21<00:11, 22.48it/s]

 61%|██████    | 400/654 [00:21<00:11, 22.76it/s]

 62%|██████▏   | 403/654 [00:21<00:10, 23.12it/s]

 62%|██████▏   | 406/654 [00:21<00:10, 23.05it/s]

 63%|██████▎   | 409/654 [00:21<00:10, 23.17it/s]

 63%|██████▎   | 412/654 [00:21<00:10, 23.19it/s]

 63%|██████▎   | 415/654 [00:21<00:11, 21.11it/s]

 64%|██████▍   | 418/654 [00:21<00:11, 21.38it/s]

 64%|██████▍   | 421/654 [00:22<00:10, 21.72it/s]

 65%|██████▍   | 424/654 [00:22<00:10, 21.92it/s]

 65%|██████▌   | 427/654 [00:22<00:10, 22.35it/s]

 66%|██████▌   | 430/654 [00:22<00:09, 22.56it/s]

 66%|██████▌   | 433/654 [00:22<00:10, 22.06it/s]

 67%|██████▋   | 436/654 [00:22<00:09, 21.92it/s]

 67%|██████▋   | 439/654 [00:22<00:09, 22.11it/s]

 68%|██████▊   | 442/654 [00:23<00:09, 22.14it/s]

 68%|██████▊   | 445/654 [00:23<00:09, 22.51it/s]

 69%|██████▊   | 448/654 [00:23<00:08, 22.94it/s]

 69%|██████▉   | 451/654 [00:23<00:08, 23.14it/s]

 69%|██████▉   | 454/654 [00:23<00:08, 23.34it/s]

 70%|██████▉   | 457/654 [00:23<00:08, 22.63it/s]

 70%|███████   | 460/654 [00:23<00:08, 22.66it/s]

 71%|███████   | 463/654 [00:23<00:08, 22.52it/s]

 71%|███████▏  | 466/654 [00:24<00:08, 22.69it/s]

 72%|███████▏  | 469/654 [00:24<00:08, 22.96it/s]

 72%|███████▏  | 472/654 [00:24<00:07, 23.00it/s]

 73%|███████▎  | 475/654 [00:24<00:07, 23.13it/s]

 73%|███████▎  | 478/654 [00:24<00:07, 22.85it/s]

 74%|███████▎  | 481/654 [00:24<00:07, 21.86it/s]

 74%|███████▍  | 484/654 [00:24<00:07, 22.34it/s]

 74%|███████▍  | 487/654 [00:25<00:07, 22.50it/s]

 75%|███████▍  | 490/654 [00:25<00:07, 22.37it/s]

 75%|███████▌  | 493/654 [00:25<00:07, 22.58it/s]

 76%|███████▌  | 496/654 [00:25<00:07, 22.57it/s]

 76%|███████▋  | 499/654 [00:25<00:06, 22.57it/s]

 77%|███████▋  | 502/654 [00:25<00:06, 22.72it/s]

 77%|███████▋  | 505/654 [00:25<00:06, 22.82it/s]

 78%|███████▊  | 508/654 [00:25<00:06, 23.00it/s]

 78%|███████▊  | 511/654 [00:26<00:06, 22.92it/s]

 79%|███████▊  | 514/654 [00:26<00:06, 22.76it/s]

 79%|███████▉  | 517/654 [00:26<00:05, 23.01it/s]

 80%|███████▉  | 520/654 [00:26<00:05, 23.19it/s]

 80%|███████▉  | 523/654 [00:26<00:05, 23.10it/s]

 80%|████████  | 526/654 [00:26<00:05, 23.10it/s]

 81%|████████  | 529/654 [00:26<00:05, 23.04it/s]

 81%|████████▏ | 532/654 [00:26<00:05, 22.13it/s]

 82%|████████▏ | 535/654 [00:27<00:05, 22.46it/s]

 82%|████████▏ | 538/654 [00:27<00:05, 22.79it/s]

 83%|████████▎ | 541/654 [00:27<00:04, 22.83it/s]

 83%|████████▎ | 544/654 [00:27<00:04, 22.44it/s]

 84%|████████▎ | 547/654 [00:27<00:04, 22.73it/s]

 84%|████████▍ | 550/654 [00:27<00:04, 22.68it/s]

 85%|████████▍ | 553/654 [00:27<00:04, 21.85it/s]

 85%|████████▌ | 556/654 [00:28<00:04, 21.30it/s]

 85%|████████▌ | 559/654 [00:28<00:04, 21.67it/s]

 86%|████████▌ | 562/654 [00:28<00:04, 21.78it/s]

 86%|████████▋ | 565/654 [00:28<00:04, 22.06it/s]

 87%|████████▋ | 568/654 [00:28<00:03, 22.20it/s]

 87%|████████▋ | 571/654 [00:28<00:03, 22.36it/s]

 88%|████████▊ | 574/654 [00:28<00:03, 22.62it/s]

 88%|████████▊ | 577/654 [00:29<00:03, 22.81it/s]

 89%|████████▊ | 580/654 [00:29<00:03, 22.28it/s]

 89%|████████▉ | 583/654 [00:29<00:03, 22.82it/s]

 90%|████████▉ | 586/654 [00:29<00:03, 22.43it/s]

 90%|█████████ | 589/654 [00:29<00:02, 22.07it/s]

 91%|█████████ | 592/654 [00:29<00:02, 22.17it/s]

 91%|█████████ | 595/654 [00:29<00:02, 22.33it/s]

 91%|█████████▏| 598/654 [00:29<00:02, 22.17it/s]

 92%|█████████▏| 601/654 [00:30<00:02, 22.29it/s]

 92%|█████████▏| 604/654 [00:30<00:02, 22.37it/s]

 93%|█████████▎| 607/654 [00:30<00:02, 22.58it/s]

 93%|█████████▎| 610/654 [00:30<00:01, 22.57it/s]

 94%|█████████▎| 613/654 [00:30<00:01, 22.82it/s]

 94%|█████████▍| 616/654 [00:30<00:01, 23.00it/s]

 95%|█████████▍| 619/654 [00:30<00:01, 22.87it/s]

 95%|█████████▌| 622/654 [00:31<00:01, 22.72it/s]

 96%|█████████▌| 625/654 [00:31<00:01, 22.98it/s]

 96%|█████████▌| 628/654 [00:31<00:01, 23.12it/s]

 96%|█████████▋| 631/654 [00:31<00:01, 23.00it/s]

 97%|█████████▋| 634/654 [00:31<00:00, 23.18it/s]

 97%|█████████▋| 637/654 [00:31<00:00, 23.37it/s]

 98%|█████████▊| 640/654 [00:31<00:00, 23.39it/s]

 98%|█████████▊| 643/654 [00:31<00:00, 22.51it/s]

 99%|█████████▉| 646/654 [00:32<00:00, 22.03it/s]

 99%|█████████▉| 649/654 [00:32<00:00, 22.48it/s]

100%|█████████▉| 652/654 [00:32<00:00, 22.92it/s]

100%|██████████| 654/654 [00:32<00:00, 20.18it/s]

Processing camera: MOT17-11-FRCNN, frames: 900

  0%|          | 0/900 [00:00<?, ?it/s]

  0%|          | 3/900 [00:00<00:40, 22.39it/s]

  1%|          | 6/900 [00:00<00:38, 22.99it/s]

  1%|          | 9/900 [00:00<00:38, 22.95it/s]

  1%|▏         | 12/900 [00:00<00:38, 23.07it/s]

  2%|▏         | 15/900 [00:00<00:38, 23.07it/s]

  2%|▏         | 18/900 [00:00<00:39, 22.37it/s]

  2%|▏         | 21/900 [00:00<00:38, 22.94it/s]

  3%|▎         | 24/900 [00:01<00:39, 22.38it/s]

  3%|▎         | 27/900 [00:01<00:39, 22.33it/s]

  3%|▎         | 30/900 [00:01<00:39, 21.99it/s]

  4%|▎         | 33/900 [00:01<00:39, 22.16it/s]

  4%|▍         | 36/900 [00:01<00:38, 22.69it/s]

  4%|▍         | 39/900 [00:01<00:37, 22.81it/s]

  5%|▍         | 42/900 [00:01<00:38, 22.32it/s]

  5%|▌         | 45/900 [00:02<00:38, 22.19it/s]

  5%|▌         | 48/900 [00:02<00:38, 22.01it/s]

  6%|▌         | 51/900 [00:02<00:38, 22.12it/s]

  6%|▌         | 54/900 [00:02<00:38, 22.10it/s]

  6%|▋         | 57/900 [00:02<00:37, 22.31it/s]

  7%|▋         | 60/900 [00:02<00:38, 21.66it/s]

  7%|▋         | 63/900 [00:02<00:38, 21.54it/s]

  7%|▋         | 66/900 [00:02<00:37, 21.98it/s]

  8%|▊         | 69/900 [00:03<00:37, 22.30it/s]

  8%|▊         | 72/900 [00:03<00:36, 22.68it/s]

  8%|▊         | 75/900 [00:03<00:37, 21.90it/s]

  9%|▊         | 78/900 [00:03<00:37, 22.14it/s]

  9%|▉         | 81/900 [00:03<00:36, 22.17it/s]

  9%|▉         | 84/900 [00:03<00:37, 21.75it/s]

 10%|▉         | 87/900 [00:03<00:36, 21.98it/s]

 10%|█         | 90/900 [00:04<00:36, 22.40it/s]

 10%|█         | 93/900 [00:04<00:36, 22.20it/s]

 11%|█         | 96/900 [00:04<00:36, 22.06it/s]

 11%|█         | 99/900 [00:04<00:35, 22.26it/s]

 11%|█▏        | 102/900 [00:04<00:35, 22.60it/s]

 12%|█▏        | 105/900 [00:04<00:34, 22.79it/s]

 12%|█▏        | 108/900 [00:04<00:35, 22.26it/s]

 12%|█▏        | 111/900 [00:04<00:35, 22.06it/s]

 13%|█▎        | 114/900 [00:05<00:35, 22.01it/s]

 13%|█▎        | 117/900 [00:05<00:35, 22.27it/s]

 13%|█▎        | 120/900 [00:05<00:34, 22.61it/s]

 14%|█▎        | 123/900 [00:05<00:35, 22.09it/s]

 14%|█▍        | 126/900 [00:05<00:34, 22.18it/s]

 14%|█▍        | 129/900 [00:05<00:34, 22.34it/s]

 15%|█▍        | 132/900 [00:05<00:33, 22.76it/s]

 15%|█▌        | 135/900 [00:06<00:33, 22.96it/s]

 15%|█▌        | 138/900 [00:06<00:32, 23.16it/s]

 16%|█▌        | 141/900 [00:06<00:32, 23.24it/s]

 16%|█▌        | 144/900 [00:06<00:33, 22.72it/s]

 16%|█▋        | 147/900 [00:06<00:33, 22.67it/s]

 17%|█▋        | 150/900 [00:06<00:33, 22.53it/s]

 17%|█▋        | 153/900 [00:06<00:33, 22.49it/s]

 17%|█▋        | 156/900 [00:06<00:32, 22.61it/s]

 18%|█▊        | 159/900 [00:07<00:32, 22.75it/s]

 18%|█▊        | 162/900 [00:07<00:32, 22.95it/s]

 18%|█▊        | 165/900 [00:07<00:32, 22.94it/s]

 19%|█▊        | 168/900 [00:07<00:31, 23.11it/s]

 19%|█▉        | 171/900 [00:07<00:31, 23.10it/s]

 19%|█▉        | 174/900 [00:07<00:32, 22.32it/s]

 20%|█▉        | 177/900 [00:07<00:35, 20.59it/s]

 20%|██        | 180/900 [00:08<00:35, 20.37it/s]

 20%|██        | 183/900 [00:08<00:36, 19.39it/s]

 21%|██        | 186/900 [00:08<00:36, 19.53it/s]

 21%|██        | 189/900 [00:08<00:34, 20.39it/s]

 21%|██▏       | 192/900 [00:08<00:33, 21.31it/s]

 22%|██▏       | 195/900 [00:08<00:32, 21.48it/s]

 22%|██▏       | 198/900 [00:08<00:32, 21.56it/s]

 22%|██▏       | 201/900 [00:09<00:32, 21.75it/s]

 23%|██▎       | 204/900 [00:09<00:31, 22.18it/s]

 23%|██▎       | 207/900 [00:09<00:30, 22.60it/s]

 23%|██▎       | 210/900 [00:09<00:30, 22.43it/s]

 24%|██▎       | 213/900 [00:09<00:30, 22.37it/s]

 24%|██▍       | 216/900 [00:09<00:30, 22.27it/s]

 24%|██▍       | 219/900 [00:09<00:30, 22.01it/s]

 25%|██▍       | 222/900 [00:10<00:30, 22.32it/s]

 25%|██▌       | 225/900 [00:10<00:31, 21.71it/s]

 25%|██▌       | 228/900 [00:10<00:30, 22.01it/s]

 26%|██▌       | 231/900 [00:10<00:30, 21.78it/s]

 26%|██▌       | 234/900 [00:10<00:30, 22.11it/s]

 26%|██▋       | 237/900 [00:10<00:29, 22.69it/s]

 27%|██▋       | 240/900 [00:10<00:29, 22.76it/s]

 27%|██▋       | 243/900 [00:10<00:29, 22.64it/s]

 27%|██▋       | 246/900 [00:11<00:28, 22.77it/s]

 28%|██▊       | 249/900 [00:11<00:28, 22.81it/s]

 28%|██▊       | 252/900 [00:11<00:28, 22.38it/s]

 28%|██▊       | 255/900 [00:11<00:29, 21.56it/s]

 29%|██▊       | 258/900 [00:11<00:31, 20.46it/s]

 29%|██▉       | 261/900 [00:11<00:29, 21.36it/s]

 29%|██▉       | 264/900 [00:11<00:29, 21.85it/s]

 30%|██▉       | 267/900 [00:12<00:30, 20.65it/s]

 30%|███       | 270/900 [00:12<00:29, 21.64it/s]

 30%|███       | 273/900 [00:12<00:28, 22.05it/s]

 31%|███       | 276/900 [00:12<00:28, 22.18it/s]

 31%|███       | 279/900 [00:12<00:28, 21.76it/s]

 31%|███▏      | 282/900 [00:12<00:28, 22.04it/s]

 32%|███▏      | 285/900 [00:12<00:27, 22.49it/s]

 32%|███▏      | 288/900 [00:13<00:27, 22.36it/s]

 32%|███▏      | 291/900 [00:13<00:27, 22.17it/s]

 33%|███▎      | 294/900 [00:13<00:26, 22.59it/s]

 33%|███▎      | 297/900 [00:13<00:26, 22.53it/s]

 33%|███▎      | 300/900 [00:13<00:26, 22.59it/s]

 34%|███▎      | 303/900 [00:13<00:26, 22.89it/s]

 34%|███▍      | 306/900 [00:13<00:26, 22.53it/s]

 34%|███▍      | 309/900 [00:13<00:25, 23.06it/s]

 35%|███▍      | 312/900 [00:14<00:26, 22.00it/s]

 35%|███▌      | 315/900 [00:14<00:26, 22.02it/s]

 35%|███▌      | 318/900 [00:14<00:26, 21.79it/s]

 36%|███▌      | 321/900 [00:14<00:26, 22.06it/s]

 36%|███▌      | 324/900 [00:14<00:26, 22.11it/s]

 36%|███▋      | 327/900 [00:14<00:25, 22.39it/s]

 37%|███▋      | 330/900 [00:14<00:25, 22.29it/s]

 37%|███▋      | 333/900 [00:15<00:25, 22.37it/s]

 37%|███▋      | 336/900 [00:15<00:25, 22.33it/s]

 38%|███▊      | 339/900 [00:15<00:24, 22.96it/s]

 38%|███▊      | 342/900 [00:15<00:24, 23.10it/s]

 38%|███▊      | 345/900 [00:15<00:23, 23.36it/s]

 39%|███▊      | 348/900 [00:15<00:23, 23.01it/s]

 39%|███▉      | 351/900 [00:15<00:23, 23.41it/s]

 39%|███▉      | 354/900 [00:15<00:23, 23.53it/s]

 40%|███▉      | 357/900 [00:16<00:23, 23.55it/s]

 40%|████      | 360/900 [00:16<00:24, 21.64it/s]

 40%|████      | 363/900 [00:16<00:24, 21.95it/s]

 41%|████      | 366/900 [00:16<00:24, 22.18it/s]

 41%|████      | 369/900 [00:16<00:23, 22.39it/s]

 41%|████▏     | 372/900 [00:16<00:23, 22.70it/s]

 42%|████▏     | 375/900 [00:16<00:23, 22.30it/s]

 42%|████▏     | 378/900 [00:17<00:23, 22.53it/s]

 42%|████▏     | 381/900 [00:17<00:23, 21.66it/s]

 43%|████▎     | 384/900 [00:17<00:23, 22.31it/s]

 43%|████▎     | 387/900 [00:17<00:23, 21.94it/s]

 43%|████▎     | 390/900 [00:17<00:22, 22.29it/s]

 44%|████▎     | 393/900 [00:17<00:22, 22.17it/s]

 44%|████▍     | 396/900 [00:17<00:22, 22.34it/s]

 44%|████▍     | 399/900 [00:17<00:21, 22.81it/s]

 45%|████▍     | 402/900 [00:18<00:21, 23.00it/s]

 45%|████▌     | 405/900 [00:18<00:22, 22.06it/s]

 45%|████▌     | 408/900 [00:18<00:23, 21.04it/s]

 46%|████▌     | 411/900 [00:18<00:22, 21.80it/s]

 46%|████▌     | 414/900 [00:18<00:22, 21.64it/s]

 46%|████▋     | 417/900 [00:18<00:22, 21.62it/s]

 47%|████▋     | 420/900 [00:18<00:22, 21.75it/s]

 47%|████▋     | 423/900 [00:19<00:21, 21.70it/s]

 47%|████▋     | 426/900 [00:19<00:21, 22.09it/s]

 48%|████▊     | 429/900 [00:19<00:21, 22.38it/s]

 48%|████▊     | 432/900 [00:19<00:22, 20.84it/s]

 48%|████▊     | 435/900 [00:19<00:21, 21.15it/s]

 49%|████▊     | 438/900 [00:19<00:21, 21.32it/s]

 49%|████▉     | 441/900 [00:19<00:21, 21.45it/s]

 49%|████▉     | 444/900 [00:20<00:20, 22.06it/s]

 50%|████▉     | 447/900 [00:20<00:20, 21.86it/s]

 50%|█████     | 450/900 [00:20<00:20, 22.41it/s]

 50%|█████     | 453/900 [00:20<00:19, 22.61it/s]

 51%|█████     | 456/900 [00:20<00:20, 21.95it/s]

 51%|█████     | 459/900 [00:20<00:19, 22.42it/s]

 51%|█████▏    | 462/900 [00:20<00:19, 22.72it/s]

 52%|█████▏    | 465/900 [00:20<00:19, 22.62it/s]

 52%|█████▏    | 468/900 [00:21<00:19, 22.65it/s]

 52%|█████▏    | 471/900 [00:21<00:19, 21.93it/s]

 53%|█████▎    | 474/900 [00:21<00:19, 21.68it/s]

 53%|█████▎    | 477/900 [00:21<00:19, 22.18it/s]

 53%|█████▎    | 480/900 [00:21<00:18, 22.14it/s]

 54%|█████▎    | 483/900 [00:21<00:18, 22.67it/s]

 54%|█████▍    | 486/900 [00:21<00:17, 23.00it/s]

 54%|█████▍    | 489/900 [00:22<00:17, 23.13it/s]

 55%|█████▍    | 492/900 [00:22<00:17, 22.85it/s]

 55%|█████▌    | 495/900 [00:22<00:17, 22.81it/s]

 55%|█████▌    | 498/900 [00:22<00:17, 22.94it/s]

 56%|█████▌    | 501/900 [00:22<00:17, 22.64it/s]

 56%|█████▌    | 504/900 [00:22<00:17, 22.62it/s]

 56%|█████▋    | 507/900 [00:22<00:17, 22.60it/s]

 57%|█████▋    | 510/900 [00:22<00:17, 22.69it/s]

 57%|█████▋    | 513/900 [00:23<00:16, 22.96it/s]

 57%|█████▋    | 516/900 [00:23<00:17, 22.53it/s]

 58%|█████▊    | 519/900 [00:23<00:16, 22.74it/s]

 58%|█████▊    | 522/900 [00:23<00:16, 22.84it/s]

 58%|█████▊    | 525/900 [00:23<00:16, 22.86it/s]

 59%|█████▊    | 528/900 [00:23<00:16, 23.19it/s]

 59%|█████▉    | 531/900 [00:23<00:15, 23.26it/s]

 59%|█████▉    | 534/900 [00:23<00:15, 23.48it/s]

 60%|█████▉    | 537/900 [00:24<00:15, 23.36it/s]

 60%|██████    | 540/900 [00:24<00:15, 22.90it/s]

 60%|██████    | 543/900 [00:24<00:15, 23.06it/s]

 61%|██████    | 546/900 [00:24<00:15, 23.01it/s]

 61%|██████    | 549/900 [00:24<00:15, 22.87it/s]

 61%|██████▏   | 552/900 [00:24<00:15, 22.78it/s]

 62%|██████▏   | 555/900 [00:24<00:14, 23.18it/s]

 62%|██████▏   | 558/900 [00:25<00:14, 23.48it/s]

 62%|██████▏   | 561/900 [00:25<00:14, 23.09it/s]

 63%|██████▎   | 564/900 [00:25<00:14, 23.19it/s]

 63%|██████▎   | 567/900 [00:25<00:14, 22.58it/s]

 63%|██████▎   | 570/900 [00:25<00:14, 22.32it/s]

 64%|██████▎   | 573/900 [00:25<00:14, 22.49it/s]

 64%|██████▍   | 576/900 [00:25<00:14, 22.66it/s]

 64%|██████▍   | 579/900 [00:25<00:14, 22.58it/s]

 65%|██████▍   | 582/900 [00:26<00:13, 22.94it/s]

 65%|██████▌   | 585/900 [00:26<00:13, 22.98it/s]

 65%|██████▌   | 588/900 [00:26<00:13, 22.69it/s]

 66%|██████▌   | 591/900 [00:26<00:13, 23.07it/s]

 66%|██████▌   | 594/900 [00:26<00:13, 23.23it/s]

 66%|██████▋   | 597/900 [00:26<00:12, 23.35it/s]

 67%|██████▋   | 600/900 [00:26<00:13, 23.00it/s]

 67%|██████▋   | 603/900 [00:26<00:12, 23.13it/s]

 67%|██████▋   | 606/900 [00:27<00:12, 23.44it/s]

 68%|██████▊   | 609/900 [00:27<00:12, 23.27it/s]

 68%|██████▊   | 612/900 [00:27<00:12, 22.90it/s]

 68%|██████▊   | 615/900 [00:27<00:12, 23.11it/s]

 69%|██████▊   | 618/900 [00:27<00:12, 23.04it/s]

 69%|██████▉   | 621/900 [00:27<00:12, 22.53it/s]

 69%|██████▉   | 624/900 [00:27<00:12, 22.44it/s]

 70%|██████▉   | 627/900 [00:28<00:11, 22.83it/s]

 70%|███████   | 630/900 [00:28<00:11, 22.60it/s]

 70%|███████   | 633/900 [00:28<00:11, 22.53it/s]

 71%|███████   | 636/900 [00:28<00:11, 22.75it/s]

 71%|███████   | 639/900 [00:28<00:11, 22.84it/s]

 71%|███████▏  | 642/900 [00:28<00:11, 23.18it/s]

 72%|███████▏  | 645/900 [00:28<00:10, 23.31it/s]

 72%|███████▏  | 648/900 [00:28<00:10, 23.40it/s]

 72%|███████▏  | 651/900 [00:29<00:10, 23.52it/s]

 73%|███████▎  | 654/900 [00:29<00:10, 22.80it/s]

 73%|███████▎  | 657/900 [00:29<00:11, 21.98it/s]

 73%|███████▎  | 660/900 [00:29<00:11, 21.34it/s]

 74%|███████▎  | 663/900 [00:29<00:11, 20.66it/s]

 74%|███████▍  | 666/900 [00:29<00:11, 21.06it/s]

 74%|███████▍  | 669/900 [00:29<00:10, 21.77it/s]

 75%|███████▍  | 672/900 [00:30<00:10, 22.34it/s]

 75%|███████▌  | 675/900 [00:30<00:10, 22.06it/s]

 75%|███████▌  | 678/900 [00:30<00:10, 21.08it/s]

 76%|███████▌  | 681/900 [00:30<00:10, 21.23it/s]

 76%|███████▌  | 684/900 [00:30<00:09, 21.80it/s]

 76%|███████▋  | 687/900 [00:30<00:09, 22.02it/s]

 77%|███████▋  | 690/900 [00:30<00:09, 21.65it/s]

 77%|███████▋  | 693/900 [00:31<00:09, 22.31it/s]

 77%|███████▋  | 696/900 [00:31<00:09, 22.33it/s]

 78%|███████▊  | 699/900 [00:31<00:09, 22.10it/s]

 78%|███████▊  | 702/900 [00:31<00:08, 22.29it/s]

 78%|███████▊  | 705/900 [00:31<00:08, 22.72it/s]

 79%|███████▊  | 708/900 [00:31<00:08, 22.98it/s]

 79%|███████▉  | 711/900 [00:31<00:08, 23.17it/s]

 79%|███████▉  | 714/900 [00:31<00:08, 22.98it/s]

 80%|███████▉  | 717/900 [00:32<00:08, 22.65it/s]

 80%|████████  | 720/900 [00:32<00:07, 22.77it/s]

 80%|████████  | 723/900 [00:32<00:08, 21.96it/s]

 81%|████████  | 726/900 [00:32<00:07, 22.16it/s]

 81%|████████  | 729/900 [00:32<00:07, 22.08it/s]

 81%|████████▏ | 732/900 [00:32<00:07, 21.88it/s]

 82%|████████▏ | 735/900 [00:32<00:07, 20.79it/s]

 82%|████████▏ | 738/900 [00:33<00:07, 20.89it/s]

 82%|████████▏ | 741/900 [00:33<00:07, 20.36it/s]

 83%|████████▎ | 744/900 [00:33<00:07, 20.25it/s]

 83%|████████▎ | 747/900 [00:33<00:07, 21.07it/s]

 83%|████████▎ | 750/900 [00:33<00:07, 21.09it/s]

 84%|████████▎ | 753/900 [00:33<00:07, 20.97it/s]

 84%|████████▍ | 756/900 [00:33<00:06, 21.28it/s]

 84%|████████▍ | 759/900 [00:34<00:06, 21.56it/s]

 85%|████████▍ | 762/900 [00:34<00:06, 21.52it/s]

 85%|████████▌ | 765/900 [00:34<00:06, 21.87it/s]

 85%|████████▌ | 768/900 [00:34<00:05, 22.32it/s]

 86%|████████▌ | 771/900 [00:34<00:05, 22.19it/s]

 86%|████████▌ | 774/900 [00:34<00:05, 21.67it/s]

 86%|████████▋ | 777/900 [00:34<00:05, 21.98it/s]

 87%|████████▋ | 780/900 [00:35<00:05, 21.03it/s]

 87%|████████▋ | 783/900 [00:35<00:05, 21.65it/s]

 87%|████████▋ | 786/900 [00:35<00:05, 21.87it/s]

 88%|████████▊ | 789/900 [00:35<00:04, 22.22it/s]

 88%|████████▊ | 792/900 [00:35<00:04, 21.83it/s]

 88%|████████▊ | 795/900 [00:35<00:04, 21.85it/s]

 89%|████████▊ | 798/900 [00:35<00:04, 22.20it/s]

 89%|████████▉ | 801/900 [00:35<00:04, 22.26it/s]

 89%|████████▉ | 804/900 [00:36<00:04, 22.50it/s]

 90%|████████▉ | 807/900 [00:36<00:04, 22.22it/s]

 90%|█████████ | 810/900 [00:36<00:04, 22.42it/s]

 90%|█████████ | 813/900 [00:36<00:03, 22.71it/s]

 91%|█████████ | 816/900 [00:36<00:03, 22.82it/s]

 91%|█████████ | 819/900 [00:36<00:03, 22.85it/s]

 91%|█████████▏| 822/900 [00:36<00:03, 22.81it/s]

 92%|█████████▏| 825/900 [00:37<00:03, 22.73it/s]

 92%|█████████▏| 828/900 [00:37<00:03, 23.05it/s]

 92%|█████████▏| 831/900 [00:37<00:02, 23.16it/s]

 93%|█████████▎| 834/900 [00:37<00:02, 23.08it/s]

 93%|█████████▎| 837/900 [00:37<00:02, 23.24it/s]

 93%|█████████▎| 840/900 [00:37<00:02, 23.35it/s]

 94%|█████████▎| 843/900 [00:37<00:02, 22.08it/s]

 94%|█████████▍| 846/900 [00:37<00:02, 21.79it/s]

 94%|█████████▍| 849/900 [00:38<00:02, 22.26it/s]

 95%|█████████▍| 852/900 [00:38<00:02, 22.60it/s]

 95%|█████████▌| 855/900 [00:38<00:01, 23.00it/s]

 95%|█████████▌| 858/900 [00:38<00:01, 22.71it/s]

 96%|█████████▌| 861/900 [00:38<00:01, 22.72it/s]

 96%|█████████▌| 864/900 [00:38<00:01, 22.88it/s]

 96%|█████████▋| 867/900 [00:38<00:01, 22.42it/s]

 97%|█████████▋| 870/900 [00:39<00:01, 22.46it/s]

 97%|█████████▋| 873/900 [00:39<00:01, 22.59it/s]

 97%|█████████▋| 876/900 [00:39<00:01, 22.89it/s]

 98%|█████████▊| 879/900 [00:39<00:00, 22.69it/s]

 98%|█████████▊| 882/900 [00:39<00:00, 22.85it/s]

 98%|█████████▊| 885/900 [00:39<00:00, 22.97it/s]

 99%|█████████▊| 888/900 [00:39<00:00, 22.95it/s]

 99%|█████████▉| 891/900 [00:39<00:00, 22.68it/s]

 99%|█████████▉| 894/900 [00:40<00:00, 22.79it/s]

100%|█████████▉| 897/900 [00:40<00:00, 22.98it/s]

100%|██████████| 900/900 [00:40<00:00, 23.23it/s]

100%|██████████| 900/900 [00:40<00:00, 22.32it/s]

Processing camera: MOT17-13-FRCNN, frames: 750

  0%|          | 0/750 [00:00<?, ?it/s]

  0%|          | 3/750 [00:00<00:34, 21.74it/s]

  1%|          | 6/750 [00:00<00:33, 21.93it/s]

  1%|          | 9/750 [00:00<00:33, 22.06it/s]

  2%|▏         | 12/750 [00:00<00:35, 20.71it/s]

  2%|▏         | 15/750 [00:00<00:36, 20.00it/s]

  2%|▏         | 18/750 [00:00<00:38, 19.01it/s]

  3%|▎         | 20/750 [00:01<00:39, 18.67it/s]

  3%|▎         | 22/750 [00:01<00:40, 18.11it/s]

  3%|▎         | 24/750 [00:01<00:41, 17.65it/s]

  3%|▎         | 26/750 [00:01<00:40, 17.71it/s]

  4%|▎         | 28/750 [00:01<00:40, 17.75it/s]

  4%|▍         | 30/750 [00:01<00:42, 16.95it/s]

  4%|▍         | 32/750 [00:01<00:45, 15.89it/s]

  5%|▍         | 34/750 [00:01<00:45, 15.77it/s]

  5%|▍         | 36/750 [00:02<00:46, 15.48it/s]

  5%|▌         | 38/750 [00:02<00:45, 15.50it/s]

  5%|▌         | 40/750 [00:02<00:46, 15.43it/s]

  6%|▌         | 42/750 [00:02<00:44, 15.78it/s]

  6%|▌         | 44/750 [00:02<00:44, 15.73it/s]

  6%|▌         | 46/750 [00:02<00:44, 15.85it/s]

  6%|▋         | 48/750 [00:02<00:43, 16.32it/s]

  7%|▋         | 50/750 [00:02<00:42, 16.46it/s]

  7%|▋         | 52/750 [00:03<00:44, 15.82it/s]

  7%|▋         | 54/750 [00:03<00:44, 15.72it/s]

  7%|▋         | 56/750 [00:03<00:43, 15.88it/s]

  8%|▊         | 58/750 [00:03<00:44, 15.58it/s]

  8%|▊         | 60/750 [00:03<00:44, 15.59it/s]

  8%|▊         | 62/750 [00:03<00:43, 15.98it/s]

  9%|▊         | 64/750 [00:03<00:41, 16.62it/s]

  9%|▉         | 66/750 [00:03<00:40, 17.02it/s]

  9%|▉         | 68/750 [00:03<00:40, 17.04it/s]

  9%|▉         | 71/750 [00:04<00:37, 18.30it/s]

 10%|▉         | 73/750 [00:04<00:37, 18.09it/s]

 10%|█         | 75/750 [00:04<00:36, 18.25it/s]

 10%|█         | 77/750 [00:04<00:37, 18.09it/s]

 11%|█         | 79/750 [00:04<00:37, 17.70it/s]

 11%|█         | 81/750 [00:04<00:38, 17.47it/s]

 11%|█         | 84/750 [00:04<00:35, 18.86it/s]

 12%|█▏        | 87/750 [00:04<00:33, 19.93it/s]

 12%|█▏        | 90/750 [00:05<00:31, 20.69it/s]

 12%|█▏        | 93/750 [00:05<00:31, 21.12it/s]

 13%|█▎        | 96/750 [00:05<00:30, 21.60it/s]

 13%|█▎        | 99/750 [00:05<00:30, 21.65it/s]

 14%|█▎        | 102/750 [00:05<00:29, 21.87it/s]

 14%|█▍        | 105/750 [00:05<00:30, 21.49it/s]

 14%|█▍        | 108/750 [00:05<00:30, 21.15it/s]

 15%|█▍        | 111/750 [00:06<00:29, 21.51it/s]

 15%|█▌        | 114/750 [00:06<00:29, 21.35it/s]

 16%|█▌        | 117/750 [00:06<00:30, 20.84it/s]

 16%|█▌        | 120/750 [00:06<00:29, 21.33it/s]

 16%|█▋        | 123/750 [00:06<00:29, 21.36it/s]

 17%|█▋        | 126/750 [00:06<00:29, 21.52it/s]

 17%|█▋        | 129/750 [00:06<00:29, 20.86it/s]

 18%|█▊        | 132/750 [00:07<00:30, 20.59it/s]

 18%|█▊        | 135/750 [00:07<00:29, 20.90it/s]

 18%|█▊        | 138/750 [00:07<00:30, 20.29it/s]

 19%|█▉        | 141/750 [00:07<00:29, 20.45it/s]

 19%|█▉        | 144/750 [00:07<00:29, 20.56it/s]

 20%|█▉        | 147/750 [00:07<00:28, 21.12it/s]

 20%|██        | 150/750 [00:07<00:28, 20.86it/s]

 20%|██        | 153/750 [00:08<00:28, 21.12it/s]

 21%|██        | 156/750 [00:08<00:28, 20.51it/s]

 21%|██        | 159/750 [00:08<00:29, 19.91it/s]

 22%|██▏       | 162/750 [00:08<00:28, 20.72it/s]

 22%|██▏       | 165/750 [00:08<00:28, 20.67it/s]

 22%|██▏       | 168/750 [00:08<00:27, 21.07it/s]

 23%|██▎       | 171/750 [00:08<00:28, 20.65it/s]

 23%|██▎       | 174/750 [00:09<00:29, 19.61it/s]

 23%|██▎       | 176/750 [00:09<00:29, 19.57it/s]

 24%|██▍       | 179/750 [00:09<00:28, 20.00it/s]

 24%|██▍       | 182/750 [00:09<00:27, 20.79it/s]

 25%|██▍       | 185/750 [00:09<00:26, 21.26it/s]

 25%|██▌       | 188/750 [00:09<00:25, 21.64it/s]

 25%|██▌       | 191/750 [00:09<00:25, 21.72it/s]

 26%|██▌       | 194/750 [00:10<00:25, 22.06it/s]

 26%|██▋       | 197/750 [00:10<00:25, 22.01it/s]

 27%|██▋       | 200/750 [00:10<00:25, 21.60it/s]

 27%|██▋       | 203/750 [00:10<00:24, 21.93it/s]

 27%|██▋       | 206/750 [00:10<00:24, 22.21it/s]

 28%|██▊       | 209/750 [00:10<00:25, 21.09it/s]

 28%|██▊       | 212/750 [00:10<00:26, 20.58it/s]

 29%|██▊       | 215/750 [00:11<00:25, 21.05it/s]

 29%|██▉       | 218/750 [00:11<00:25, 21.11it/s]

 29%|██▉       | 221/750 [00:11<00:26, 20.22it/s]

 30%|██▉       | 224/750 [00:11<00:25, 20.83it/s]

 30%|███       | 227/750 [00:11<00:24, 21.14it/s]

 31%|███       | 230/750 [00:11<00:23, 21.68it/s]

 31%|███       | 233/750 [00:11<00:23, 21.99it/s]

 31%|███▏      | 236/750 [00:12<00:23, 21.49it/s]

 32%|███▏      | 239/750 [00:12<00:23, 21.77it/s]

 32%|███▏      | 242/750 [00:12<00:23, 21.95it/s]

 33%|███▎      | 245/750 [00:12<00:23, 21.70it/s]

 33%|███▎      | 248/750 [00:12<00:23, 21.48it/s]

 33%|███▎      | 251/750 [00:12<00:22, 21.93it/s]

 34%|███▍      | 254/750 [00:12<00:22, 21.64it/s]

 34%|███▍      | 257/750 [00:12<00:22, 21.67it/s]

 35%|███▍      | 260/750 [00:13<00:23, 20.83it/s]

 35%|███▌      | 263/750 [00:13<00:22, 21.23it/s]

 35%|███▌      | 266/750 [00:13<00:22, 21.56it/s]

 36%|███▌      | 269/750 [00:13<00:21, 21.95it/s]

 36%|███▋      | 272/750 [00:13<00:21, 21.93it/s]

 37%|███▋      | 275/750 [00:13<00:21, 22.26it/s]

 37%|███▋      | 278/750 [00:13<00:21, 21.96it/s]

 37%|███▋      | 281/750 [00:14<00:21, 21.80it/s]

 38%|███▊      | 284/750 [00:14<00:21, 21.97it/s]

 38%|███▊      | 287/750 [00:14<00:20, 22.24it/s]

 39%|███▊      | 290/750 [00:14<00:20, 22.14it/s]

 39%|███▉      | 293/750 [00:14<00:20, 22.46it/s]

 39%|███▉      | 296/750 [00:14<00:20, 22.49it/s]

 40%|███▉      | 299/750 [00:14<00:19, 22.71it/s]

 40%|████      | 302/750 [00:15<00:19, 22.56it/s]

 41%|████      | 305/750 [00:15<00:19, 22.46it/s]

 41%|████      | 308/750 [00:15<00:19, 22.54it/s]

 41%|████▏     | 311/750 [00:15<00:20, 21.81it/s]

 42%|████▏     | 314/750 [00:15<00:20, 21.69it/s]

 42%|████▏     | 317/750 [00:15<00:19, 22.09it/s]

 43%|████▎     | 320/750 [00:15<00:19, 22.18it/s]

 43%|████▎     | 323/750 [00:15<00:19, 22.29it/s]

 43%|████▎     | 326/750 [00:16<00:19, 22.17it/s]

 44%|████▍     | 329/750 [00:16<00:19, 21.80it/s]

 44%|████▍     | 332/750 [00:16<00:19, 21.97it/s]

 45%|████▍     | 335/750 [00:16<00:19, 21.81it/s]

 45%|████▌     | 338/750 [00:16<00:18, 22.17it/s]

 45%|████▌     | 341/750 [00:16<00:18, 22.04it/s]

 46%|████▌     | 344/750 [00:16<00:18, 22.14it/s]

 46%|████▋     | 347/750 [00:17<00:18, 22.02it/s]

 47%|████▋     | 350/750 [00:17<00:18, 22.06it/s]

 47%|████▋     | 353/750 [00:17<00:18, 21.82it/s]

 47%|████▋     | 356/750 [00:17<00:19, 20.25it/s]

 48%|████▊     | 359/750 [00:17<00:19, 20.01it/s]

 48%|████▊     | 362/750 [00:17<00:19, 19.43it/s]

 49%|████▊     | 364/750 [00:17<00:20, 19.09it/s]

 49%|████▉     | 366/750 [00:18<00:20, 18.70it/s]

 49%|████▉     | 369/750 [00:18<00:19, 19.55it/s]

 50%|████▉     | 372/750 [00:18<00:18, 20.08it/s]

 50%|█████     | 375/750 [00:18<00:18, 20.81it/s]

 50%|█████     | 378/750 [00:18<00:17, 20.95it/s]

 51%|█████     | 381/750 [00:18<00:17, 21.47it/s]

 51%|█████     | 384/750 [00:18<00:16, 21.89it/s]

 52%|█████▏    | 387/750 [00:19<00:16, 21.94it/s]

 52%|█████▏    | 390/750 [00:19<00:16, 21.22it/s]

 52%|█████▏    | 393/750 [00:19<00:17, 20.41it/s]

 53%|█████▎    | 396/750 [00:19<00:17, 20.75it/s]

 53%|█████▎    | 399/750 [00:19<00:16, 21.04it/s]

 54%|█████▎    | 402/750 [00:19<00:16, 21.43it/s]

 54%|█████▍    | 405/750 [00:19<00:15, 21.80it/s]

 54%|█████▍    | 408/750 [00:20<00:15, 22.02it/s]

 55%|█████▍    | 411/750 [00:20<00:15, 21.75it/s]

 55%|█████▌    | 414/750 [00:20<00:15, 21.65it/s]

 56%|█████▌    | 417/750 [00:20<00:15, 21.49it/s]

 56%|█████▌    | 420/750 [00:20<00:15, 21.61it/s]

 56%|█████▋    | 423/750 [00:20<00:15, 21.74it/s]

 57%|█████▋    | 426/750 [00:20<00:14, 21.60it/s]

 57%|█████▋    | 429/750 [00:20<00:15, 21.32it/s]

 58%|█████▊    | 432/750 [00:21<00:14, 21.44it/s]

 58%|█████▊    | 435/750 [00:21<00:14, 21.58it/s]

 58%|█████▊    | 438/750 [00:21<00:14, 21.17it/s]

 59%|█████▉    | 441/750 [00:21<00:14, 21.38it/s]

 59%|█████▉    | 444/750 [00:21<00:13, 21.86it/s]

 60%|█████▉    | 447/750 [00:21<00:13, 22.12it/s]

 60%|██████    | 450/750 [00:21<00:13, 22.20it/s]

 60%|██████    | 453/750 [00:22<00:13, 21.91it/s]

 61%|██████    | 456/750 [00:22<00:13, 21.28it/s]

 61%|██████    | 459/750 [00:22<00:13, 21.84it/s]

 62%|██████▏   | 462/750 [00:22<00:13, 22.10it/s]

 62%|██████▏   | 465/750 [00:22<00:13, 21.84it/s]

 62%|██████▏   | 468/750 [00:22<00:12, 21.72it/s]

 63%|██████▎   | 471/750 [00:22<00:12, 21.77it/s]

 63%|██████▎   | 474/750 [00:23<00:12, 22.00it/s]

 64%|██████▎   | 477/750 [00:23<00:12, 22.07it/s]

 64%|██████▍   | 480/750 [00:23<00:12, 21.73it/s]

 64%|██████▍   | 483/750 [00:23<00:12, 21.59it/s]

 65%|██████▍   | 486/750 [00:23<00:12, 21.82it/s]

 65%|██████▌   | 489/750 [00:23<00:12, 21.66it/s]

 66%|██████▌   | 492/750 [00:23<00:11, 21.82it/s]

 66%|██████▌   | 495/750 [00:24<00:11, 21.80it/s]

 66%|██████▋   | 498/750 [00:24<00:11, 22.17it/s]

 67%|██████▋   | 501/750 [00:24<00:11, 22.23it/s]

 67%|██████▋   | 504/750 [00:24<00:11, 21.89it/s]

 68%|██████▊   | 507/750 [00:24<00:11, 22.04it/s]

 68%|██████▊   | 510/750 [00:24<00:10, 22.24it/s]

 68%|██████▊   | 513/750 [00:24<00:10, 22.38it/s]

 69%|██████▉   | 516/750 [00:24<00:10, 22.33it/s]

 69%|██████▉   | 519/750 [00:25<00:10, 22.25it/s]

 70%|██████▉   | 522/750 [00:25<00:10, 22.14it/s]

 70%|███████   | 525/750 [00:25<00:10, 21.83it/s]

 70%|███████   | 528/750 [00:25<00:10, 21.75it/s]

 71%|███████   | 531/750 [00:25<00:09, 21.94it/s]

 71%|███████   | 534/750 [00:25<00:09, 22.27it/s]

 72%|███████▏  | 537/750 [00:25<00:09, 22.26it/s]

 72%|███████▏  | 540/750 [00:26<00:09, 22.05it/s]

 72%|███████▏  | 543/750 [00:26<00:09, 21.91it/s]

 73%|███████▎  | 546/750 [00:26<00:09, 21.57it/s]

 73%|███████▎  | 549/750 [00:26<00:09, 21.72it/s]

 74%|███████▎  | 552/750 [00:26<00:09, 21.87it/s]

 74%|███████▍  | 555/750 [00:26<00:08, 22.02it/s]

 74%|███████▍  | 558/750 [00:26<00:08, 22.33it/s]

 75%|███████▍  | 561/750 [00:27<00:08, 22.30it/s]

 75%|███████▌  | 564/750 [00:27<00:08, 22.00it/s]

 76%|███████▌  | 567/750 [00:27<00:08, 22.22it/s]

 76%|███████▌  | 570/750 [00:27<00:08, 22.37it/s]

 76%|███████▋  | 573/750 [00:27<00:08, 21.37it/s]

 77%|███████▋  | 576/750 [00:27<00:08, 21.57it/s]

 77%|███████▋  | 579/750 [00:27<00:07, 21.48it/s]

 78%|███████▊  | 582/750 [00:27<00:07, 21.75it/s]

 78%|███████▊  | 585/750 [00:28<00:07, 21.79it/s]

 78%|███████▊  | 588/750 [00:28<00:07, 21.68it/s]

 79%|███████▉  | 591/750 [00:28<00:07, 22.13it/s]

 79%|███████▉  | 594/750 [00:28<00:07, 22.16it/s]

 80%|███████▉  | 597/750 [00:28<00:06, 22.23it/s]

 80%|████████  | 600/750 [00:28<00:06, 21.69it/s]

 80%|████████  | 603/750 [00:28<00:06, 21.90it/s]

 81%|████████  | 606/750 [00:29<00:06, 21.85it/s]

 81%|████████  | 609/750 [00:29<00:06, 22.01it/s]

 82%|████████▏ | 612/750 [00:29<00:06, 22.37it/s]

 82%|████████▏ | 615/750 [00:29<00:05, 22.53it/s]

 82%|████████▏ | 618/750 [00:29<00:05, 22.23it/s]

 83%|████████▎ | 621/750 [00:29<00:05, 22.43it/s]

 83%|████████▎ | 624/750 [00:29<00:05, 22.27it/s]

 84%|████████▎ | 627/750 [00:30<00:05, 21.82it/s]

 84%|████████▍ | 630/750 [00:30<00:05, 21.89it/s]

 84%|████████▍ | 633/750 [00:30<00:05, 21.84it/s]

 85%|████████▍ | 636/750 [00:30<00:05, 22.00it/s]

 85%|████████▌ | 639/750 [00:30<00:05, 22.02it/s]

 86%|████████▌ | 642/750 [00:30<00:04, 21.94it/s]

 86%|████████▌ | 645/750 [00:30<00:04, 21.97it/s]

 86%|████████▋ | 648/750 [00:30<00:04, 22.29it/s]

 87%|████████▋ | 651/750 [00:31<00:04, 22.57it/s]

 87%|████████▋ | 654/750 [00:31<00:04, 22.67it/s]

 88%|████████▊ | 657/750 [00:31<00:04, 22.90it/s]

 88%|████████▊ | 660/750 [00:31<00:03, 22.95it/s]

 88%|████████▊ | 663/750 [00:31<00:04, 21.32it/s]

 89%|████████▉ | 666/750 [00:31<00:03, 21.22it/s]

 89%|████████▉ | 669/750 [00:31<00:03, 21.65it/s]

 90%|████████▉ | 672/750 [00:32<00:03, 21.26it/s]

 90%|█████████ | 675/750 [00:32<00:03, 21.66it/s]

 90%|█████████ | 678/750 [00:32<00:03, 21.45it/s]

 91%|█████████ | 681/750 [00:32<00:03, 21.77it/s]

 91%|█████████ | 684/750 [00:32<00:03, 21.76it/s]

 92%|█████████▏| 687/750 [00:32<00:02, 22.19it/s]

 92%|█████████▏| 690/750 [00:32<00:02, 22.00it/s]

 92%|█████████▏| 693/750 [00:33<00:02, 22.31it/s]

 93%|█████████▎| 696/750 [00:33<00:02, 21.47it/s]

 93%|█████████▎| 699/750 [00:33<00:02, 21.88it/s]

 94%|█████████▎| 702/750 [00:33<00:02, 22.18it/s]

 94%|█████████▍| 705/750 [00:33<00:02, 22.44it/s]

 94%|█████████▍| 708/750 [00:33<00:01, 22.53it/s]

 95%|█████████▍| 711/750 [00:33<00:01, 21.66it/s]

 95%|█████████▌| 714/750 [00:33<00:01, 21.78it/s]

 96%|█████████▌| 717/750 [00:34<00:01, 22.05it/s]

 96%|█████████▌| 720/750 [00:34<00:01, 22.05it/s]

 96%|█████████▋| 723/750 [00:34<00:01, 22.01it/s]

 97%|█████████▋| 726/750 [00:34<00:01, 22.22it/s]

 97%|█████████▋| 729/750 [00:34<00:00, 22.32it/s]

 98%|█████████▊| 732/750 [00:34<00:00, 22.04it/s]

 98%|█████████▊| 735/750 [00:34<00:00, 22.34it/s]

 98%|█████████▊| 738/750 [00:35<00:00, 22.61it/s]

 99%|█████████▉| 741/750 [00:35<00:00, 22.29it/s]

 99%|█████████▉| 744/750 [00:35<00:00, 22.47it/s]

100%|█████████▉| 747/750 [00:35<00:00, 22.50it/s]

100%|██████████| 750/750 [00:35<00:00, 22.51it/s]

100%|██████████| 750/750 [00:35<00:00, 21.08it/s]

Saved: D:\hoiancomputervision\ticket_suspicion_project\outputs\tracks\tracks.csv
Rows: 45445

,camera_id,sequence_name,frame_id,timestamp_sec,image_path,local_track_id,confidence,x1,y1,x2,y2
0,MOT17-02-FRCNN,MOT17-02-FRCNN,1,0.0,D:\hoiancomputervision\ticket_suspicion_projec...,1,0.849230,1337.596191,418.733643,1499.459595,785.622070
1,MOT17-02-FRCNN,MOT17-02-FRCNN,1,0.0,D:\hoiancomputervision\ticket_suspicion_projec...,2,0.836228,583.730347,447.518890,674.571960,708.177368
2,MOT17-02-FRCNN,MOT17-02-FRCNN,1,0.0,D:\hoiancomputervision\ticket_suspicion_projec...,3,0.769477,1457.200195,434.877197,1595.463135,762.812866
3,MOT17-02-FRCNN,MOT17-02-FRCNN,1,0.0,D:\hoiancomputervision\ticket_suspicion_projec...,4,0.736684,439.472473,445.419098,550.020020,719.356812
4,MOT17-02-FRCNN,MOT17-02-FRCNN,1,0.0,D:\hoiancomputervision\ticket_suspicion_projec...,5,0.542474,732.278381,458.517822,769.481384,571.080322

# Visualization tracking

In [5]:
# Tạo ảnh minh họa bounding box và ID track để kiểm tra chất lượng tracking.
vis_dir = PROJECT_ROOT / "outputs/visualizations/tracking"
vis_dir.mkdir(parents=True, exist_ok=True)

sample_frames = sorted(tracks_df["frame_id"].unique())[::100][:10]

for fid in sample_frames:
    frame_rows = tracks_df[tracks_df["frame_id"] == fid]

    if len(frame_rows) == 0:
        continue

    img_path = frame_rows.iloc[0]["image_path"]
    frame = cv2.imread(img_path)

    for _, row in frame_rows.iterrows():
        x1, y1, x2, y2 = map(int, [row.x1, row.y1, row.x2, row.y2])
        tid = int(row.local_track_id)

        cv2.rectangle(frame, (x1, y1), (x2, y2), (0, 255, 0), 2)
        cv2.putText(
            frame,
            f"ID {tid}",
            (x1, max(0, y1 - 5)),
            cv2.FONT_HERSHEY_SIMPLEX,
            0.6,
            (0, 255, 0),
            2
        )

    save_path = vis_dir / f"tracking_frame_{fid:06d}.jpg"
    cv2.imwrite(str(save_path), frame)

print("Saved visualization to:", vis_dir)

Saved visualization to: D:\hoiancomputervision\ticket_suspicion_project\outputs\visualizations\tracking

# Some check

In [6]:
# Cell này thực hiện một bước cụ thể trong luồng pipeline, có thể là nạp dữ liệu, xử lý, hoặc lưu kết quả.
from pathlib import Path
import pandas as pd

PROJECT_ROOT = Path.cwd()
if PROJECT_ROOT.name == "notebooks":
    PROJECT_ROOT = PROJECT_ROOT.parent

candidate_files = list((PROJECT_ROOT / "outputs").rglob("*track*.csv"))

print("Track files found:")
for p in candidate_files:
    print(p)

for p in candidate_files:
    try:
        df = pd.read_csv(p)
        print("\nFILE:", p)
        print("Rows:", len(df))
        print("Columns:", list(df.columns))
        print(df.head())
    except Exception as e:
        print("Cannot read:", p, e)

Track files found:
D:\hoiancomputervision\ticket_suspicion_project\outputs\tracks\tracks.csv

FILE: D:\hoiancomputervision\ticket_suspicion_project\outputs\tracks\tracks.csv
Rows: 45445
Columns: ['camera_id', 'sequence_name', 'frame_id', 'timestamp_sec', 'image_path', 'local_track_id', 'confidence', 'x1', 'y1', 'x2', 'y2']
        camera_id   sequence_name  frame_id  timestamp_sec  \
0  MOT17-02-FRCNN  MOT17-02-FRCNN         1            0.0
1  MOT17-02-FRCNN  MOT17-02-FRCNN         1            0.0
2  MOT17-02-FRCNN  MOT17-02-FRCNN         1            0.0
3  MOT17-02-FRCNN  MOT17-02-FRCNN         1            0.0
4  MOT17-02-FRCNN  MOT17-02-FRCNN         1            0.0

                                          image_path  local_track_id  \
0  D:\hoiancomputervision\ticket_suspicion_projec...               1
1  D:\hoiancomputervision\ticket_suspicion_projec...               2
2  D:\hoiancomputervision\ticket_suspicion_projec...               3
3  D:\hoiancomputervision\ticket_suspicion_projec...               4
4  D:\hoiancomputervision\ticket_suspicion_projec...               5

   confidence           x1          y1           x2          y2
0    0.849230  1337.596191  418.733643  1499.459595  785.622070
1    0.836228   583.730347  447.518890   674.571960  708.177368
2    0.769477  1457.200195  434.877197  1595.463135  762.812866
3    0.736684   439.472473  445.419098   550.020020  719.356812
4    0.542474   732.278381  458.517822   769.481384  571.080322