# Setup

In [1]:
# Tìm thư mục gốc của dự án để notebook biết nơi chứa mã nguồn và dữ liệu.
from pathlib import Path
import sys
import cv2
import pandas as pd
import numpy as np
from tqdm import tqdm

def find_project_root(max_up=6):
    p = Path.cwd()
    for _ in range(max_up + 1):
        if (p / "src").exists() and (p / "configs").exists():
            return p
        if p.parent == p:
            break
        p = p.parent
    return Path.cwd()

PROJECT_ROOT = find_project_root()

sys.path.append(str(PROJECT_ROOT))

from src.config import load_yaml
from src.io_utils import save_csv

pipeline_cfg = load_yaml(PROJECT_ROOT / "configs/pipeline_config.yaml")
tracklet_cfg = pipeline_cfg["tracklet"]

tracks_df = pd.read_csv(PROJECT_ROOT / "outputs/tracks/tracks.csv")

tracks_df.head()

,camera_id,sequence_name,frame_id,timestamp_sec,image_path,local_track_id,confidence,x1,y1,x2,y2
0,MOT17-02-FRCNN,MOT17-02-FRCNN,1,0.0,D:\hoiancomputervision\ticket_suspicion_projec...,1,0.849230,1337.596191,418.733643,1499.459595,785.622070
1,MOT17-02-FRCNN,MOT17-02-FRCNN,1,0.0,D:\hoiancomputervision\ticket_suspicion_projec...,2,0.836228,583.730347,447.518890,674.571960,708.177368
2,MOT17-02-FRCNN,MOT17-02-FRCNN,1,0.0,D:\hoiancomputervision\ticket_suspicion_projec...,3,0.769477,1457.200195,434.877197,1595.463135,762.812866
3,MOT17-02-FRCNN,MOT17-02-FRCNN,1,0.0,D:\hoiancomputervision\ticket_suspicion_projec...,4,0.736684,439.472473,445.419098,550.020020,719.356812
4,MOT17-02-FRCNN,MOT17-02-FRCNN,1,0.0,D:\hoiancomputervision\ticket_suspicion_projec...,5,0.542474,732.278381,458.517822,769.481384,571.080322

# Tạo tracklet summary

In [2]:
# Gom các detections liên tiếp của cùng một track thành tracklet và đánh giá chất lượng.
tracklet_rows = []

for (camera_id, track_id), group in tracks_df.groupby(["camera_id", "local_track_id"]):
    group = group.sort_values("frame_id")

    num_frames = len(group)
    start_frame = int(group["frame_id"].min())
    end_frame = int(group["frame_id"].max())
    start_time = float(group["timestamp_sec"].min())
    end_time = float(group["timestamp_sec"].max())
    duration = end_time - start_time

    avg_conf = float(group["confidence"].mean())
    avg_height = float((group["y2"] - group["y1"]).mean())
    avg_area = float(((group["x2"] - group["x1"]) * (group["y2"] - group["y1"])).mean())

    valid = (
        num_frames >= tracklet_cfg["min_frames"] and
        duration >= tracklet_cfg["min_duration_sec"] and
        avg_height >= tracklet_cfg["min_bbox_height"]
    )

    quality_score = min(1.0, avg_conf * 0.7 + min(avg_height / 200.0, 1.0) * 0.3)

    tracklet_rows.append({
        "camera_id": camera_id,
        "local_track_id": int(track_id),
        "start_frame": start_frame,
        "end_frame": end_frame,
        "start_time": start_time,
        "end_time": end_time,
        "duration_sec": duration,
        "num_frames": num_frames,
        "avg_confidence": avg_conf,
        "avg_bbox_height": avg_height,
        "avg_bbox_area": avg_area,
        "quality_score": quality_score,
        "valid": bool(valid)
    })

tracklets_df = pd.DataFrame(tracklet_rows)

out_path = PROJECT_ROOT / "outputs/tracklets/tracklets_summary.csv"
save_csv(tracklets_df, out_path)

print("Saved:", out_path)
tracklets_df.head()

Saved: D:\hoiancomputervision\ticket_suspicion_project\outputs\tracklets\tracklets_summary.csv

,camera_id,local_track_id,start_frame,end_frame,start_time,end_time,duration_sec,num_frames,avg_confidence,avg_bbox_height,avg_bbox_area,quality_score,valid
0,MOT17-02-FRCNN,1,1,57,0.0,1.866667,1.866667,57,0.780298,432.057656,76171.929359,0.846209,True
1,MOT17-02-FRCNN,2,1,244,0.0,8.100000,8.100000,244,0.800671,323.433317,36021.349130,0.860470,True
2,MOT17-02-FRCNN,3,1,43,0.0,1.400000,1.400000,43,0.709899,370.227860,50630.794241,0.796929,True
3,MOT17-02-FRCNN,4,1,440,0.0,14.633333,14.633333,440,0.776293,501.857367,93657.552456,0.843405,True
4,MOT17-02-FRCNN,5,1,34,0.0,1.100000,1.100000,34,0.479171,111.872150,4341.925721,0.503228,True

# Hàm crop quality

In [3]:
# Định nghĩa hàm kiểm tra chất lượng crop và cắt vùng ảnh an toàn từ bounding box.
def compute_sharpness(image):
    if image is None or image.size == 0:
        return 0.0

    gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
    return cv2.Laplacian(gray, cv2.CV_64F).var()


def safe_crop(frame, x1, y1, x2, y2):
    h, w = frame.shape[:2]

    x1 = max(0, min(int(x1), w - 1))
    x2 = max(0, min(int(x2), w - 1))
    y1 = max(0, min(int(y1), h - 1))
    y2 = max(0, min(int(y2), h - 1))

    if x2 <= x1 or y2 <= y1:
        return None

    return frame[y1:y2, x1:x2]


def crop_quality(row, frame):
    crop = safe_crop(frame, row.x1, row.y1, row.x2, row.y2)

    if crop is None:
        return 0.0, None

    h, w = frame.shape[:2]
    bbox_area = max(0, row.x2 - row.x1) * max(0, row.y2 - row.y1)
    norm_area = bbox_area / (w * h)

    sharpness = compute_sharpness(crop)

    score = float(row.confidence) + 2.0 * norm_area + 0.0001 * sharpness

    return float(score), crop

# Chọn top-K representative crops

In [4]:
# Chọn crop chất lượng cao nhất cho mỗi tracklet, dùng để trích embedding và đối chiếu.
crop_root = PROJECT_ROOT / "outputs/crops"
crop_root.mkdir(parents=True, exist_ok=True)

top_k = tracklet_cfg["top_k_crops"]
representative_rows = []

valid_tracklets = tracklets_df[tracklets_df["valid"] == True]

for _, trow in tqdm(valid_tracklets.iterrows(), total=len(valid_tracklets)):
    camera_id = trow["camera_id"]
    track_id = int(trow["local_track_id"])

    group = tracks_df[
        (tracks_df["camera_id"] == camera_id) &
        (tracks_df["local_track_id"] == track_id)
    ].copy()

    candidates = []

    for _, row in group.iterrows():
        frame = cv2.imread(row["image_path"])

        if frame is None:
            continue

        score, crop = crop_quality(row, frame)

        if crop is None or crop.size == 0:
            continue

        candidates.append((score, row, crop))

    candidates = sorted(candidates, key=lambda x: x[0], reverse=True)[:top_k]

    save_dir = crop_root / camera_id / f"track_{track_id}"
    save_dir.mkdir(parents=True, exist_ok=True)

    for rank, (score, row, crop) in enumerate(candidates):
        crop_path = save_dir / f"rank_{rank + 1}_frame_{int(row.frame_id)}.jpg"
        cv2.imwrite(str(crop_path), crop)

        representative_rows.append({
            "camera_id": camera_id,
            "local_track_id": track_id,
            "frame_id": int(row.frame_id),
            "timestamp_sec": float(row.timestamp_sec),
            "crop_path": str(crop_path),
            "quality_score": float(score),
            "confidence": float(row.confidence)
        })

rep_df = pd.DataFrame(representative_rows)

out_path = PROJECT_ROOT / "outputs/crops/representative_crops.csv"
save_csv(rep_df, out_path)

print("Saved:", out_path)
rep_df.head()

  0%|          | 0/364 [00:00<?, ?it/s]

  0%|          | 1/364 [00:00<04:38,  1.31it/s]

  1%|          | 2/364 [00:03<11:47,  1.95s/it]

  1%|          | 3/364 [00:03<07:34,  1.26s/it]

  1%|          | 4/364 [00:08<14:26,  2.41s/it]

  1%|▏         | 5/364 [00:08<09:47,  1.64s/it]

  2%|▏         | 6/364 [00:09<08:48,  1.48s/it]

  2%|▏         | 7/364 [00:09<06:31,  1.10s/it]

  2%|▏         | 8/364 [00:12<08:28,  1.43s/it]

  2%|▏         | 9/364 [00:12<06:00,  1.02s/it]

  3%|▎         | 10/364 [00:12<04:21,  1.35it/s]

  3%|▎         | 11/364 [00:12<04:02,  1.45it/s]

  3%|▎         | 12/364 [00:13<03:27,  1.70it/s]

  4%|▎         | 13/364 [00:13<02:44,  2.13it/s]

  4%|▍         | 14/364 [00:14<03:49,  1.52it/s]

  4%|▍         | 15/364 [00:15<03:55,  1.48it/s]

  4%|▍         | 16/364 [00:15<03:59,  1.45it/s]

  5%|▍         | 17/364 [00:17<05:32,  1.04it/s]

  5%|▍         | 18/364 [00:17<04:20,  1.33it/s]

  5%|▌         | 19/364 [00:18<03:38,  1.58it/s]

  5%|▌         | 20/364 [00:19<04:53,  1.17it/s]

  6%|▌         | 21/364 [00:20<04:41,  1.22it/s]

  6%|▌         | 22/364 [00:20<03:39,  1.56it/s]

  6%|▋         | 23/364 [00:21<03:44,  1.52it/s]

  7%|▋         | 24/364 [00:21<02:49,  2.01it/s]

  7%|▋         | 25/364 [00:21<02:11,  2.57it/s]

  7%|▋         | 26/364 [00:23<05:11,  1.09it/s]

  7%|▋         | 27/364 [00:25<06:16,  1.12s/it]

  8%|▊         | 28/364 [00:25<04:50,  1.16it/s]

  8%|▊         | 29/364 [00:25<03:41,  1.51it/s]

  8%|▊         | 30/364 [00:26<04:09,  1.34it/s]

  9%|▊         | 31/364 [00:27<03:45,  1.48it/s]

  9%|▉         | 32/364 [00:27<03:36,  1.53it/s]

  9%|▉         | 33/364 [00:27<02:42,  2.04it/s]

  9%|▉         | 34/364 [00:28<03:48,  1.44it/s]

 10%|▉         | 36/364 [00:29<02:57,  1.85it/s]

 10%|█         | 37/364 [00:30<02:49,  1.93it/s]

 10%|█         | 38/364 [00:30<02:29,  2.18it/s]

 11%|█         | 39/364 [00:31<02:57,  1.83it/s]

 11%|█         | 40/364 [00:31<02:52,  1.87it/s]

 11%|█▏        | 41/364 [00:32<02:50,  1.90it/s]

 12%|█▏        | 42/364 [00:32<03:05,  1.74it/s]

 12%|█▏        | 43/364 [00:33<03:04,  1.74it/s]

 12%|█▏        | 44/364 [00:39<11:06,  2.08s/it]

 12%|█▏        | 45/364 [00:42<12:31,  2.35s/it]

 13%|█▎        | 46/364 [00:47<16:43,  3.15s/it]

 13%|█▎        | 47/364 [00:57<28:15,  5.35s/it]

 13%|█▎        | 48/364 [01:02<26:55,  5.11s/it]

 13%|█▎        | 49/364 [01:10<31:53,  6.08s/it]

 14%|█▎        | 50/364 [01:11<23:33,  4.50s/it]

 14%|█▍        | 51/364 [01:12<17:26,  3.34s/it]

 14%|█▍        | 52/364 [01:19<24:02,  4.62s/it]

 15%|█▍        | 53/364 [01:20<17:49,  3.44s/it]

 15%|█▍        | 54/364 [01:20<12:53,  2.49s/it]

 15%|█▌        | 55/364 [01:21<09:33,  1.86s/it]

 15%|█▌        | 56/364 [01:26<14:49,  2.89s/it]

 16%|█▌        | 57/364 [01:27<12:49,  2.51s/it]

 16%|█▌        | 58/364 [01:30<13:00,  2.55s/it]

 16%|█▌        | 59/364 [01:35<16:06,  3.17s/it]

 16%|█▋        | 60/364 [01:36<13:16,  2.62s/it]

 17%|█▋        | 61/364 [01:37<11:21,  2.25s/it]

 17%|█▋        | 62/364 [01:42<14:17,  2.84s/it]

 17%|█▋        | 63/364 [01:42<10:55,  2.18s/it]

 18%|█▊        | 64/364 [01:46<12:42,  2.54s/it]

 18%|█▊        | 65/364 [01:46<09:33,  1.92s/it]

 18%|█▊        | 66/364 [01:47<07:52,  1.59s/it]

 18%|█▊        | 67/364 [01:47<06:07,  1.24s/it]

 19%|█▊        | 68/364 [01:51<09:31,  1.93s/it]

 19%|█▉        | 69/364 [01:52<07:54,  1.61s/it]

 19%|█▉        | 70/364 [01:53<07:41,  1.57s/it]

 20%|█▉        | 71/364 [01:56<08:45,  1.79s/it]

 20%|█▉        | 72/364 [01:56<06:23,  1.31s/it]

 20%|██        | 73/364 [01:56<04:54,  1.01s/it]

 20%|██        | 74/364 [01:59<07:36,  1.57s/it]

 21%|██        | 75/364 [02:00<06:20,  1.32s/it]

 21%|██        | 76/364 [02:00<04:51,  1.01s/it]

 21%|██        | 77/364 [02:01<05:05,  1.07s/it]

 21%|██▏       | 78/364 [02:06<10:25,  2.19s/it]

 22%|██▏       | 79/364 [02:07<08:19,  1.75s/it]

 22%|██▏       | 80/364 [02:07<06:49,  1.44s/it]

 22%|██▏       | 81/364 [02:09<06:31,  1.38s/it]

 23%|██▎       | 82/364 [02:09<05:21,  1.14s/it]

 23%|██▎       | 83/364 [02:10<04:10,  1.12it/s]

 23%|██▎       | 84/364 [02:10<03:20,  1.40it/s]

 23%|██▎       | 85/364 [02:12<05:25,  1.17s/it]

 24%|██▎       | 86/364 [02:13<04:34,  1.01it/s]

 24%|██▍       | 87/364 [02:13<03:38,  1.27it/s]

 24%|██▍       | 88/364 [02:14<03:30,  1.31it/s]

 24%|██▍       | 89/364 [02:14<02:49,  1.62it/s]

 25%|██▍       | 90/364 [02:14<02:26,  1.87it/s]

 25%|██▌       | 91/364 [02:18<07:07,  1.56s/it]

 25%|██▌       | 92/364 [02:19<05:42,  1.26s/it]

 26%|██▌       | 93/364 [02:21<06:59,  1.55s/it]

 26%|██▌       | 94/364 [02:22<06:27,  1.44s/it]

 26%|██▌       | 95/364 [02:23<04:58,  1.11s/it]

 26%|██▋       | 96/364 [02:24<06:01,  1.35s/it]

 27%|██▋       | 97/364 [02:25<04:56,  1.11s/it]

 27%|██▋       | 98/364 [02:26<04:28,  1.01s/it]

 27%|██▋       | 99/364 [02:29<07:09,  1.62s/it]

 27%|██▋       | 100/364 [02:30<06:49,  1.55s/it]

 28%|██▊       | 101/364 [02:33<08:39,  1.98s/it]

 28%|██▊       | 102/364 [02:36<09:47,  2.24s/it]

 28%|██▊       | 103/364 [02:39<10:25,  2.39s/it]

 29%|██▊       | 104/364 [02:39<07:25,  1.71s/it]

 29%|██▉       | 105/364 [02:39<05:38,  1.31s/it]

 29%|██▉       | 107/364 [02:40<03:40,  1.16it/s]

 30%|██▉       | 108/364 [02:41<03:36,  1.18it/s]

 30%|███       | 110/364 [02:42<03:23,  1.25it/s]

 30%|███       | 111/364 [02:44<04:10,  1.01it/s]

 31%|███       | 112/364 [02:45<03:52,  1.08it/s]

 31%|███       | 113/364 [02:46<04:26,  1.06s/it]

 31%|███▏      | 114/364 [02:46<03:20,  1.24it/s]

 32%|███▏      | 115/364 [02:47<03:53,  1.07it/s]

 32%|███▏      | 116/364 [02:49<04:18,  1.04s/it]

 32%|███▏      | 117/364 [02:50<04:02,  1.02it/s]

 32%|███▏      | 118/364 [02:51<04:14,  1.04s/it]

 33%|███▎      | 119/364 [02:51<03:30,  1.16it/s]

 33%|███▎      | 120/364 [02:52<03:23,  1.20it/s]

 33%|███▎      | 121/364 [02:52<02:46,  1.46it/s]

 34%|███▎      | 122/364 [02:54<03:59,  1.01it/s]

 34%|███▍      | 123/364 [02:54<03:19,  1.21it/s]

 34%|███▍      | 125/364 [02:55<02:07,  1.88it/s]

 35%|███▍      | 126/364 [02:55<01:44,  2.28it/s]

 35%|███▌      | 129/364 [02:55<00:54,  4.33it/s]

 36%|███▌      | 131/364 [02:55<00:40,  5.74it/s]

 37%|███▋      | 134/364 [02:55<00:29,  7.85it/s]

 38%|███▊      | 137/364 [02:56<00:32,  6.95it/s]

 38%|███▊      | 139/364 [02:56<00:28,  7.92it/s]

 39%|███▉      | 143/364 [02:56<00:19, 11.40it/s]

 40%|████      | 146/364 [02:56<00:15, 13.64it/s]

 41%|████      | 148/364 [02:57<00:26,  8.14it/s]

 41%|████▏     | 151/364 [02:57<00:21,  9.88it/s]

 42%|████▏     | 153/364 [02:57<00:25,  8.42it/s]

 43%|████▎     | 155/364 [02:58<00:33,  6.23it/s]

 43%|████▎     | 157/364 [02:58<00:28,  7.17it/s]

 44%|████▎     | 159/364 [02:58<00:24,  8.38it/s]

 44%|████▍     | 161/364 [03:00<01:00,  3.33it/s]

 45%|████▌     | 164/364 [03:00<00:40,  4.89it/s]

 46%|████▌     | 167/364 [03:00<00:28,  6.80it/s]

 46%|████▋     | 169/364 [03:00<00:31,  6.09it/s]

 47%|████▋     | 171/364 [03:01<00:26,  7.17it/s]

 48%|████▊     | 173/364 [03:01<00:27,  7.03it/s]

 48%|████▊     | 176/364 [03:01<00:19,  9.70it/s]

 49%|████▉     | 180/364 [03:01<00:13, 13.84it/s]

 51%|█████     | 184/364 [03:01<00:10, 17.18it/s]

 51%|█████▏    | 187/364 [03:01<00:10, 16.98it/s]

 52%|█████▏    | 190/364 [03:02<00:09, 18.80it/s]

 53%|█████▎    | 193/364 [03:02<00:08, 20.04it/s]

 54%|█████▍    | 196/364 [03:03<00:26,  6.34it/s]

 54%|█████▍    | 198/364 [03:05<00:53,  3.08it/s]

 55%|█████▍    | 200/364 [03:09<01:59,  1.37it/s]

 55%|█████▌    | 201/364 [03:10<02:17,  1.19it/s]

 55%|█████▌    | 202/364 [03:10<01:55,  1.40it/s]

 56%|█████▌    | 203/364 [03:12<02:25,  1.11it/s]

 56%|█████▌    | 204/364 [03:13<02:40,  1.00s/it]

 56%|█████▋    | 205/364 [03:15<03:09,  1.19s/it]

 57%|█████▋    | 206/364 [03:16<02:45,  1.05s/it]

 57%|█████▋    | 207/364 [03:17<02:32,  1.03it/s]

 57%|█████▋    | 208/364 [03:17<02:03,  1.27it/s]

 57%|█████▋    | 209/364 [03:18<02:11,  1.18it/s]

 58%|█████▊    | 210/364 [03:19<02:04,  1.23it/s]

 58%|█████▊    | 211/364 [03:19<01:35,  1.60it/s]

 58%|█████▊    | 212/364 [03:19<01:14,  2.04it/s]

 59%|█████▊    | 213/364 [03:21<02:06,  1.20it/s]

 59%|█████▉    | 214/364 [03:21<01:44,  1.43it/s]

 59%|█████▉    | 215/364 [03:23<02:37,  1.06s/it]

 59%|█████▉    | 216/364 [03:24<02:16,  1.08it/s]

 60%|█████▉    | 217/364 [03:25<02:26,  1.00it/s]

 60%|█████▉    | 218/364 [03:25<01:59,  1.22it/s]

 60%|██████    | 219/364 [03:26<02:12,  1.10it/s]

 60%|██████    | 220/364 [03:27<01:48,  1.32it/s]

 61%|██████    | 221/364 [03:28<01:52,  1.28it/s]

 61%|██████    | 222/364 [03:28<01:28,  1.61it/s]

 61%|██████▏   | 223/364 [03:29<01:33,  1.51it/s]

 62%|██████▏   | 224/364 [03:29<01:21,  1.72it/s]

 62%|██████▏   | 225/364 [03:29<01:04,  2.16it/s]

 62%|██████▏   | 226/364 [03:30<01:05,  2.12it/s]

 62%|██████▏   | 227/364 [03:30<01:01,  2.22it/s]

 63%|██████▎   | 228/364 [03:30<00:54,  2.49it/s]

 63%|██████▎   | 229/364 [03:31<00:51,  2.61it/s]

 63%|██████▎   | 230/364 [03:33<02:24,  1.08s/it]

 63%|██████▎   | 231/364 [03:34<01:51,  1.19it/s]

 64%|██████▎   | 232/364 [03:34<01:28,  1.49it/s]

 64%|██████▍   | 233/364 [03:34<01:17,  1.70it/s]

 64%|██████▍   | 234/364 [03:35<01:06,  1.97it/s]

 65%|██████▍   | 235/364 [03:35<01:05,  1.98it/s]

 65%|██████▍   | 236/364 [03:35<00:54,  2.33it/s]

 65%|██████▌   | 237/364 [03:36<00:46,  2.74it/s]

 65%|██████▌   | 238/364 [03:36<00:44,  2.80it/s]

 66%|██████▌   | 239/364 [03:36<00:38,  3.28it/s]

 66%|██████▌   | 240/364 [03:39<02:09,  1.05s/it]

 66%|██████▌   | 241/364 [03:40<01:57,  1.05it/s]

 66%|██████▋   | 242/364 [03:40<01:43,  1.18it/s]

 67%|██████▋   | 243/364 [03:41<01:25,  1.42it/s]

 67%|██████▋   | 244/364 [03:41<01:08,  1.76it/s]

 67%|██████▋   | 245/364 [03:41<00:53,  2.21it/s]

 68%|██████▊   | 246/364 [03:41<00:46,  2.54it/s]

 68%|██████▊   | 247/364 [03:42<00:48,  2.43it/s]

 68%|██████▊   | 248/364 [03:42<00:40,  2.84it/s]

 68%|██████▊   | 249/364 [03:43<00:59,  1.92it/s]

 69%|██████▊   | 250/364 [03:44<01:17,  1.48it/s]

 69%|██████▉   | 251/364 [03:44<01:08,  1.64it/s]

 69%|██████▉   | 252/364 [03:45<01:26,  1.29it/s]

 70%|██████▉   | 253/364 [03:46<01:04,  1.73it/s]

 70%|██████▉   | 254/364 [03:46<00:53,  2.07it/s]

 70%|███████   | 255/364 [03:47<01:06,  1.63it/s]

 70%|███████   | 256/364 [03:49<01:52,  1.05s/it]

 71%|███████   | 257/364 [03:49<01:27,  1.23it/s]

 71%|███████   | 258/364 [03:50<01:44,  1.02it/s]

 71%|███████   | 259/364 [03:51<01:21,  1.29it/s]

 71%|███████▏  | 260/364 [03:51<01:03,  1.63it/s]

 72%|███████▏  | 261/364 [03:53<01:43,  1.00s/it]

 72%|███████▏  | 262/364 [03:53<01:22,  1.24it/s]

 72%|███████▏  | 263/364 [03:54<01:28,  1.14it/s]

 73%|███████▎  | 264/364 [03:55<01:08,  1.45it/s]

 73%|███████▎  | 265/364 [03:56<01:23,  1.19it/s]

 73%|███████▎  | 266/364 [03:56<01:18,  1.25it/s]

 73%|███████▎  | 267/364 [03:57<01:03,  1.52it/s]

 74%|███████▎  | 268/364 [03:57<01:03,  1.52it/s]

 74%|███████▍  | 270/364 [03:58<00:44,  2.10it/s]

 74%|███████▍  | 271/364 [03:58<00:38,  2.43it/s]

 75%|███████▍  | 272/364 [03:59<00:37,  2.48it/s]

 75%|███████▌  | 273/364 [03:59<00:29,  3.06it/s]

 75%|███████▌  | 274/364 [03:59<00:33,  2.69it/s]

 76%|███████▌  | 275/364 [04:04<02:14,  1.52s/it]

 76%|███████▌  | 276/364 [04:04<01:52,  1.28s/it]

 76%|███████▌  | 277/364 [04:04<01:24,  1.02it/s]

 76%|███████▋  | 278/364 [04:06<01:49,  1.27s/it]

 77%|███████▋  | 279/364 [04:07<01:21,  1.04it/s]

 77%|███████▋  | 280/364 [04:07<01:03,  1.33it/s]

 77%|███████▋  | 281/364 [04:08<01:02,  1.33it/s]

 77%|███████▋  | 282/364 [04:08<00:47,  1.72it/s]

 78%|███████▊  | 283/364 [04:09<00:48,  1.66it/s]

 78%|███████▊  | 284/364 [04:10<01:06,  1.21it/s]

 78%|███████▊  | 285/364 [04:11<01:04,  1.23it/s]

 79%|███████▊  | 286/364 [04:11<01:00,  1.29it/s]

 79%|███████▉  | 287/364 [04:12<00:59,  1.29it/s]

 79%|███████▉  | 288/364 [04:13<00:59,  1.29it/s]

 79%|███████▉  | 289/364 [04:14<00:54,  1.39it/s]

 80%|███████▉  | 290/364 [04:14<00:39,  1.86it/s]

 80%|███████▉  | 291/364 [04:15<00:48,  1.50it/s]

 80%|████████  | 292/364 [04:16<01:14,  1.03s/it]

 80%|████████  | 293/364 [04:17<01:07,  1.05it/s]

 81%|████████  | 294/364 [04:20<01:36,  1.38s/it]

 81%|████████  | 295/364 [04:20<01:17,  1.13s/it]

 81%|████████▏ | 296/364 [04:20<01:00,  1.12it/s]

 82%|████████▏ | 297/364 [04:21<00:58,  1.14it/s]

 82%|████████▏ | 298/364 [04:22<00:45,  1.46it/s]

 82%|████████▏ | 299/364 [04:22<00:45,  1.43it/s]

 82%|████████▏ | 300/364 [04:23<00:36,  1.73it/s]

 83%|████████▎ | 301/364 [04:23<00:39,  1.60it/s]

 83%|████████▎ | 302/364 [04:24<00:31,  1.98it/s]

 83%|████████▎ | 303/364 [04:24<00:25,  2.36it/s]

 84%|████████▎ | 304/364 [04:25<00:37,  1.61it/s]

 84%|████████▍ | 305/364 [04:26<00:48,  1.22it/s]

 84%|████████▍ | 306/364 [04:27<00:46,  1.25it/s]

 84%|████████▍ | 307/364 [04:27<00:34,  1.64it/s]

 85%|████████▍ | 308/364 [04:28<00:35,  1.57it/s]

 85%|████████▍ | 309/364 [04:29<00:36,  1.49it/s]

 85%|████████▌ | 310/364 [04:29<00:35,  1.53it/s]

 85%|████████▌ | 311/364 [04:30<00:40,  1.30it/s]

 86%|████████▌ | 312/364 [04:31<00:35,  1.45it/s]

 86%|████████▌ | 313/364 [04:31<00:33,  1.52it/s]

 86%|████████▋ | 314/364 [04:32<00:33,  1.51it/s]

 87%|████████▋ | 315/364 [04:33<00:35,  1.39it/s]

 87%|████████▋ | 316/364 [04:34<00:34,  1.38it/s]

 87%|████████▋ | 317/364 [04:34<00:28,  1.64it/s]

 87%|████████▋ | 318/364 [04:35<00:28,  1.60it/s]

 88%|████████▊ | 320/364 [04:35<00:18,  2.33it/s]

 88%|████████▊ | 321/364 [04:35<00:18,  2.27it/s]

 88%|████████▊ | 322/364 [04:36<00:16,  2.59it/s]

 89%|████████▊ | 323/364 [04:36<00:14,  2.82it/s]

 89%|████████▉ | 324/364 [04:37<00:18,  2.12it/s]

 89%|████████▉ | 325/364 [04:38<00:22,  1.76it/s]

 90%|████████▉ | 326/364 [04:38<00:25,  1.49it/s]

 90%|████████▉ | 327/364 [04:39<00:23,  1.58it/s]

 90%|█████████ | 328/364 [04:39<00:20,  1.77it/s]

 90%|█████████ | 329/364 [04:40<00:15,  2.25it/s]

 91%|█████████ | 330/364 [04:40<00:12,  2.76it/s]

 91%|█████████ | 331/364 [04:40<00:12,  2.56it/s]

 91%|█████████ | 332/364 [04:40<00:11,  2.75it/s]

 91%|█████████▏| 333/364 [04:41<00:10,  2.97it/s]

 92%|█████████▏| 334/364 [04:41<00:09,  3.12it/s]

 92%|█████████▏| 335/364 [04:42<00:12,  2.37it/s]

 92%|█████████▏| 336/364 [04:43<00:22,  1.26it/s]

 93%|█████████▎| 337/364 [04:44<00:23,  1.16it/s]

 93%|█████████▎| 338/364 [04:45<00:19,  1.35it/s]

 93%|█████████▎| 339/364 [04:46<00:19,  1.32it/s]

 93%|█████████▎| 340/364 [04:46<00:13,  1.74it/s]

 94%|█████████▎| 341/364 [04:46<00:11,  1.98it/s]

 94%|█████████▍| 342/364 [04:46<00:09,  2.44it/s]

 94%|█████████▍| 343/364 [04:46<00:06,  3.10it/s]

 95%|█████████▍| 344/364 [04:47<00:06,  3.17it/s]

 95%|█████████▍| 345/364 [04:47<00:05,  3.23it/s]

 95%|█████████▌| 346/364 [04:47<00:04,  3.92it/s]

 95%|█████████▌| 347/364 [04:47<00:04,  4.19it/s]

 96%|█████████▌| 348/364 [04:48<00:04,  3.62it/s]

 96%|█████████▌| 349/364 [04:48<00:04,  3.42it/s]

 96%|█████████▌| 350/364 [04:48<00:04,  3.39it/s]

 96%|█████████▋| 351/364 [04:49<00:03,  3.56it/s]

 97%|█████████▋| 352/364 [04:49<00:03,  3.22it/s]

 97%|█████████▋| 353/364 [04:49<00:03,  3.32it/s]

 97%|█████████▋| 354/364 [04:50<00:02,  3.35it/s]

 98%|█████████▊| 355/364 [04:50<00:02,  3.40it/s]

 98%|█████████▊| 356/364 [04:50<00:02,  2.93it/s]

 98%|█████████▊| 357/364 [04:50<00:02,  3.31it/s]

 98%|█████████▊| 358/364 [04:51<00:01,  3.01it/s]

 99%|█████████▊| 359/364 [04:51<00:01,  3.13it/s]

 99%|█████████▉| 360/364 [04:52<00:01,  2.70it/s]

 99%|█████████▉| 361/364 [04:52<00:01,  2.95it/s]

 99%|█████████▉| 362/364 [04:52<00:00,  2.84it/s]

100%|█████████▉| 363/364 [04:53<00:00,  2.91it/s]

100%|██████████| 364/364 [04:53<00:00,  3.50it/s]

100%|██████████| 364/364 [04:53<00:00,  1.24it/s]

Saved: D:\hoiancomputervision\ticket_suspicion_project\outputs\crops\representative_crops.csv

,camera_id,local_track_id,frame_id,timestamp_sec,crop_path,quality_score,confidence
0,MOT17-02-FRCNN,1,44,1.433333,D:\hoiancomputervision\ticket_suspicion_projec...,0.993238,0.874075
1,MOT17-02-FRCNN,1,43,1.400000,D:\hoiancomputervision\ticket_suspicion_projec...,0.989640,0.874804
2,MOT17-02-FRCNN,1,6,0.166667,D:\hoiancomputervision\ticket_suspicion_projec...,0.983757,0.914009
3,MOT17-02-FRCNN,1,5,0.133333,D:\hoiancomputervision\ticket_suspicion_projec...,0.976241,0.909170
4,MOT17-02-FRCNN,1,7,0.200000,D:\hoiancomputervision\ticket_suspicion_projec...,0.969124,0.898346

# Some check

In [5]:
# Cell này thực hiện một bước cụ thể trong luồng pipeline, có thể là nạp dữ liệu, xử lý, hoặc lưu kết quả.
from pathlib import Path

PROJECT_ROOT = Path.cwd()
if PROJECT_ROOT.name == "notebooks":
    PROJECT_ROOT = PROJECT_ROOT.parent

crop_dirs = [
    PROJECT_ROOT / "outputs" / "crops",
    PROJECT_ROOT / "outputs" / "person_crops",
]

for crop_root in crop_dirs:
    if crop_root.exists():
        imgs = list(crop_root.rglob("*.jpg")) + list(crop_root.rglob("*.png"))
        print("Crop root:", crop_root)
        print("Number of crop images:", len(imgs))
        print("First 10 crops:")
        for p in imgs[:10]:
            print(p)

Crop root: D:\hoiancomputervision\ticket_suspicion_project\outputs\crops
Number of crop images: 1820
First 10 crops:
D:\hoiancomputervision\ticket_suspicion_project\outputs\crops\MOT17-02-FRCNN\track_1\rank_1_frame_44.jpg
D:\hoiancomputervision\ticket_suspicion_project\outputs\crops\MOT17-02-FRCNN\track_1\rank_2_frame_43.jpg
D:\hoiancomputervision\ticket_suspicion_project\outputs\crops\MOT17-02-FRCNN\track_1\rank_3_frame_6.jpg
D:\hoiancomputervision\ticket_suspicion_project\outputs\crops\MOT17-02-FRCNN\track_1\rank_4_frame_5.jpg
D:\hoiancomputervision\ticket_suspicion_project\outputs\crops\MOT17-02-FRCNN\track_1\rank_5_frame_7.jpg
D:\hoiancomputervision\ticket_suspicion_project\outputs\crops\MOT17-02-FRCNN\track_104\rank_1_frame_460.jpg
D:\hoiancomputervision\ticket_suspicion_project\outputs\crops\MOT17-02-FRCNN\track_104\rank_2_frame_454.jpg
D:\hoiancomputervision\ticket_suspicion_project\outputs\crops\MOT17-02-FRCNN\track_104\rank_3_frame_446.jpg
D:\hoiancomputervision\ticket_suspicion_project\outputs\crops\MOT17-02-FRCNN\track_104\rank_4_frame_447.jpg
D:\hoiancomputervision\ticket_suspicion_project\outputs\crops\MOT17-02-FRCNN\track_104\rank_5_frame_457.jpg