# Setup

In [1]:
# Tìm thư mục gốc của dự án để notebook biết nơi chứa mã nguồn và dữ liệu.
from pathlib import Path
import sys
import torch
import pandas as pd
import numpy as np
from tqdm import tqdm
from PIL import Image

def find_project_root(max_up=6):
    p = Path.cwd()
    for _ in range(max_up + 1):
        if (p / "src").exists() and (p / "configs").exists():
            return p
        if p.parent == p:
            break
        p = p.parent
    return Path.cwd()

PROJECT_ROOT = find_project_root()

sys.path.append(str(PROJECT_ROOT))

from src.config import load_yaml
from src.io_utils import save_csv, save_numpy

pipeline_cfg = load_yaml(PROJECT_ROOT / "configs/pipeline_config.yaml")
reid_cfg = pipeline_cfg["reid"]

device = "cuda" if torch.cuda.is_available() else "cpu"

print("Device:", device)

Device: cpu

In [2]:
# Cell này thực hiện một bước cụ thể trong luồng pipeline, có thể là nạp dữ liệu, xử lý, hoặc lưu kết quả.
# !pip install git+https://github.com/KaiyangZhou/deep-person-reid.git

In [3]:
# Cell này thực hiện một bước cụ thể trong luồng pipeline, có thể là nạp dữ liệu, xử lý, hoặc lưu kết quả.
!pip install torchreid

Requirement already satisfied: torchreid in C:\Users\DUNG\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages (0.2.5)

[notice] A new release of pip is available: 26.0.1 -> 26.1.1
[notice] To update, run: C:\Users\DUNG\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

In [4]:
# Cell này thực hiện một bước cụ thể trong luồng pipeline, có thể là nạp dữ liệu, xử lý, hoặc lưu kết quả.
import sys
print(sys.executable)
import sys
!"{sys.executable}" -m pip install tensorboard
import sys
!"{sys.executable}" -m pip install tensorboard yacs gdown

C:\Users\DUNG\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\python.exe

Requirement already satisfied: tensorboard in C:\Users\DUNG\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages (2.20.0)
Requirement already satisfied: absl-py>=0.4 in C:\Users\DUNG\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages (from tensorboard) (2.4.0)
Requirement already satisfied: grpcio>=1.48.2 in C:\Users\DUNG\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages (from tensorboard) (1.80.0)
Requirement already satisfied: markdown>=2.6.8 in C:\Users\DUNG\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages (from tensorboard) (3.10.2)
Requirement already satisfied: numpy>=1.12.0 in C:\Users\DUNG\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages (from tensorboard) (2.4.5)
Requirement already satisfied: packaging in C:\Users\DUNG\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages (from tensorboard) (26.0)
Requirement already satisfied: pillow in C:\Users\DUNG\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages (from tensorboard) (12.1.1)
Requirement already satisfied: protobuf!=4.24.0,>=3.19.6 in C:\Users\DUNG\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages (from tensorboard) (6.33.6)
Requirement already satisfied: setuptools>=41.0.0 in C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\site-packages (from tensorboard) (65.5.0)
Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in C:\Users\DUNG\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages (from tensorboard) (0.7.2)
Requirement already satisfied: werkzeug>=1.0.1 in C:\Users\DUNG\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages (from tensorboard) (3.1.8)
Requirement already satisfied: typing-extensions~=4.12 in C:\Users\DUNG\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages (from grpcio>=1.48.2->tensorboard) (4.15.0)
Requirement already satisfied: markupsafe>=2.1.1 in C:\Users\DUNG\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages (from werkzeug>=1.0.1->tensorboard) (3.0.3)

[notice] A new release of pip is available: 26.0.1 -> 26.1.1
[notice] To update, run: C:\Users\DUNG\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

Requirement already satisfied: tensorboard in C:\Users\DUNG\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages (2.20.0)
Requirement already satisfied: yacs in C:\Users\DUNG\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages (0.1.8)
Requirement already satisfied: gdown in C:\Users\DUNG\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages (6.0.0)
Requirement already satisfied: absl-py>=0.4 in C:\Users\DUNG\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages (from tensorboard) (2.4.0)
Requirement already satisfied: grpcio>=1.48.2 in C:\Users\DUNG\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages (from tensorboard) (1.80.0)
Requirement already satisfied: markdown>=2.6.8 in C:\Users\DUNG\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages (from tensorboard) (3.10.2)
Requirement already satisfied: numpy>=1.12.0 in C:\Users\DUNG\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages (from tensorboard) (2.4.5)
Requirement already satisfied: packaging in C:\Users\DUNG\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages (from tensorboard) (26.0)
Requirement already satisfied: pillow in C:\Users\DUNG\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages (from tensorboard) (12.1.1)
Requirement already satisfied: protobuf!=4.24.0,>=3.19.6 in C:\Users\DUNG\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages (from tensorboard) (6.33.6)
Requirement already satisfied: setuptools>=41.0.0 in C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\site-packages (from tensorboard) (65.5.0)
Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in C:\Users\DUNG\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages (from tensorboard) (0.7.2)
Requirement already satisfied: werkzeug>=1.0.1 in C:\Users\DUNG\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages (from tensorboard) (3.1.8)
Requirement already satisfied: PyYAML in C:\Users\DUNG\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages (from yacs) (6.0.3)
Requirement already satisfied: beautifulsoup4 in C:\Users\DUNG\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages (from gdown) (4.14.3)
Requirement already satisfied: filelock in C:\Users\DUNG\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages (from gdown) (3.20.3)
Requirement already satisfied: requests[socks] in C:\Users\DUNG\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages (from gdown) (2.32.5)
Requirement already satisfied: tqdm in C:\Users\DUNG\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages (from gdown) (4.67.3)
Requirement already satisfied: typing-extensions>=4.0 in C:\Users\DUNG\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages (from gdown) (4.15.0)
Requirement already satisfied: markupsafe>=2.1.1 in C:\Users\DUNG\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages (from werkzeug>=1.0.1->tensorboard) (3.0.3)
Requirement already satisfied: soupsieve>=1.6.1 in C:\Users\DUNG\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages (from beautifulsoup4->gdown) (2.8.3)
Requirement already satisfied: charset_normalizer<4,>=2 in C:\Users\DUNG\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages (from requests[socks]->gdown) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in C:\Users\DUNG\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages (from requests[socks]->gdown) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in C:\Users\DUNG\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages (from requests[socks]->gdown) (2.6.3)
Requirement already satisfied: certifi>=2017.4.17 in C:\Users\DUNG\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages (from requests[socks]->gdown) (2026.1.4)
Requirement already satisfied: PySocks!=1.5.7,>=1.5.6 in C:\Users\DUNG\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages (from requests[socks]->gdown) (1.7.1)
Requirement already satisfied: colorama in C:\Users\DUNG\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages (from tqdm->gdown) (0.4.6)

[notice] A new release of pip is available: 26.0.1 -> 26.1.1
[notice] To update, run: C:\Users\DUNG\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

In [5]:
# Nạp mô hình ReID để trích đặc trưng từ ảnh nhân vật, sử dụng cho việc ghép người giữa camera.
import torchreid
print("torchreid imported successfully")

C:\Users\DUNG\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\torchreid\reid\metrics\rank.py:11: UserWarning: Cython evaluation (very fast so highly recommended) is unavailable, now use python evaluation.
  warnings.warn(

torchreid imported successfully

# Load OSNet

In [6]:
# Nạp mô hình ReID để trích đặc trưng từ ảnh nhân vật, sử dụng cho việc ghép người giữa camera.
import torchreid

reid_model = torchreid.models.build_model(
    name=reid_cfg["model"],
    num_classes=1000,
    pretrained=True
)

reid_model = reid_model.to(device)
reid_model.eval()

print("Loaded Re-ID model:", reid_cfg["model"])

Successfully loaded imagenet pretrained weights from "C:\Users\DUNG/.cache\torch\checkpoints\osnet_x1_0_imagenet.pth"
Loaded Re-ID model: osnet_x1_0

# Transform ảnh

In [7]:
# Nạp mô hình ReID để trích đặc trưng từ ảnh nhân vật, sử dụng cho việc ghép người giữa camera.
from torchvision import transforms

input_h = reid_cfg["input_height"]
input_w = reid_cfg["input_width"]

transform = transforms.Compose([
    transforms.Resize((input_h, input_w)),
    transforms.ToTensor(),
    transforms.Normalize(
        mean=[0.485, 0.456, 0.406],
        std=[0.229, 0.224, 0.225]
    )
])


def extract_embedding(image_path):
    img = Image.open(image_path).convert("RGB")
    tensor = transform(img).unsqueeze(0).to(device)

    with torch.no_grad():
        feat = reid_model(tensor)
        feat = torch.nn.functional.normalize(feat, p=2, dim=1)

    return feat.cpu().numpy()[0]

# Extract crop embeddings

In [8]:
# Cell này thực hiện một bước cụ thể trong luồng pipeline, có thể là nạp dữ liệu, xử lý, hoặc lưu kết quả.
rep_df = pd.read_csv(PROJECT_ROOT / "outputs/crops/representative_crops.csv")

embedding_rows = []
embeddings = []

for idx, row in tqdm(rep_df.iterrows(), total=len(rep_df)):
    emb = extract_embedding(row["crop_path"])
    embeddings.append(emb)

    embedding_rows.append({
        "embedding_index": idx,
        "camera_id": row["camera_id"],
        "local_track_id": int(row["local_track_id"]),
        "frame_id": int(row["frame_id"]),
        "timestamp_sec": float(row["timestamp_sec"]),
        "crop_path": row["crop_path"],
        "quality_score": float(row["quality_score"])
    })

embeddings = np.vstack(embeddings)
emb_meta_df = pd.DataFrame(embedding_rows)

save_numpy(embeddings, PROJECT_ROOT / "outputs/embeddings/crop_embeddings.npy")
save_csv(emb_meta_df, PROJECT_ROOT / "outputs/embeddings/crop_embeddings_meta.csv")

print("Embeddings shape:", embeddings.shape)
emb_meta_df.head()

  0%|          | 0/1820 [00:00<?, ?it/s]

  0%|          | 1/1820 [00:00<04:16,  7.09it/s]

  0%|          | 4/1820 [00:00<01:47, 16.84it/s]

  0%|          | 7/1820 [00:00<01:27, 20.80it/s]

  1%|          | 10/1820 [00:00<01:20, 22.43it/s]

  1%|          | 13/1820 [00:00<01:16, 23.70it/s]

  1%|          | 16/1820 [00:00<01:14, 24.22it/s]

  1%|          | 19/1820 [00:00<01:13, 24.34it/s]

  1%|          | 22/1820 [00:00<01:13, 24.62it/s]

  1%|▏         | 25/1820 [00:01<01:12, 24.87it/s]

  2%|▏         | 28/1820 [00:01<01:11, 25.04it/s]

  2%|▏         | 31/1820 [00:01<01:10, 25.22it/s]

  2%|▏         | 34/1820 [00:01<01:10, 25.35it/s]

  2%|▏         | 37/1820 [00:01<01:10, 25.31it/s]

  2%|▏         | 40/1820 [00:01<01:09, 25.47it/s]

  2%|▏         | 43/1820 [00:01<01:09, 25.52it/s]

  3%|▎         | 46/1820 [00:01<01:08, 25.72it/s]

  3%|▎         | 49/1820 [00:02<01:09, 25.57it/s]

  3%|▎         | 52/1820 [00:02<01:08, 25.79it/s]

  3%|▎         | 55/1820 [00:02<01:08, 25.88it/s]

  3%|▎         | 58/1820 [00:02<01:06, 26.35it/s]

  3%|▎         | 61/1820 [00:02<01:06, 26.34it/s]

  4%|▎         | 64/1820 [00:02<01:07, 26.19it/s]

  4%|▎         | 67/1820 [00:02<01:05, 26.65it/s]

  4%|▍         | 70/1820 [00:02<01:05, 26.69it/s]

  4%|▍         | 73/1820 [00:02<01:06, 26.37it/s]

  4%|▍         | 76/1820 [00:03<01:06, 26.35it/s]

  4%|▍         | 79/1820 [00:03<01:06, 26.27it/s]

  5%|▍         | 82/1820 [00:03<01:06, 26.15it/s]

  5%|▍         | 85/1820 [00:03<01:07, 25.86it/s]

  5%|▍         | 88/1820 [00:03<01:06, 25.93it/s]

  5%|▌         | 91/1820 [00:03<01:06, 25.84it/s]

  5%|▌         | 94/1820 [00:03<01:07, 25.71it/s]

  5%|▌         | 97/1820 [00:03<01:06, 25.96it/s]

  5%|▌         | 100/1820 [00:03<01:07, 25.60it/s]

  6%|▌         | 103/1820 [00:04<01:06, 25.74it/s]

  6%|▌         | 106/1820 [00:04<01:05, 25.98it/s]

  6%|▌         | 109/1820 [00:04<01:05, 26.22it/s]

  6%|▌         | 112/1820 [00:04<01:04, 26.38it/s]

  6%|▋         | 115/1820 [00:04<01:04, 26.57it/s]

  6%|▋         | 118/1820 [00:04<01:04, 26.29it/s]

  7%|▋         | 121/1820 [00:04<01:05, 26.02it/s]

  7%|▋         | 124/1820 [00:04<01:04, 26.18it/s]

  7%|▋         | 127/1820 [00:05<01:03, 26.50it/s]

  7%|▋         | 130/1820 [00:05<01:04, 26.20it/s]

  7%|▋         | 133/1820 [00:05<01:05, 25.70it/s]

  7%|▋         | 136/1820 [00:05<01:06, 25.23it/s]

  8%|▊         | 139/1820 [00:05<01:05, 25.54it/s]

  8%|▊         | 142/1820 [00:05<01:07, 24.94it/s]

  8%|▊         | 145/1820 [00:05<01:08, 24.53it/s]

  8%|▊         | 148/1820 [00:05<01:08, 24.43it/s]

  8%|▊         | 151/1820 [00:05<01:09, 24.06it/s]

  8%|▊         | 154/1820 [00:06<01:10, 23.70it/s]

  9%|▊         | 157/1820 [00:06<01:08, 24.31it/s]

  9%|▉         | 160/1820 [00:06<01:06, 25.13it/s]

  9%|▉         | 163/1820 [00:06<01:12, 22.85it/s]

  9%|▉         | 166/1820 [00:06<01:12, 22.71it/s]

  9%|▉         | 169/1820 [00:06<01:16, 21.59it/s]

  9%|▉         | 172/1820 [00:06<01:14, 22.14it/s]

 10%|▉         | 175/1820 [00:07<01:12, 22.82it/s]

 10%|▉         | 178/1820 [00:07<01:10, 23.16it/s]

 10%|▉         | 181/1820 [00:07<01:09, 23.52it/s]

 10%|█         | 184/1820 [00:07<01:08, 24.00it/s]

 10%|█         | 187/1820 [00:07<01:06, 24.53it/s]

 10%|█         | 190/1820 [00:07<01:04, 25.10it/s]

 11%|█         | 193/1820 [00:07<01:04, 25.13it/s]

 11%|█         | 196/1820 [00:07<01:02, 26.01it/s]

 11%|█         | 199/1820 [00:07<01:01, 26.37it/s]

 11%|█         | 202/1820 [00:08<01:01, 26.50it/s]

 11%|█▏        | 205/1820 [00:08<01:00, 26.87it/s]

 11%|█▏        | 208/1820 [00:08<00:59, 27.13it/s]

 12%|█▏        | 211/1820 [00:08<01:00, 26.67it/s]

 12%|█▏        | 214/1820 [00:08<01:00, 26.42it/s]

 12%|█▏        | 217/1820 [00:08<00:59, 26.81it/s]

 12%|█▏        | 220/1820 [00:08<01:01, 26.17it/s]

 12%|█▏        | 223/1820 [00:08<00:59, 26.64it/s]

 12%|█▏        | 226/1820 [00:08<01:00, 26.40it/s]

 13%|█▎        | 229/1820 [00:09<00:59, 26.58it/s]

 13%|█▎        | 232/1820 [00:09<01:00, 26.29it/s]

 13%|█▎        | 235/1820 [00:09<00:59, 26.44it/s]

 13%|█▎        | 238/1820 [00:09<01:00, 25.99it/s]

 13%|█▎        | 241/1820 [00:09<01:00, 26.29it/s]

 13%|█▎        | 244/1820 [00:09<00:59, 26.37it/s]

 14%|█▎        | 247/1820 [00:09<01:01, 25.74it/s]

 14%|█▎        | 250/1820 [00:09<01:01, 25.65it/s]

 14%|█▍        | 253/1820 [00:10<01:02, 25.19it/s]

 14%|█▍        | 256/1820 [00:10<01:09, 22.38it/s]

 14%|█▍        | 259/1820 [00:10<01:23, 18.59it/s]

 14%|█▍        | 262/1820 [00:10<01:29, 17.38it/s]

 15%|█▍        | 264/1820 [00:10<01:31, 17.02it/s]

 15%|█▍        | 266/1820 [00:10<01:46, 14.56it/s]

 15%|█▍        | 268/1820 [00:11<01:45, 14.70it/s]

 15%|█▍        | 270/1820 [00:11<01:43, 15.00it/s]

 15%|█▍        | 272/1820 [00:11<01:38, 15.70it/s]

 15%|█▌        | 274/1820 [00:11<01:38, 15.75it/s]

 15%|█▌        | 276/1820 [00:11<01:33, 16.49it/s]

 15%|█▌        | 279/1820 [00:11<01:25, 18.08it/s]

 15%|█▌        | 282/1820 [00:11<01:20, 19.01it/s]

 16%|█▌        | 284/1820 [00:11<01:22, 18.73it/s]

 16%|█▌        | 286/1820 [00:12<01:22, 18.64it/s]

 16%|█▌        | 288/1820 [00:12<01:23, 18.38it/s]

 16%|█▌        | 291/1820 [00:12<01:18, 19.49it/s]

 16%|█▌        | 294/1820 [00:12<01:17, 19.66it/s]

 16%|█▋        | 297/1820 [00:12<01:16, 19.82it/s]

 16%|█▋        | 300/1820 [00:12<01:15, 20.22it/s]

 17%|█▋        | 303/1820 [00:12<01:15, 20.11it/s]

 17%|█▋        | 306/1820 [00:13<01:16, 19.91it/s]

 17%|█▋        | 308/1820 [00:13<01:16, 19.84it/s]

 17%|█▋        | 311/1820 [00:13<01:15, 20.11it/s]

 17%|█▋        | 314/1820 [00:13<01:11, 21.06it/s]

 17%|█▋        | 317/1820 [00:13<01:09, 21.75it/s]

 18%|█▊        | 320/1820 [00:13<01:10, 21.18it/s]

 18%|█▊        | 323/1820 [00:13<01:11, 21.07it/s]

 18%|█▊        | 326/1820 [00:13<01:10, 21.13it/s]

 18%|█▊        | 329/1820 [00:14<01:09, 21.41it/s]

 18%|█▊        | 332/1820 [00:14<01:08, 21.65it/s]

 18%|█▊        | 335/1820 [00:14<01:08, 21.53it/s]

 19%|█▊        | 338/1820 [00:14<01:08, 21.60it/s]

 19%|█▊        | 341/1820 [00:14<01:09, 21.36it/s]

 19%|█▉        | 344/1820 [00:14<01:09, 21.24it/s]

 19%|█▉        | 347/1820 [00:14<01:07, 21.81it/s]

 19%|█▉        | 350/1820 [00:15<01:04, 22.63it/s]

 19%|█▉        | 353/1820 [00:15<01:02, 23.40it/s]

 20%|█▉        | 356/1820 [00:15<01:00, 24.09it/s]

 20%|█▉        | 359/1820 [00:15<01:02, 23.50it/s]

 20%|█▉        | 362/1820 [00:15<01:02, 23.21it/s]

 20%|██        | 365/1820 [00:15<01:02, 23.22it/s]

 20%|██        | 368/1820 [00:15<01:01, 23.56it/s]

 20%|██        | 371/1820 [00:15<01:01, 23.52it/s]

 21%|██        | 374/1820 [00:16<01:01, 23.61it/s]

 21%|██        | 377/1820 [00:16<01:00, 23.67it/s]

 21%|██        | 380/1820 [00:16<00:59, 24.11it/s]

 21%|██        | 383/1820 [00:16<01:00, 23.90it/s]

 21%|██        | 386/1820 [00:16<01:00, 23.82it/s]

 21%|██▏       | 389/1820 [00:16<01:00, 23.82it/s]

 22%|██▏       | 392/1820 [00:16<01:01, 23.31it/s]

 22%|██▏       | 395/1820 [00:16<01:01, 23.22it/s]

 22%|██▏       | 398/1820 [00:17<01:00, 23.51it/s]

 22%|██▏       | 401/1820 [00:17<01:00, 23.54it/s]

 22%|██▏       | 404/1820 [00:17<01:00, 23.56it/s]

 22%|██▏       | 407/1820 [00:17<01:01, 22.93it/s]

 23%|██▎       | 410/1820 [00:17<01:00, 23.41it/s]

 23%|██▎       | 413/1820 [00:17<00:59, 23.69it/s]

 23%|██▎       | 416/1820 [00:17<00:59, 23.78it/s]

 23%|██▎       | 419/1820 [00:18<01:00, 23.35it/s]

 23%|██▎       | 422/1820 [00:18<01:01, 22.89it/s]

 23%|██▎       | 425/1820 [00:18<00:59, 23.38it/s]

 24%|██▎       | 428/1820 [00:18<00:58, 23.62it/s]

 24%|██▎       | 431/1820 [00:18<00:59, 23.34it/s]

 24%|██▍       | 434/1820 [00:18<00:58, 23.70it/s]

 24%|██▍       | 437/1820 [00:18<01:00, 22.92it/s]

 24%|██▍       | 440/1820 [00:18<00:59, 23.07it/s]

 24%|██▍       | 443/1820 [00:19<00:58, 23.45it/s]

 25%|██▍       | 446/1820 [00:19<00:58, 23.67it/s]

 25%|██▍       | 449/1820 [00:19<00:57, 23.77it/s]

 25%|██▍       | 452/1820 [00:19<00:57, 23.84it/s]

 25%|██▌       | 455/1820 [00:19<00:59, 22.80it/s]

 25%|██▌       | 458/1820 [00:19<00:58, 23.31it/s]

 25%|██▌       | 461/1820 [00:19<00:57, 23.68it/s]

 25%|██▌       | 464/1820 [00:19<00:57, 23.61it/s]

 26%|██▌       | 467/1820 [00:20<00:57, 23.39it/s]

 26%|██▌       | 470/1820 [00:20<00:59, 22.51it/s]

 26%|██▌       | 473/1820 [00:20<00:58, 23.09it/s]

 26%|██▌       | 476/1820 [00:20<00:57, 23.25it/s]

 26%|██▋       | 479/1820 [00:20<00:57, 23.53it/s]

 26%|██▋       | 482/1820 [00:20<00:56, 23.55it/s]

 27%|██▋       | 485/1820 [00:20<00:55, 23.91it/s]

 27%|██▋       | 488/1820 [00:20<00:56, 23.77it/s]

 27%|██▋       | 491/1820 [00:21<00:56, 23.61it/s]

 27%|██▋       | 494/1820 [00:21<00:56, 23.45it/s]

 27%|██▋       | 497/1820 [00:21<00:57, 23.17it/s]

 27%|██▋       | 500/1820 [00:21<00:57, 23.14it/s]

 28%|██▊       | 503/1820 [00:21<00:56, 23.18it/s]

 28%|██▊       | 506/1820 [00:21<00:56, 23.15it/s]

 28%|██▊       | 509/1820 [00:21<00:57, 22.86it/s]

 28%|██▊       | 512/1820 [00:21<00:56, 22.95it/s]

 28%|██▊       | 515/1820 [00:22<00:57, 22.57it/s]

 28%|██▊       | 518/1820 [00:22<00:57, 22.72it/s]

 29%|██▊       | 521/1820 [00:22<00:56, 23.09it/s]

 29%|██▉       | 524/1820 [00:22<00:55, 23.25it/s]

 29%|██▉       | 527/1820 [00:22<00:57, 22.57it/s]

 29%|██▉       | 530/1820 [00:22<00:57, 22.51it/s]

 29%|██▉       | 533/1820 [00:22<00:56, 22.68it/s]

 29%|██▉       | 536/1820 [00:23<00:55, 23.17it/s]

 30%|██▉       | 539/1820 [00:23<00:55, 23.03it/s]

 30%|██▉       | 542/1820 [00:23<00:55, 22.99it/s]

 30%|██▉       | 545/1820 [00:23<00:55, 22.86it/s]

 30%|███       | 548/1820 [00:23<00:54, 23.35it/s]

 30%|███       | 551/1820 [00:23<00:54, 23.49it/s]

 30%|███       | 554/1820 [00:23<00:53, 23.53it/s]

 31%|███       | 557/1820 [00:23<00:54, 23.23it/s]

 31%|███       | 560/1820 [00:24<00:53, 23.51it/s]

 31%|███       | 563/1820 [00:24<00:53, 23.43it/s]

 31%|███       | 566/1820 [00:24<00:53, 23.54it/s]

 31%|███▏      | 569/1820 [00:24<00:53, 23.35it/s]

 31%|███▏      | 572/1820 [00:24<00:52, 23.82it/s]

 32%|███▏      | 575/1820 [00:24<00:52, 23.70it/s]

 32%|███▏      | 578/1820 [00:24<00:52, 23.74it/s]

 32%|███▏      | 581/1820 [00:24<00:52, 23.42it/s]

 32%|███▏      | 584/1820 [00:25<00:52, 23.54it/s]

 32%|███▏      | 587/1820 [00:25<00:52, 23.29it/s]

 32%|███▏      | 590/1820 [00:25<00:51, 23.72it/s]

 33%|███▎      | 593/1820 [00:25<00:51, 23.69it/s]

 33%|███▎      | 596/1820 [00:25<00:51, 23.61it/s]

 33%|███▎      | 599/1820 [00:25<00:52, 23.40it/s]

 33%|███▎      | 602/1820 [00:25<00:51, 23.52it/s]

 33%|███▎      | 605/1820 [00:25<00:52, 23.33it/s]

 33%|███▎      | 608/1820 [00:26<00:51, 23.58it/s]

 34%|███▎      | 611/1820 [00:26<00:53, 22.63it/s]

 34%|███▎      | 614/1820 [00:26<00:53, 22.61it/s]

 34%|███▍      | 617/1820 [00:26<00:53, 22.70it/s]

 34%|███▍      | 620/1820 [00:26<00:51, 23.23it/s]

 34%|███▍      | 623/1820 [00:26<00:51, 23.35it/s]

 34%|███▍      | 626/1820 [00:26<00:51, 22.97it/s]

 35%|███▍      | 629/1820 [00:27<00:51, 23.11it/s]

 35%|███▍      | 632/1820 [00:27<00:52, 22.78it/s]

 35%|███▍      | 635/1820 [00:27<00:51, 23.08it/s]

 35%|███▌      | 638/1820 [00:27<00:51, 23.08it/s]

 35%|███▌      | 641/1820 [00:27<00:50, 23.19it/s]

 35%|███▌      | 644/1820 [00:27<00:50, 23.32it/s]

 36%|███▌      | 647/1820 [00:27<00:50, 23.19it/s]

 36%|███▌      | 650/1820 [00:27<00:51, 22.73it/s]

 36%|███▌      | 653/1820 [00:28<00:50, 23.10it/s]

 36%|███▌      | 656/1820 [00:28<00:51, 22.57it/s]

 36%|███▌      | 659/1820 [00:28<00:50, 23.03it/s]

 36%|███▋      | 662/1820 [00:28<00:50, 23.10it/s]

 37%|███▋      | 665/1820 [00:28<00:48, 23.75it/s]

 37%|███▋      | 668/1820 [00:28<00:48, 23.60it/s]

 37%|███▋      | 671/1820 [00:28<00:48, 23.50it/s]

 37%|███▋      | 674/1820 [00:28<00:49, 23.26it/s]

 37%|███▋      | 677/1820 [00:29<00:49, 22.94it/s]

 37%|███▋      | 680/1820 [00:29<00:49, 23.03it/s]

 38%|███▊      | 683/1820 [00:29<00:49, 23.05it/s]

 38%|███▊      | 686/1820 [00:29<00:49, 23.06it/s]

 38%|███▊      | 689/1820 [00:29<00:48, 23.17it/s]

 38%|███▊      | 692/1820 [00:29<00:48, 23.14it/s]

 38%|███▊      | 695/1820 [00:29<00:48, 23.02it/s]

 38%|███▊      | 698/1820 [00:30<00:48, 22.93it/s]

 39%|███▊      | 701/1820 [00:30<00:52, 21.45it/s]

 39%|███▊      | 704/1820 [00:30<00:50, 22.01it/s]

 39%|███▉      | 707/1820 [00:30<00:51, 21.78it/s]

 39%|███▉      | 710/1820 [00:30<00:49, 22.30it/s]

 39%|███▉      | 713/1820 [00:30<00:48, 22.79it/s]

 39%|███▉      | 716/1820 [00:30<00:49, 22.51it/s]

 40%|███▉      | 719/1820 [00:30<00:47, 22.94it/s]

 40%|███▉      | 722/1820 [00:31<00:46, 23.41it/s]

 40%|███▉      | 725/1820 [00:31<00:47, 23.15it/s]

 40%|████      | 728/1820 [00:31<00:46, 23.29it/s]

 40%|████      | 731/1820 [00:31<00:47, 23.06it/s]

 40%|████      | 734/1820 [00:31<00:47, 22.65it/s]

 40%|████      | 737/1820 [00:31<00:47, 22.62it/s]

 41%|████      | 740/1820 [00:31<00:47, 22.86it/s]

 41%|████      | 743/1820 [00:32<00:46, 23.06it/s]

 41%|████      | 746/1820 [00:32<00:45, 23.44it/s]

 41%|████      | 749/1820 [00:32<00:44, 23.89it/s]

 41%|████▏     | 752/1820 [00:32<00:45, 23.47it/s]

 41%|████▏     | 755/1820 [00:32<00:46, 23.08it/s]

 42%|████▏     | 758/1820 [00:32<00:46, 22.71it/s]

 42%|████▏     | 761/1820 [00:32<00:46, 22.82it/s]

 42%|████▏     | 764/1820 [00:32<00:46, 22.85it/s]

 42%|████▏     | 767/1820 [00:33<00:46, 22.71it/s]

 42%|████▏     | 770/1820 [00:33<00:46, 22.76it/s]

 42%|████▏     | 773/1820 [00:33<00:45, 22.91it/s]

 43%|████▎     | 776/1820 [00:33<00:44, 23.28it/s]

 43%|████▎     | 779/1820 [00:33<00:44, 23.27it/s]

 43%|████▎     | 782/1820 [00:33<00:44, 23.21it/s]

 43%|████▎     | 785/1820 [00:33<00:44, 23.28it/s]

 43%|████▎     | 788/1820 [00:33<00:43, 23.55it/s]

 43%|████▎     | 791/1820 [00:34<00:43, 23.46it/s]

 44%|████▎     | 794/1820 [00:34<00:43, 23.56it/s]

 44%|████▍     | 797/1820 [00:34<00:43, 23.75it/s]

 44%|████▍     | 800/1820 [00:34<00:43, 23.60it/s]

 44%|████▍     | 803/1820 [00:34<00:43, 23.44it/s]

 44%|████▍     | 806/1820 [00:34<00:43, 23.28it/s]

 44%|████▍     | 809/1820 [00:34<00:45, 22.43it/s]

 45%|████▍     | 812/1820 [00:34<00:45, 21.93it/s]

 45%|████▍     | 815/1820 [00:35<00:44, 22.56it/s]

 45%|████▍     | 818/1820 [00:35<00:43, 23.03it/s]

 45%|████▌     | 821/1820 [00:35<00:43, 22.99it/s]

 45%|████▌     | 824/1820 [00:35<00:42, 23.34it/s]

 45%|████▌     | 827/1820 [00:35<00:43, 22.89it/s]

 46%|████▌     | 830/1820 [00:35<00:44, 22.48it/s]

 46%|████▌     | 833/1820 [00:35<00:42, 22.97it/s]

 46%|████▌     | 836/1820 [00:36<00:42, 23.16it/s]

 46%|████▌     | 839/1820 [00:36<00:41, 23.41it/s]

 46%|████▋     | 842/1820 [00:36<00:41, 23.47it/s]

 46%|████▋     | 845/1820 [00:36<00:40, 23.91it/s]

 47%|████▋     | 848/1820 [00:36<00:40, 23.88it/s]

 47%|████▋     | 851/1820 [00:36<00:40, 24.09it/s]

 47%|████▋     | 854/1820 [00:36<00:39, 24.35it/s]

 47%|████▋     | 857/1820 [00:36<00:39, 24.30it/s]

 47%|████▋     | 860/1820 [00:37<00:39, 24.09it/s]

 47%|████▋     | 863/1820 [00:37<00:39, 24.12it/s]

 48%|████▊     | 866/1820 [00:37<00:39, 24.14it/s]

 48%|████▊     | 869/1820 [00:37<00:39, 24.22it/s]

 48%|████▊     | 872/1820 [00:37<00:39, 24.27it/s]

 48%|████▊     | 875/1820 [00:37<00:38, 24.31it/s]

 48%|████▊     | 878/1820 [00:37<00:38, 24.15it/s]

 48%|████▊     | 881/1820 [00:37<00:38, 24.22it/s]

 49%|████▊     | 884/1820 [00:38<00:38, 24.27it/s]

 49%|████▊     | 887/1820 [00:38<00:38, 24.37it/s]

 49%|████▉     | 890/1820 [00:38<00:38, 24.40it/s]

 49%|████▉     | 893/1820 [00:38<00:39, 23.59it/s]

 49%|████▉     | 896/1820 [00:38<00:39, 23.55it/s]

 49%|████▉     | 899/1820 [00:38<00:40, 22.71it/s]

 50%|████▉     | 902/1820 [00:38<00:41, 22.21it/s]

 50%|████▉     | 905/1820 [00:38<00:41, 22.11it/s]

 50%|████▉     | 908/1820 [00:39<00:41, 22.20it/s]

 50%|█████     | 911/1820 [00:39<00:41, 22.06it/s]

 50%|█████     | 914/1820 [00:39<00:41, 21.82it/s]

 50%|█████     | 917/1820 [00:39<00:41, 21.84it/s]

 51%|█████     | 920/1820 [00:39<00:41, 21.91it/s]

 51%|█████     | 923/1820 [00:39<00:41, 21.48it/s]

 51%|█████     | 926/1820 [00:39<00:42, 20.88it/s]

 51%|█████     | 929/1820 [00:40<00:42, 20.87it/s]

 51%|█████     | 932/1820 [00:40<00:41, 21.17it/s]

 51%|█████▏    | 935/1820 [00:40<00:42, 20.93it/s]

 52%|█████▏    | 938/1820 [00:40<00:41, 21.21it/s]

 52%|█████▏    | 941/1820 [00:40<00:41, 21.28it/s]

 52%|█████▏    | 944/1820 [00:40<00:40, 21.60it/s]

 52%|█████▏    | 947/1820 [00:40<00:40, 21.64it/s]

 52%|█████▏    | 950/1820 [00:41<00:40, 21.39it/s]

 52%|█████▏    | 953/1820 [00:41<00:40, 21.63it/s]

 53%|█████▎    | 956/1820 [00:41<00:39, 22.00it/s]

 53%|█████▎    | 959/1820 [00:41<00:39, 21.73it/s]

 53%|█████▎    | 962/1820 [00:41<00:39, 21.55it/s]

 53%|█████▎    | 965/1820 [00:41<00:40, 21.37it/s]

 53%|█████▎    | 968/1820 [00:41<00:40, 21.23it/s]

 53%|█████▎    | 971/1820 [00:42<00:39, 21.29it/s]

 54%|█████▎    | 974/1820 [00:42<00:39, 21.42it/s]

 54%|█████▎    | 977/1820 [00:42<00:39, 21.56it/s]

 54%|█████▍    | 980/1820 [00:42<00:39, 21.48it/s]

 54%|█████▍    | 983/1820 [00:42<00:39, 21.19it/s]

 54%|█████▍    | 986/1820 [00:42<00:39, 21.31it/s]

 54%|█████▍    | 989/1820 [00:42<00:38, 21.48it/s]

 55%|█████▍    | 992/1820 [00:42<00:38, 21.60it/s]

 55%|█████▍    | 995/1820 [00:43<00:38, 21.69it/s]

 55%|█████▍    | 998/1820 [00:43<00:37, 21.75it/s]

 55%|█████▌    | 1001/1820 [00:43<00:40, 20.09it/s]

 55%|█████▌    | 1004/1820 [00:43<00:40, 20.31it/s]

 55%|█████▌    | 1007/1820 [00:43<00:40, 19.93it/s]

 55%|█████▌    | 1010/1820 [00:43<00:40, 20.19it/s]

 56%|█████▌    | 1013/1820 [00:44<00:40, 19.82it/s]

 56%|█████▌    | 1015/1820 [00:44<00:40, 19.68it/s]

 56%|█████▌    | 1017/1820 [00:44<00:40, 19.71it/s]

 56%|█████▌    | 1019/1820 [00:44<00:40, 19.73it/s]

 56%|█████▌    | 1022/1820 [00:44<00:39, 20.02it/s]

 56%|█████▋    | 1025/1820 [00:44<00:39, 20.24it/s]

 56%|█████▋    | 1028/1820 [00:44<00:38, 20.52it/s]

 57%|█████▋    | 1031/1820 [00:44<00:38, 20.75it/s]

 57%|█████▋    | 1034/1820 [00:45<00:38, 20.56it/s]

 57%|█████▋    | 1037/1820 [00:45<00:37, 20.95it/s]

 57%|█████▋    | 1040/1820 [00:45<00:36, 21.19it/s]

 57%|█████▋    | 1043/1820 [00:45<00:36, 21.21it/s]

 57%|█████▋    | 1046/1820 [00:45<00:36, 21.46it/s]

 58%|█████▊    | 1049/1820 [00:45<00:35, 21.45it/s]

 58%|█████▊    | 1052/1820 [00:45<00:36, 21.17it/s]

 58%|█████▊    | 1055/1820 [00:46<00:36, 21.07it/s]

 58%|█████▊    | 1058/1820 [00:46<00:35, 21.31it/s]

 58%|█████▊    | 1061/1820 [00:46<00:35, 21.17it/s]

 58%|█████▊    | 1064/1820 [00:46<00:35, 21.24it/s]

 59%|█████▊    | 1067/1820 [00:46<00:35, 21.44it/s]

 59%|█████▉    | 1070/1820 [00:46<00:35, 21.21it/s]

 59%|█████▉    | 1073/1820 [00:46<00:35, 20.96it/s]

 59%|█████▉    | 1076/1820 [00:47<00:35, 21.23it/s]

 59%|█████▉    | 1079/1820 [00:47<00:34, 21.29it/s]

 59%|█████▉    | 1082/1820 [00:47<00:34, 21.15it/s]

 60%|█████▉    | 1085/1820 [00:47<00:35, 20.92it/s]

 60%|█████▉    | 1088/1820 [00:47<00:34, 21.16it/s]

 60%|█████▉    | 1091/1820 [00:47<00:34, 21.24it/s]

 60%|██████    | 1094/1820 [00:47<00:35, 20.72it/s]

 60%|██████    | 1097/1820 [00:48<00:35, 20.42it/s]

 60%|██████    | 1100/1820 [00:48<00:35, 20.37it/s]

 61%|██████    | 1103/1820 [00:48<00:35, 20.26it/s]

 61%|██████    | 1106/1820 [00:48<00:34, 20.59it/s]

 61%|██████    | 1109/1820 [00:48<00:33, 21.15it/s]

 61%|██████    | 1112/1820 [00:48<00:32, 21.83it/s]

 61%|██████▏   | 1115/1820 [00:48<00:31, 22.24it/s]

 61%|██████▏   | 1118/1820 [00:49<00:31, 22.24it/s]

 62%|██████▏   | 1121/1820 [00:49<00:31, 22.08it/s]

 62%|██████▏   | 1124/1820 [00:49<00:32, 21.69it/s]

 62%|██████▏   | 1127/1820 [00:49<00:32, 21.47it/s]

 62%|██████▏   | 1130/1820 [00:49<00:31, 21.79it/s]

 62%|██████▏   | 1133/1820 [00:49<00:31, 21.77it/s]

 62%|██████▏   | 1136/1820 [00:49<00:31, 21.39it/s]

 63%|██████▎   | 1139/1820 [00:50<00:31, 21.36it/s]

 63%|██████▎   | 1142/1820 [00:50<00:32, 21.15it/s]

 63%|██████▎   | 1145/1820 [00:50<00:32, 20.84it/s]

 63%|██████▎   | 1148/1820 [00:50<00:32, 20.83it/s]

 63%|██████▎   | 1151/1820 [00:50<00:31, 21.10it/s]

 63%|██████▎   | 1154/1820 [00:50<00:30, 21.75it/s]

 64%|██████▎   | 1157/1820 [00:50<00:30, 21.94it/s]

 64%|██████▎   | 1160/1820 [00:50<00:30, 21.36it/s]

 64%|██████▍   | 1163/1820 [00:51<00:30, 21.34it/s]

 64%|██████▍   | 1166/1820 [00:51<00:30, 21.23it/s]

 64%|██████▍   | 1169/1820 [00:51<00:30, 21.24it/s]

 64%|██████▍   | 1172/1820 [00:51<00:29, 21.86it/s]

 65%|██████▍   | 1175/1820 [00:51<00:28, 22.71it/s]

 65%|██████▍   | 1178/1820 [00:51<00:28, 22.93it/s]

 65%|██████▍   | 1181/1820 [00:51<00:27, 23.37it/s]

 65%|██████▌   | 1184/1820 [00:52<00:27, 22.96it/s]

 65%|██████▌   | 1187/1820 [00:52<00:27, 22.79it/s]

 65%|██████▌   | 1190/1820 [00:52<00:26, 23.35it/s]

 66%|██████▌   | 1193/1820 [00:52<00:26, 23.82it/s]

 66%|██████▌   | 1196/1820 [00:52<00:25, 24.11it/s]

 66%|██████▌   | 1199/1820 [00:52<00:25, 24.08it/s]

 66%|██████▌   | 1202/1820 [00:52<00:25, 23.94it/s]

 66%|██████▌   | 1205/1820 [00:52<00:27, 22.60it/s]

 66%|██████▋   | 1208/1820 [00:53<00:27, 22.09it/s]

 67%|██████▋   | 1211/1820 [00:53<00:28, 21.46it/s]

 67%|██████▋   | 1214/1820 [00:53<00:28, 21.55it/s]

 67%|██████▋   | 1217/1820 [00:53<00:27, 21.60it/s]

 67%|██████▋   | 1220/1820 [00:53<00:26, 22.37it/s]

 67%|██████▋   | 1223/1820 [00:53<00:26, 22.94it/s]

 67%|██████▋   | 1226/1820 [00:53<00:25, 23.25it/s]

 68%|██████▊   | 1229/1820 [00:54<00:24, 23.69it/s]

 68%|██████▊   | 1232/1820 [00:54<00:24, 23.90it/s]

 68%|██████▊   | 1235/1820 [00:54<00:26, 22.32it/s]

 68%|██████▊   | 1238/1820 [00:54<00:26, 22.15it/s]

 68%|██████▊   | 1241/1820 [00:54<00:26, 21.78it/s]

 68%|██████▊   | 1244/1820 [00:54<00:27, 20.95it/s]

 69%|██████▊   | 1247/1820 [00:54<00:27, 20.83it/s]

 69%|██████▊   | 1250/1820 [00:55<00:27, 20.83it/s]

 69%|██████▉   | 1253/1820 [00:55<00:27, 20.92it/s]

 69%|██████▉   | 1256/1820 [00:55<00:26, 20.98it/s]

 69%|██████▉   | 1259/1820 [00:55<00:26, 21.38it/s]

 69%|██████▉   | 1262/1820 [00:55<00:25, 21.74it/s]

 70%|██████▉   | 1265/1820 [00:55<00:25, 21.79it/s]

 70%|██████▉   | 1268/1820 [00:55<00:25, 21.59it/s]

 70%|██████▉   | 1271/1820 [00:55<00:25, 21.63it/s]

 70%|███████   | 1274/1820 [00:56<00:25, 21.34it/s]

 70%|███████   | 1277/1820 [00:56<00:25, 21.01it/s]

 70%|███████   | 1280/1820 [00:56<00:25, 21.40it/s]

 70%|███████   | 1283/1820 [00:56<00:24, 22.07it/s]

 71%|███████   | 1286/1820 [00:56<00:23, 22.31it/s]

 71%|███████   | 1289/1820 [00:56<00:23, 22.64it/s]

 71%|███████   | 1292/1820 [00:56<00:23, 22.69it/s]

 71%|███████   | 1295/1820 [00:57<00:22, 23.12it/s]

 71%|███████▏  | 1298/1820 [00:57<00:22, 23.32it/s]

 71%|███████▏  | 1301/1820 [00:57<00:22, 23.52it/s]

 72%|███████▏  | 1304/1820 [00:57<00:21, 23.72it/s]

 72%|███████▏  | 1307/1820 [00:57<00:22, 22.88it/s]

 72%|███████▏  | 1310/1820 [00:57<00:23, 21.65it/s]

 72%|███████▏  | 1313/1820 [00:57<00:23, 21.40it/s]

 72%|███████▏  | 1316/1820 [00:57<00:22, 22.07it/s]

 72%|███████▏  | 1319/1820 [00:58<00:22, 22.77it/s]

 73%|███████▎  | 1322/1820 [00:58<00:21, 23.29it/s]

 73%|███████▎  | 1325/1820 [00:58<00:20, 23.72it/s]

 73%|███████▎  | 1328/1820 [00:58<00:20, 23.58it/s]

 73%|███████▎  | 1331/1820 [00:58<00:20, 23.70it/s]

 73%|███████▎  | 1334/1820 [00:58<00:20, 24.02it/s]

 73%|███████▎  | 1337/1820 [00:58<00:19, 24.25it/s]

 74%|███████▎  | 1340/1820 [00:58<00:19, 24.35it/s]

 74%|███████▍  | 1343/1820 [00:59<00:19, 24.42it/s]

 74%|███████▍  | 1346/1820 [00:59<00:19, 24.41it/s]

 74%|███████▍  | 1349/1820 [00:59<00:19, 24.59it/s]

 74%|███████▍  | 1352/1820 [00:59<00:18, 24.77it/s]

 74%|███████▍  | 1355/1820 [00:59<00:18, 24.96it/s]

 75%|███████▍  | 1358/1820 [00:59<00:18, 25.04it/s]

 75%|███████▍  | 1361/1820 [00:59<00:18, 25.15it/s]

 75%|███████▍  | 1364/1820 [00:59<00:18, 25.23it/s]

 75%|███████▌  | 1367/1820 [01:00<00:18, 25.04it/s]

 75%|███████▌  | 1370/1820 [01:00<00:18, 24.59it/s]

 75%|███████▌  | 1373/1820 [01:00<00:19, 23.33it/s]

 76%|███████▌  | 1376/1820 [01:00<00:22, 19.88it/s]

 76%|███████▌  | 1379/1820 [01:00<00:22, 19.34it/s]

 76%|███████▌  | 1382/1820 [01:00<00:22, 19.69it/s]

 76%|███████▌  | 1385/1820 [01:00<00:21, 19.90it/s]

 76%|███████▋  | 1388/1820 [01:01<00:21, 20.01it/s]

 76%|███████▋  | 1391/1820 [01:01<00:21, 19.89it/s]

 77%|███████▋  | 1394/1820 [01:01<00:21, 20.12it/s]

 77%|███████▋  | 1397/1820 [01:01<00:21, 20.12it/s]

 77%|███████▋  | 1400/1820 [01:01<00:20, 20.13it/s]

 77%|███████▋  | 1403/1820 [01:01<00:20, 20.11it/s]

 77%|███████▋  | 1406/1820 [01:02<00:20, 20.44it/s]

 77%|███████▋  | 1409/1820 [01:02<00:19, 20.95it/s]

 78%|███████▊  | 1412/1820 [01:02<00:19, 20.96it/s]

 78%|███████▊  | 1415/1820 [01:02<00:19, 21.28it/s]

 78%|███████▊  | 1418/1820 [01:02<00:19, 20.79it/s]

 78%|███████▊  | 1421/1820 [01:02<00:18, 21.38it/s]

 78%|███████▊  | 1424/1820 [01:02<00:18, 21.91it/s]

 78%|███████▊  | 1427/1820 [01:02<00:17, 22.45it/s]

 79%|███████▊  | 1430/1820 [01:03<00:17, 22.48it/s]

 79%|███████▊  | 1433/1820 [01:03<00:17, 22.06it/s]

 79%|███████▉  | 1436/1820 [01:03<00:17, 21.86it/s]

 79%|███████▉  | 1439/1820 [01:03<00:17, 21.59it/s]

 79%|███████▉  | 1442/1820 [01:03<00:17, 21.82it/s]

 79%|███████▉  | 1445/1820 [01:03<00:16, 22.19it/s]

 80%|███████▉  | 1448/1820 [01:03<00:16, 22.00it/s]

 80%|███████▉  | 1451/1820 [01:04<00:17, 21.54it/s]

 80%|███████▉  | 1454/1820 [01:04<00:17, 20.92it/s]

 80%|████████  | 1457/1820 [01:04<00:17, 20.77it/s]

 80%|████████  | 1460/1820 [01:04<00:17, 20.83it/s]

 80%|████████  | 1463/1820 [01:04<00:17, 20.16it/s]

 81%|████████  | 1466/1820 [01:04<00:17, 19.83it/s]

 81%|████████  | 1469/1820 [01:04<00:17, 20.04it/s]

 81%|████████  | 1472/1820 [01:05<00:17, 19.52it/s]

 81%|████████  | 1475/1820 [01:05<00:16, 20.34it/s]

 81%|████████  | 1478/1820 [01:05<00:16, 21.05it/s]

 81%|████████▏ | 1481/1820 [01:05<00:16, 20.72it/s]

 82%|████████▏ | 1484/1820 [01:05<00:16, 20.37it/s]

 82%|████████▏ | 1487/1820 [01:05<00:16, 20.10it/s]

 82%|████████▏ | 1490/1820 [01:06<00:16, 20.61it/s]

 82%|████████▏ | 1493/1820 [01:06<00:15, 20.72it/s]

 82%|████████▏ | 1496/1820 [01:06<00:15, 20.62it/s]

 82%|████████▏ | 1499/1820 [01:06<00:15, 20.90it/s]

 83%|████████▎ | 1502/1820 [01:06<00:16, 19.09it/s]

 83%|████████▎ | 1504/1820 [01:06<00:17, 18.38it/s]

 83%|████████▎ | 1506/1820 [01:06<00:17, 18.09it/s]

 83%|████████▎ | 1508/1820 [01:06<00:16, 18.52it/s]

 83%|████████▎ | 1511/1820 [01:07<00:16, 19.02it/s]

 83%|████████▎ | 1514/1820 [01:07<00:15, 19.64it/s]

 83%|████████▎ | 1516/1820 [01:07<00:15, 19.58it/s]

 83%|████████▎ | 1519/1820 [01:07<00:14, 20.32it/s]

 84%|████████▎ | 1522/1820 [01:07<00:14, 20.58it/s]

 84%|████████▍ | 1525/1820 [01:07<00:14, 20.48it/s]

 84%|████████▍ | 1528/1820 [01:07<00:14, 20.72it/s]

 84%|████████▍ | 1531/1820 [01:08<00:13, 20.84it/s]

 84%|████████▍ | 1534/1820 [01:08<00:13, 20.75it/s]

 84%|████████▍ | 1537/1820 [01:08<00:13, 20.82it/s]

 85%|████████▍ | 1540/1820 [01:08<00:13, 21.00it/s]

 85%|████████▍ | 1543/1820 [01:08<00:13, 20.69it/s]

 85%|████████▍ | 1546/1820 [01:08<00:13, 20.60it/s]

 85%|████████▌ | 1549/1820 [01:08<00:12, 20.89it/s]

 85%|████████▌ | 1552/1820 [01:09<00:12, 21.05it/s]

 85%|████████▌ | 1555/1820 [01:09<00:12, 21.39it/s]

 86%|████████▌ | 1558/1820 [01:09<00:12, 21.26it/s]

 86%|████████▌ | 1561/1820 [01:09<00:12, 21.40it/s]

 86%|████████▌ | 1564/1820 [01:09<00:11, 21.78it/s]

 86%|████████▌ | 1567/1820 [01:09<00:11, 21.44it/s]

 86%|████████▋ | 1570/1820 [01:09<00:11, 21.30it/s]

 86%|████████▋ | 1573/1820 [01:10<00:11, 22.09it/s]

 87%|████████▋ | 1576/1820 [01:10<00:10, 22.38it/s]

 87%|████████▋ | 1579/1820 [01:10<00:10, 22.58it/s]

 87%|████████▋ | 1582/1820 [01:10<00:10, 22.78it/s]

 87%|████████▋ | 1585/1820 [01:10<00:10, 22.51it/s]

 87%|████████▋ | 1588/1820 [01:10<00:10, 22.22it/s]

 87%|████████▋ | 1591/1820 [01:10<00:10, 22.57it/s]

 88%|████████▊ | 1594/1820 [01:10<00:09, 23.31it/s]

 88%|████████▊ | 1597/1820 [01:11<00:09, 23.24it/s]

 88%|████████▊ | 1600/1820 [01:11<00:09, 23.19it/s]

 88%|████████▊ | 1603/1820 [01:11<00:09, 23.00it/s]

 88%|████████▊ | 1606/1820 [01:11<00:09, 23.07it/s]

 88%|████████▊ | 1609/1820 [01:11<00:08, 23.62it/s]

 89%|████████▊ | 1612/1820 [01:11<00:08, 23.51it/s]

 89%|████████▊ | 1615/1820 [01:11<00:08, 23.82it/s]

 89%|████████▉ | 1618/1820 [01:11<00:08, 24.02it/s]

 89%|████████▉ | 1621/1820 [01:12<00:08, 24.30it/s]

 89%|████████▉ | 1624/1820 [01:12<00:07, 24.51it/s]

 89%|████████▉ | 1627/1820 [01:12<00:07, 24.29it/s]

 90%|████████▉ | 1630/1820 [01:12<00:07, 24.38it/s]

 90%|████████▉ | 1633/1820 [01:12<00:07, 24.44it/s]

 90%|████████▉ | 1636/1820 [01:12<00:07, 24.61it/s]

 90%|█████████ | 1639/1820 [01:12<00:07, 24.66it/s]

 90%|█████████ | 1642/1820 [01:12<00:07, 24.76it/s]

 90%|█████████ | 1645/1820 [01:13<00:07, 24.83it/s]

 91%|█████████ | 1648/1820 [01:13<00:06, 24.82it/s]

 91%|█████████ | 1651/1820 [01:13<00:06, 24.87it/s]

 91%|█████████ | 1654/1820 [01:13<00:06, 24.73it/s]

 91%|█████████ | 1657/1820 [01:13<00:06, 24.35it/s]

 91%|█████████ | 1660/1820 [01:13<00:06, 23.29it/s]

 91%|█████████▏| 1663/1820 [01:13<00:06, 22.80it/s]

 92%|█████████▏| 1666/1820 [01:13<00:06, 22.99it/s]

 92%|█████████▏| 1669/1820 [01:14<00:06, 22.70it/s]

 92%|█████████▏| 1672/1820 [01:14<00:06, 22.81it/s]

 92%|█████████▏| 1675/1820 [01:14<00:06, 22.53it/s]

 92%|█████████▏| 1678/1820 [01:14<00:06, 22.59it/s]

 92%|█████████▏| 1681/1820 [01:14<00:06, 22.73it/s]

 93%|█████████▎| 1684/1820 [01:14<00:05, 23.26it/s]

 93%|█████████▎| 1687/1820 [01:14<00:05, 23.37it/s]

 93%|█████████▎| 1690/1820 [01:15<00:05, 22.91it/s]

 93%|█████████▎| 1693/1820 [01:15<00:05, 22.49it/s]

 93%|█████████▎| 1696/1820 [01:15<00:05, 21.82it/s]

 93%|█████████▎| 1699/1820 [01:15<00:05, 21.94it/s]

 94%|█████████▎| 1702/1820 [01:15<00:05, 22.57it/s]

 94%|█████████▎| 1705/1820 [01:15<00:04, 23.09it/s]

 94%|█████████▍| 1708/1820 [01:15<00:04, 23.03it/s]

 94%|█████████▍| 1711/1820 [01:15<00:04, 23.48it/s]

 94%|█████████▍| 1714/1820 [01:16<00:04, 23.86it/s]

 94%|█████████▍| 1717/1820 [01:16<00:04, 24.19it/s]

 95%|█████████▍| 1720/1820 [01:16<00:04, 24.07it/s]

 95%|█████████▍| 1723/1820 [01:16<00:04, 24.23it/s]

 95%|█████████▍| 1726/1820 [01:16<00:03, 24.33it/s]

 95%|█████████▌| 1729/1820 [01:16<00:03, 24.23it/s]

 95%|█████████▌| 1732/1820 [01:16<00:03, 23.87it/s]

 95%|█████████▌| 1735/1820 [01:16<00:03, 23.94it/s]

 95%|█████████▌| 1738/1820 [01:17<00:03, 24.25it/s]

 96%|█████████▌| 1741/1820 [01:17<00:03, 24.41it/s]

 96%|█████████▌| 1744/1820 [01:17<00:03, 24.52it/s]

 96%|█████████▌| 1747/1820 [01:17<00:02, 24.36it/s]

 96%|█████████▌| 1750/1820 [01:17<00:02, 24.61it/s]

 96%|█████████▋| 1753/1820 [01:17<00:02, 24.48it/s]

 96%|█████████▋| 1756/1820 [01:17<00:02, 24.40it/s]

 97%|█████████▋| 1759/1820 [01:17<00:02, 24.39it/s]

 97%|█████████▋| 1762/1820 [01:18<00:02, 23.48it/s]

 97%|█████████▋| 1765/1820 [01:18<00:02, 23.52it/s]

 97%|█████████▋| 1768/1820 [01:18<00:02, 23.69it/s]

 97%|█████████▋| 1771/1820 [01:18<00:02, 23.61it/s]

 97%|█████████▋| 1774/1820 [01:18<00:02, 22.91it/s]

 98%|█████████▊| 1777/1820 [01:18<00:01, 21.95it/s]

 98%|█████████▊| 1780/1820 [01:18<00:01, 21.51it/s]

 98%|█████████▊| 1783/1820 [01:18<00:01, 21.82it/s]

 98%|█████████▊| 1786/1820 [01:19<00:01, 22.58it/s]

 98%|█████████▊| 1789/1820 [01:19<00:01, 23.20it/s]

 98%|█████████▊| 1792/1820 [01:19<00:01, 23.49it/s]

 99%|█████████▊| 1795/1820 [01:19<00:01, 23.81it/s]

 99%|█████████▉| 1798/1820 [01:19<00:00, 23.59it/s]

 99%|█████████▉| 1801/1820 [01:19<00:00, 23.93it/s]

 99%|█████████▉| 1804/1820 [01:19<00:00, 24.24it/s]

 99%|█████████▉| 1807/1820 [01:19<00:00, 24.23it/s]

 99%|█████████▉| 1810/1820 [01:20<00:00, 24.40it/s]

100%|█████████▉| 1813/1820 [01:20<00:00, 24.51it/s]

100%|█████████▉| 1816/1820 [01:20<00:00, 24.60it/s]

100%|█████████▉| 1819/1820 [01:20<00:00, 24.53it/s]

100%|██████████| 1820/1820 [01:20<00:00, 22.61it/s]

Embeddings shape: (1820, 512)

,embedding_index,camera_id,local_track_id,frame_id,timestamp_sec,crop_path,quality_score
0,0,MOT17-02-FRCNN,1,44,1.433333,D:\hoiancomputervision\ticket_suspicion_projec...,0.993238
1,1,MOT17-02-FRCNN,1,43,1.400000,D:\hoiancomputervision\ticket_suspicion_projec...,0.989640
2,2,MOT17-02-FRCNN,1,6,0.166667,D:\hoiancomputervision\ticket_suspicion_projec...,0.983757
3,3,MOT17-02-FRCNN,1,5,0.133333,D:\hoiancomputervision\ticket_suspicion_projec...,0.976241
4,4,MOT17-02-FRCNN,1,7,0.200000,D:\hoiancomputervision\ticket_suspicion_projec...,0.969124

# Tracklet-level embedding

In [9]:
# Cell này thực hiện một bước cụ thể trong luồng pipeline, có thể là nạp dữ liệu, xử lý, hoặc lưu kết quả.
emb_meta_df = pd.read_csv(PROJECT_ROOT / "outputs/embeddings/crop_embeddings_meta.csv")
embeddings = np.load(PROJECT_ROOT / "outputs/embeddings/crop_embeddings.npy")

tracklet_emb_rows = []
tracklet_embs = []

for (camera_id, track_id), group in emb_meta_df.groupby(["camera_id", "local_track_id"]):
    idxs = group["embedding_index"].values
    embs = embeddings[idxs]

    mean_emb = embs.mean(axis=0)
    mean_emb = mean_emb / np.linalg.norm(mean_emb)

    emb_index = len(tracklet_embs)
    tracklet_embs.append(mean_emb)

    tracklet_emb_rows.append({
        "tracklet_embedding_index": emb_index,
        "camera_id": camera_id,
        "local_track_id": int(track_id),
        "num_crops": len(group),
        "mean_quality_score": float(group["quality_score"].mean())
    })

tracklet_embs = np.vstack(tracklet_embs)
tracklet_emb_df = pd.DataFrame(tracklet_emb_rows)

save_numpy(tracklet_embs, PROJECT_ROOT / "outputs/embeddings/tracklet_embeddings.npy")
save_csv(tracklet_emb_df, PROJECT_ROOT / "outputs/embeddings/tracklet_embeddings_meta.csv")

print("Tracklet embeddings:", tracklet_embs.shape)
tracklet_emb_df.head()

Tracklet embeddings: (364, 512)

,tracklet_embedding_index,camera_id,local_track_id,num_crops,mean_quality_score
0,0,MOT17-02-FRCNN,1,5,0.982400
1,1,MOT17-02-FRCNN,2,5,0.950629
2,2,MOT17-02-FRCNN,3,5,0.846067
3,3,MOT17-02-FRCNN,4,5,1.022948
4,4,MOT17-02-FRCNN,5,5,0.603006

# Some check

In [10]:
# Cell này thực hiện một bước cụ thể trong luồng pipeline, có thể là nạp dữ liệu, xử lý, hoặc lưu kết quả.
from pathlib import Path
import pandas as pd
import numpy as np

PROJECT_ROOT = Path.cwd()
if PROJECT_ROOT.name == "notebooks":
    PROJECT_ROOT = PROJECT_ROOT.parent

embedding_files = []
embedding_files += list((PROJECT_ROOT / "outputs").rglob("*embedding*.csv"))
embedding_files += list((PROJECT_ROOT / "outputs").rglob("*embedding*.npy"))
embedding_files += list((PROJECT_ROOT / "outputs").rglob("*embeddings*.csv"))
embedding_files += list((PROJECT_ROOT / "outputs").rglob("*embeddings*.npy"))

print("Embedding files found:")
for p in embedding_files:
    print(p)

for p in embedding_files:
    print("\nFILE:", p)
    if p.suffix == ".csv":
        df = pd.read_csv(p)
        print("Rows:", len(df))
        print("Columns:", list(df.columns)[:20])
        print(df.head())
    elif p.suffix == ".npy":
        arr = np.load(p, allow_pickle=True)
        print("Shape:", arr.shape)
        print("Dtype:", arr.dtype)

Embedding files found:
D:\hoiancomputervision\ticket_suspicion_project\outputs\embeddings\crop_embeddings_meta.csv
D:\hoiancomputervision\ticket_suspicion_project\outputs\embeddings\tracklet_embeddings_meta.csv
D:\hoiancomputervision\ticket_suspicion_project\outputs\embeddings\crop_embeddings.npy
D:\hoiancomputervision\ticket_suspicion_project\outputs\embeddings\tracklet_embeddings.npy
D:\hoiancomputervision\ticket_suspicion_project\outputs\embeddings\crop_embeddings_meta.csv
D:\hoiancomputervision\ticket_suspicion_project\outputs\embeddings\tracklet_embeddings_meta.csv
D:\hoiancomputervision\ticket_suspicion_project\outputs\embeddings\crop_embeddings.npy
D:\hoiancomputervision\ticket_suspicion_project\outputs\embeddings\tracklet_embeddings.npy

FILE: D:\hoiancomputervision\ticket_suspicion_project\outputs\embeddings\crop_embeddings_meta.csv
Rows: 1820
Columns: ['embedding_index', 'camera_id', 'local_track_id', 'frame_id', 'timestamp_sec', 'crop_path', 'quality_score']
   embedding_index       camera_id  local_track_id  frame_id  timestamp_sec  \
0                0  MOT17-02-FRCNN               1        44       1.433333
1                1  MOT17-02-FRCNN               1        43       1.400000
2                2  MOT17-02-FRCNN               1         6       0.166667
3                3  MOT17-02-FRCNN               1         5       0.133333
4                4  MOT17-02-FRCNN               1         7       0.200000

                                           crop_path  quality_score
0  D:\hoiancomputervision\ticket_suspicion_projec...       0.993238
1  D:\hoiancomputervision\ticket_suspicion_projec...       0.989640
2  D:\hoiancomputervision\ticket_suspicion_projec...       0.983757
3  D:\hoiancomputervision\ticket_suspicion_projec...       0.976241
4  D:\hoiancomputervision\ticket_suspicion_projec...       0.969124

FILE: D:\hoiancomputervision\ticket_suspicion_project\outputs\embeddings\tracklet_embeddings_meta.csv
Rows: 364
Columns: ['tracklet_embedding_index', 'camera_id', 'local_track_id', 'num_crops', 'mean_quality_score']
   tracklet_embedding_index       camera_id  local_track_id  num_crops  \
0                         0  MOT17-02-FRCNN               1          5
1                         1  MOT17-02-FRCNN               2          5
2                         2  MOT17-02-FRCNN               3          5
3                         3  MOT17-02-FRCNN               4          5
4                         4  MOT17-02-FRCNN               5          5

   mean_quality_score
0            0.982400
1            0.950629
2            0.846067
3            1.022948
4            0.603006

FILE: D:\hoiancomputervision\ticket_suspicion_project\outputs\embeddings\crop_embeddings.npy
Shape: (1820, 512)
Dtype: float32

FILE: D:\hoiancomputervision\ticket_suspicion_project\outputs\embeddings\tracklet_embeddings.npy
Shape: (364, 512)
Dtype: float32

FILE: D:\hoiancomputervision\ticket_suspicion_project\outputs\embeddings\crop_embeddings_meta.csv
Rows: 1820
Columns: ['embedding_index', 'camera_id', 'local_track_id', 'frame_id', 'timestamp_sec', 'crop_path', 'quality_score']
   embedding_index       camera_id  local_track_id  frame_id  timestamp_sec  \
0                0  MOT17-02-FRCNN               1        44       1.433333
1                1  MOT17-02-FRCNN               1        43       1.400000
2                2  MOT17-02-FRCNN               1         6       0.166667
3                3  MOT17-02-FRCNN               1         5       0.133333
4                4  MOT17-02-FRCNN               1         7       0.200000

                                           crop_path  quality_score
0  D:\hoiancomputervision\ticket_suspicion_projec...       0.993238
1  D:\hoiancomputervision\ticket_suspicion_projec...       0.989640
2  D:\hoiancomputervision\ticket_suspicion_projec...       0.983757
3  D:\hoiancomputervision\ticket_suspicion_projec...       0.976241
4  D:\hoiancomputervision\ticket_suspicion_projec...       0.969124

FILE: D:\hoiancomputervision\ticket_suspicion_project\outputs\embeddings\tracklet_embeddings_meta.csv
Rows: 364
Columns: ['tracklet_embedding_index', 'camera_id', 'local_track_id', 'num_crops', 'mean_quality_score']
   tracklet_embedding_index       camera_id  local_track_id  num_crops  \
0                         0  MOT17-02-FRCNN               1          5
1                         1  MOT17-02-FRCNN               2          5
2                         2  MOT17-02-FRCNN               3          5
3                         3  MOT17-02-FRCNN               4          5
4                         4  MOT17-02-FRCNN               5          5

   mean_quality_score
0            0.982400
1            0.950629
2            0.846067
3            1.022948
4            0.603006

FILE: D:\hoiancomputervision\ticket_suspicion_project\outputs\embeddings\crop_embeddings.npy
Shape: (1820, 512)
Dtype: float32

FILE: D:\hoiancomputervision\ticket_suspicion_project\outputs\embeddings\tracklet_embeddings.npy
Shape: (364, 512)
Dtype: float32